### ISSUE TITLE
[Feature] Adding the campaign beneficiary name also as a free text, not only by creating a separate profile

### ISSUE THREAD

**Issue by anikolova-bg** [podkrepi-bg/frontend#1006]
**The issue**
Currently to create a beneficiary, one need to create a separate profile of such, which sometimes makes the whole process of creating a campaign difficult, since not always the organiser is also the beneficient and not all beneficiary need to have a separate profile. Also there are some limits in the beneficiary profile name creation, which makes it difficult to type the full names.

**Proposed solution**
To have an option the beneficiary to be added by just typing the name as a free text, not only by creating a separate profile.

**Alternative options**
Having an option for free text type and adding a profile would be better. But if this is a challenge, we can go only with the freetext typing option, since the orginiser profile is more important in terms of transperency.

**Comment by igoychev** [comment]
When adding the beneficiary, we should consider that the names are not always enough from legal perspective:
- If the beneficiary is a person, we need to register him in the system with the names and his ID number
- If the beneficiary is a legal entity, we need to register him in the system with the company name and its registration number

For both cases the proposal of simply adding free text will not be enough.

**Comment by anikolova-bg** [comment]
How about giving the option of the organiser to add this info without asking for a separate profile of the beneficiary. The issue there is that this needs separate regisytration with email and in not every case the beneficiary has own email (if it is a kid, for examle).

**Comment by igoychev** [comment]
Ok agreed, then in the New Beneficiery form we need to have "skip email registration" option. We will still save the user in the database, but he will not be able to login.
