### ISSUE TITLE
[BankAccounts] Improvements on create/edit BankAccount

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1013]
**Describe the bug**
When creating or editing new Bank Account:
 - Status field should be a dropdown with available status values ( translated)
 - Account Type should be a dropdown with available status values ( translated)
 - fingerprint to be hidden - not needed for now

**To Reproduce**

1. Login as Admin user
2. Navigate to /admin/bankaccounts
3. Click on create/edit bank account
4. See the described improvements needed above

**Comment by AndreyGoranov** [comment]
Is this issue available to work on? If so can you please assign me to it.

**Comment by igoychev** [comment]
Yes, free and happy to see you want to take it!

**Comment by kachar** [comment]
Closed by https://github.com/podkrepi-bg/frontend/pull/1160
