### ISSUE TITLE
[Enhancement] Donations list filtering/sorting and export

### ISSUE THREAD

**Issue by stann1** [podkrepi-bg/frontend#1042]
These are requirements for the **admin panel only**:

At the moment, searching/filtering and sorting is performed as frontend action on the current page. This should all change to backend filtering/sorting and affect the whole result set.

**Acceptance criteria:**

As an admin,
1.  I can use advance filtering options:
- [x] date-range selector (working with the creation date of the donation) - any kind of date-range selector component will do
- [x] donation amount range - any kind of number range selector component (can be as simple as two input boxes 'more than' and 'less than').
2. I can apply standard filters to a set of donations, by:
- [x] payment type
- [x] campaign name
- [x] payment status (with default value selected 'succeeded')
- [x] donor name
- [x] billing name
- [x] billing email
- [x] payment provider
3. I can sort by all fields in the result grid
 - [x] I can export the donations
 - [x] I can export the filtered donations to a xlsx file

**Comment by igoychev** [comment]
Some of these are completed with https://github.com/podkrepi-bg/frontend/pull/1245 and https://github.com/podkrepi-bg/frontend/pull/1279 - marked above

**Comment by igoychev** [comment]
completed with https://github.com/podkrepi-bg/frontend/pull/1418
to export campaign donations the user needs to go to campaign list and click on the cell with the collected amount, which leads to the filtered donation list.
