### ISSUE TITLE
[Enhancement] Bank file imports

### ISSUE THREAD

**Issue by stann1** [podkrepi-bg/frontend#1043]
When importing a bank file that contains invalid entries, the admin does not get notified which entries cause the problem. There are several adequate measure to solve this, but to keep thing simple we can just implement the following steps:

**Acceptance criteria:**

On import of a valid xml file, that contains invalid entries
1. Accept a partially correct import and process the valid entries
2. Return in the response the count of the failed entries.
3. Return a file containing **only** the failed entries

On import of an invalid xml
1. Return a validation error only

**Comment by Juicebgs** [comment]
I will be writing multiple issues on problems with importing data, the proposal by @stann1 is ok when you have just a couple of donations. Currently we are importing 25+ bank donations per day and it is not ok to have partial import (if we don't check whether the donation has not already been imported).

**Comment by igoychev** [comment]
this functionality was greatly improved:
 - now there is error reporting for manual imports
 - also enabled automated imports via IRIS integraiton
Closing for now and please open new tickets for specific new improvements
