### ISSUE TITLE
New card delete account/profile

### ISSUE THREAD

**Issue by marianacat** [podkrepi-bg/frontend#1077]
**Delete account/profile**
Please change the card when the delete account is clicked.
Login/personal information/delete account/profile

**Additional context**
The new design and text can be found in the Figma file here:
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=14682%3A45152

![изтриване](https://user-images.githubusercontent.com/92619043/198989267-dd56ce86-559c-41cc-9f10-b81b155c0da6.png)

**Comment by Katzarov** [comment]
Starting to work on this, can I be assigned to it please.
