### ISSUE TITLE
Update the date format of 'Change birthdate' dialog

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1095]
Steps to reproduce:
1. Login
2. Open 'Profile'
3. Open 'Personal Information' tab.
4. Scroll down to 'Birthdate'. The date format is 'dd/MM/yyyy':
![image](https://user-images.githubusercontent.com/14351733/200903741-eb90000c-7bfd-4d08-89e8-b473c6ad45a9.png)
5. Click on 'Edit'. On the 'Change birthdate' dialog the date format is 'dd/MM/yyyy':
![image](https://user-images.githubusercontent.com/14351733/200904233-5313e9a9-8ebe-472f-bd40-5873206b306d.png)

Expected behavior: 
Unify the date format to be 'dd/MM/yyyy'.

**Comment by batebobo** [comment]
Hi @ani-kalpachka! The date format on the first screenshot is `dd.MM.yyyy` and on the second is `MM/dd/yyyy`. Can you please confirm that we prefer the latter?

Anyways I'd like to take this task. Can you please assign me, since I can't see a way to assign myself :)

**Comment by ani-kalpachka** [comment]
@batebobo I agree. We need dd.MM.yyyy format. 
The task is assigned to you. Thank you!

**Comment by batebobo** [comment]
Hi @ani-kalpachka! Can you please send some details about your browser (locale, language settings, etc.) :pray: I'm not able to reproduce the issue - I see the correct format in the dialog - `dd.MM.yyyy`.

The dialog uses a native `input type="date"` element that respects users' locale settings and its format can't be (easily) changed. On the other hand, the date in the _Personal Info_ tab is not localized - it's always `dd.MM.yyyy` and that's not okay for most locales.

**Comment by ovcharski** [comment]
I am reproducing the issue. I am attaching a .gif 
I am using Firefox on a Windows 11 laptop English US https://whatismybrowser.com/w/DGYC4LC

![edit-birthday](https://user-images.githubusercontent.com/48056945/202130942-c09d08b6-8d11-48b3-a7ed-218deaa78b30.gif)
