### ISSUE TITLE
Please add a "success" tag.

### ISSUE THREAD

**Issue by marianacat** [podkrepi-bg/frontend#1101]
Please add a "success" tag to the campaign: https://podkrepi.bg/campaigns/staya-za-ergoterapiya-v-pomosh-na-deca-s-narusheno-zrenie-ot-suunz-gr-varna

The label is located in a Figma file here: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=8281%3A24205&t=tt2bLmrJut1XRkuw-1

![label](https://user-images.githubusercontent.com/92619043/201852219-dc1b8fdc-e339-4761-8682-8aa0646cbffb.png)

**Comment by kachar** [comment]
Closed via https://github.com/podkrepi-bg/frontend/pull/1107
