### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mduchev** [podkrepi-bg/frontend#1102]
**Describe the bug**
When we have a smaller screen (either a smartphone, or a smaller desktop window), the section on the right that contains the share & donate buttons, as well as the donations, moves on the top of the screen. Upon scrolling this section isn't persisted and some of the content overflows on top of it.
This happens in both desktop & mobile version of Firefox. 

**To Reproduce**
Open any of the campaigns and scroll down.

**Expected behavior**
The top section, that contains the share & donate buttons, as well as the donated sum, to stay on top of all content and the rest of the page's content to slide behind it the same way the navigation header behaves.

**Screenshots**
Dekstop:
<img width="665" alt="Screenshot 2022-11-15 at 17 26 02" src="https://user-images.githubusercontent.com/8217099/201959527-97a0507e-e23e-43c3-bfaf-27b9ea2ed760.png">

Mobile:
![Screenshot_20221115-165928](https://user-images.githubusercontent.com/8217099/201956811-84c08606-4ee5-4978-96a8-a774b63b4f2c.jpg)
![Screenshot_20221115-165943](https://user-images.githubusercontent.com/8217099/201956827-e61e48fc-d70e-4415-9f73-81030f70fd51.jpg)

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.0.1
- Browser Firefox
- Version 107.0

**Smartphone (please complete the following information):**
- Device: Pixel 4 XL
- OS: Android 13
- Browser: Firefox
- Version: 106.1.0

**Comment by kabaivanov** [comment]
Proposed fix would be:

.CampaignDetails-beneficiaryAvatar { z-index: -1; }

_/sorry, new here.. still haven't gotten the time to get to know the platform code, and not really ready to actually implement a fix/_
