### ISSUE TITLE
[Bug] Campaign's donation block is not fully visible

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1108]
Steps to reproduce:
1. Go to https://podkrepi.bg/campaigns
2. Open a campaign
3. Observe the campaign's donation block - it is not fully visible at the bottom until the user scrolls down to the bottom of the page and the last donor and the pagination are cut:

![image](https://user-images.githubusercontent.com/14351733/202127446-13f11999-9c55-476e-b6b3-045ec6e433ca.png)

Expected behavior: It should be fully visible.

**Comment by ani-kalpachka** [comment]
Depends on https://github.com/podkrepi-bg/api/issues/364

**Comment by kabaivanov** [comment]
Possibly implement a sticky sidebar solution that fixes the issue.

https://github.com/vursen/FloatSidebar.js

**Comment by ani-kalpachka** [comment]
@kabaivanov The donation component currently has a sticky position, but we need to resolve the cutting of the content which is possibly caused by some heights and spacings.

**Comment by kabaivanov** [comment]
> @kabaivanov The donation component currently has a sticky position, but we need to resolve the cutting of the content which is possibly caused by some heights and spacings.

Sorry, I did not mean a sidebar that has a **position: sticky** property, but rather one of the scripts written to tackle exactly that issue.

FloatSidebar.js or sticky-sidebar.js

**Comment by ani-kalpachka** [comment]
The issues is currently fixed.
