### ISSUE TITLE
[Feature] Remove whitespaces from IBAN

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/frontend#1109]
**Is your feature request related to a problem? Please describe.**
When contributing to a campaign via bank transfer the IBAN of the organization is shown. It, currently, contains whitespaces which cause issues when copy-pasting it into online banking. To ease users, we should remove the whitespaces.

**Describe the solution you'd like**
Remove the whitespaces from the IBAN:
![image](https://user-images.githubusercontent.com/16187050/202271635-49168985-fb18-4db1-8609-163e92dcb4f4.png)

**Comment by valkirilov** [comment]
@imilchev I see that this behavior is causing issues when people copy/paste the IBAN, but we must admit that it's looking better (and way more easier) if you read and type manually when there are such "blank space" separators. 

So, how about applying this change only to the IBAN when you use the "Copy" button?
- keep the visuals of the IBAN as it is now, with spaces to separate each portion
- trim automatically the spaces before putting the IBAN it into the clipboard when you use the "Copy" button next to it

**Comment by igoychev** [comment]
I support the trimming to be on the copy button, and leave the text with spaces.
