### ISSUE TITLE
[Bug] Campaigns progress bars mismatch.

### ISSUE THREAD

**Issue by kabaivanov** [podkrepi-bg/frontend#1111]
Upon loading the homepage _sometimes_ there appears to be a progress bar mismatch.
(Second time see this happen, but this time was able to make screenshots.)

**To Reproduce[hard]**
1. Go to 'Homepage'
2. See campaign progress bars reporting wrong values.
3. Resize browser window.
4. Bars shift, but still some are wrong.
5. Refresh and it's gone. _Hard to reproduce. Does not always happen._

**Expected behavior**
Progress bars that always reflect the actual progress of the campaigns in real time.

**Screenshots**
<img width="1992" alt="campaign-progress-bar-bug" src="https://user-images.githubusercontent.com/118026471/202327194-79022885-c878-44f9-98d0-dee161478341.png">
<img width="1325" alt="campaign-progress-bar-bug-resized" src="https://user-images.githubusercontent.com/118026471/202327219-ce136c52-717a-4304-b099-95ed565c3fad.png">

**Desktop:**

- OS: Mac OS X 12.4
- Browser: Safari 
- Version: 15.5

**Comment by ani-kalpachka** [comment]
I tested this issue for desktop and mobile on Chrome and Firefox and could not reproduce it.
Could you confirm it is fixed?

**Comment by igoychev** [comment]
The issue was caused by the randomization of the order of campaigns. The logic was refactored so not the progress bar mismatch is not happening anymore.
