### ISSUE TITLE
[Bug] The collected amount of money in Campaign card appears as NaN on local environment 

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1112]
The bug is valid for Homepage and for Campaigns listing page and only for local environment:

![Screenshot 2022-11-17 075009](https://user-images.githubusercontent.com/14351733/202366997-d2ce1299-9ad1-4c12-8c26-41cf4bbf6cb8.png)

**Comment by AnzheloD** [comment]
I cannot reproduce it. Maybe it has been fixed in another issue?

**Comment by ani-kalpachka** [comment]
I tested it again and reproduced it for Chrome and Firefox.

**Comment by ani-kalpachka** [comment]
Closing the ticket since it seems to be currently resolved:

![image](https://user-images.githubusercontent.com/14351733/205579324-0083995b-079a-4731-b8fe-708bfdfcde91.png)
