### ISSUE TITLE
[Bug] A wish is listed on a campaign page despite the user cancelling the donation process

### ISSUE THREAD

**Issue by ovcharski** [podkrepi-bg/frontend#1116]
**Describe the bug**
A wish is listed on a campaign page despite the user cancelling the donation process

**To Reproduce**
I am donating to dev.podkrepi.bg via a card (not bank transfer)

1. Write a wish (послание)
2. Click Finish (премини към плащане)
3. A stripe checkout page is opened
4. Do not pay. Click back button

**Expected behavior**
The wish should not be listed on the campaign page

**Actual behavior**
The donation payment did not occur, but the wish is listed on the campaign page

**Desktop (please complete the following information):**

Windows 11 PC, Fireofx v106

![Poslanie-payment-back](https://user-images.githubusercontent.com/48056945/202486942-665cf12f-6035-4cbc-b86d-4e2c09c26625.gif)

**Comment by AnzheloD** [comment]
It's a bug on BE.  There is a check in donations.service.ts , if sessionDto.message exists to create a donation wish.

**Comment by kachar** [comment]
Indeed that seems to be a platform downside, but the upside is that the message of the user is not lost forever.

I suggest that we keep the message in the database but add a new field `status` to the wish object to keep it's current state. 

This will fit to the long term vision for the wishes where we need to moderate the content and unpunish certain comments.

Some ideas for statuses:

- `new`
- `published`
- `archived`
- `deleted`
- `spam`

Then when we fetch the comments we will show only the published ones.

@ovcharski @AnzheloD please share your vision

**Comment by AnzheloD** [comment]
It's a good idea to have a status field, but in this case the wish shouldn't be kept at all, because the payment wasn't successful. I don't think we need such records in database

**Comment by kachar** [comment]
Yep The wish acts as a comment to the campaign. We should publish the wish after a successful donation. 

The main point is to never discard user input as this can make them anxious and close the tab.

**Comment by igoychev** [comment]
The fix for this could be quite easy if when getting the donationWishes in findWishesByCampaignId the select statement from prisma to return only those issues that are connected to a card donation with state = succeeded. 

Note that DonationWishes with no relation to Donation still need to be returned as they are coming from Bank Donations currently and that needs to be fixed separately.

**Comment by kachar** [comment]
> Note that DonationWishes with no relation to Donation still need to be returned as they are coming from Bank Donations currently and that needs to be fixed separately.

We can set a process to publish the bank wishes when a successful bank donation is imported.
