### ISSUE TITLE
[Bug] Unable to load campaign thumbnails

### ISSUE THREAD

**Issue by kabaivanov** [podkrepi-bg/frontend#1117]
**Describe the bug**
Image thumbnail links on campaigns page appear to break _sometimes_

**To Reproduce[hard]**
Visit the campaigns page from time to time

1. Click on "Дарете/Donate"
2. See (can't) campaign thumbnail images. 

**Screenshots**
<img width="1309" alt="Screenshot 2022-11-17 at 17 20 10" src="https://user-images.githubusercontent.com/118026471/202487205-ced46a8d-f27b-4759-ae1e-276f86aa486a.png">
**Desktop::**

- OS: Mac OS X 12.4
- Browser: Safari 
- Version: 15.5

**Additional context**
Does not always seem to happen, but It happened to me two times in the last 15 min so I am reporting it as a bug.

**Comment by ani-kalpachka** [comment]
This does not seems to be currently valid.
Also according to the new design the campaign cards and the images are going to be updated.
I think we can close this issue. If the problem with the images is still there after the update, we can open another one referring to the new UI.
