### ISSUE TITLE
[Bug] Terms and Conditions and GDPR checkboxes in registration are not required

### ISSUE THREAD

**Issue by YanchoK** [podkrepi-bg/frontend#1118]
You can register without checking Terms and Conditions checkbox and GDPR checkbox

**Expected behavior**
You should not be able to register if you dont check both Terms and Conditions and GDPR checkbox. If you try to do so there should be some error message.

![image](https://user-images.githubusercontent.com/50592845/202732368-61910513-54f0-47fe-b0cf-9b10e2c16c2a.png)

**Comment by kachar** [comment]
The problem can be tackled by adding validation to these two fields

Code references

- https://github.com/podkrepi-bg/frontend/blob/dd3d3ef60253f5f3af641cf8019e797b993b07cb/src/components/auth/register/RegisterForm.tsx#L30-L34
- https://github.com/podkrepi-bg/frontend/blob/a2832377f5e69d64902e5f5c2b9b99bbdaa193ae/src/components/contact/ContactForm.tsx#L30-L31

```tsx
terms: yup.bool().required().oneOf([true], 'validation:terms-of-use'),
gdpr: yup.bool().required().oneOf([true], 'validation:terms-of-service'),
```
