### ISSUE TITLE
[Bug] confirm password field in registration is not required

### ISSUE THREAD

**Issue by YanchoK** [podkrepi-bg/frontend#1119]
**Describe the bug**
You can register without filing anything in confirm password field. It does its job only if you fill something.

**Expected behavior**
If the confirm password field is empty, there should be some error message and you should not be able to register without filling it.

**Comment by kachar** [comment]
The problem can be tackled by adding validation to these two fields

Coffee references

https://github.com/podkrepi-bg/frontend/blob/dd3d3ef60253f5f3af641cf8019e797b993b07cb/src/components/auth/register/RegisterForm.tsx#L30-L34

https://github.com/podkrepi-bg/frontend/blob/a2832377f5e69d64902e5f5c2b9b99bbdaa193ae/src/components/contact/ContactForm.tsx#L30-L31

```tsx
terms: yup.bool().required().oneOf([true], 'validation:terms-of-use'),
gdpr: yup.bool().required().oneOf([true], 'validation:terms-of-service'),
```

**Comment by jozef-drabik** [comment]
Can i take this issue and work on it ?

**Comment by kachar** [comment]
@jozef-drabik Sure thing! Feel free to tackle it

**Comment by jozef-drabik** [comment]
Thanks. Will create PR as soon as possible.
