### ISSUE TITLE
[Bug] Email field on the Login page is not trimmed automatically

### ISSUE THREAD

**Issue by valkirilov** [podkrepi-bg/frontend#1124]
**Describe the bug**
When you enter your email on the "**Login**" page and you accidentally put a leading/trailing space, it results into failed login because of invalid credentials. On most of the websites it's a common practice to ignore those "false" spaces when verifying the credentials, so we may apply it as well.

_Note: It can be considered as a change request, not a bug._
_Note: The same behavior is observed for the password field as well, but the safe approach is to apply this only for the "E-mail" field._

**To Reproduce**

1. Go to 'https://dev.podkrepi.bg/login'
2. Enter valid email for an existing account in the "**Email**" field, but put one additional space in the beginning/end of it
3. Enter valid password in the "**Password**" field _(valid password for the account matching the above email)_
4. Click on the "**Login**" button and see the following error - "**Wrong username / password.**"

**Expected behavior**
Instead of showing a misleading error message, we should trim the spaces from the "**E-mail**" field automatically, which will result into a successful login action.

**Screenshots**
![image](https://user-images.githubusercontent.com/1233496/202757569-a5958a53-2b52-46b2-aae2-ad35aa6a19e6.png)
![image](https://user-images.githubusercontent.com/1233496/202758911-f91e9b83-3145-493c-a8f1-27adf3d6174c.png)

**Additional context**
This bug is not dependent on any desktop/mobile/OS.

**Comment by kachar** [comment]
I can confirm the problem. We need to add `trim()` to the yup validation chain for the email and other fields. We also need to apply it to all authentication forms, not only login forms.

Thanks for bringing it up @valkirilov

**Comment by Nnachevvv** [comment]
I would like to take this bug :)
