### ISSUE TITLE
[Feature] Pagination on the messages on a Campaign

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1129]
**Is your feature request related to a problem? Please describe.**
We need some way to limit the messages. We are fetching too many of them, there should be pagination

**Describe the solution you'd like**
Infnite scroll would be the best solution I think, but a simple pagination would also do! Might require some work on the api

**Comment by Katzarov** [comment]
Is anyone working on this? If not, can I be assigned to it? I think it would be a good first full-stack issue for a newcomer like me.
