### ISSUE TITLE
[dev] Upgrade yarn to latest

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1145]
**Is your feature request related to a problem? Please describe.**
We are using yarn v1 while latest is v3.3

**Describe the solution you'd like**
Looking at the upgrade instructions here: https://yarnpkg.com/getting-started/install it just requires running 
```
yarn set version stable
```
and then updating the .gitignore file as per https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

**Comment by kachar** [comment]
We also need to make sure that the Docketfile images are able to build and run smoothly. 

Let's roll this change both to frontend and API repos so we use the same stack.
