### ISSUE TITLE
[Feature] Dump logs to a file with a downloadable artifact in the CI/CD

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1149]
**Is your feature request related to a problem? Please describe.**
In order to be able to debug in the CI/CD it would be good to have the logs on file you can download, after an errored out action

**Describe the solution you'd like**
Next is already logging in the console when you run the project, we should dump these logs to a file that can be downloaded when the CI/CD actions is run

**Comment by imilchev** [comment]
This is no longer required since we approached the issue differently
