### ISSUE TITLE
[Feature] Update login forms

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#1155]
**Is your feature request related to a problem? Please describe.**

The login form components lack the `autoComplete` attribute over the email field.
The browsers are smart enough to pick it up from attributes like `name="email"` and `label="Email"`.
Anyway, there are users that reported that the fields are not auto-completed by their browser or password browser add-on.

**Describe the solution you'd like**
Extract the email field as a separate component `EmailField`, just like `PasswordField`, and reuse it in the forms.

**Additional context**
Related to #1120

**Comment by antonmihaylov** [comment]
Feel free to assign it to me if no one else wants it. I don't have a lot of time those days, but I can get it done next week.
