### ISSUE TITLE
[Bug] Campaigns' banner images are cut on tablet and mobile devices

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1172]
Steps to reproduce:
1. Go to campaigns listing page.
2. Choose a campaign.
3. Apply responsive view smaller than 900px screen width. 
   - Note: This is a default MUI breakpoint - md, medium: 900px
5. Observe that the image is cut from the top because the Donation block overlaps it:

![image](https://user-images.githubusercontent.com/14351733/203713225-dec93c97-0d5a-48d4-89b1-1d3eb5f4bdb6.png)

Expected behavior:
Campaigns' images are fully displayed.

**Comment by kabaivanov** [comment]
I think this should fix it, but can't really test it locally since I still don't have the back-end running.

frontend/src/components/campaigns/CampaignDetails.tsx

Insert after line 44:

```
[theme.breakpoints.down('md')]: {
     top: '165px',
 },
```

**Comment by kachar** [comment]
// offtopic

@kabaivanov For development purposes, you can link your local frontend environment to the staging server.

Edit the file `.env.local` and restart frontend server
```shell
API_URL=http://localhost:5010/api/v1
API_URL=https://dev.podkrepi.bg/api/v1
```

**Comment by kabaivanov** [comment]
> // offtopic
> 
> @kabaivanov For development purposes, you can link your local frontend environment to the staging server.
> 
> Edit the file `.env.local` and restart frontend server
> 
> ```shell
> API_URL=http://localhost:5010/api/v1
> API_URL=https://dev.podkrepi.bg/api/v1
> ```

That sounds sweet!

I tried it, and got an error that pointed to editing the next.config.js file line 40 regarding image domains. Did that, and the campaigns page started showing some content, but couldn't load the single campaign page (where the issue in this ticket applies to). Got a new set of errors:

> Error: Text content does not match server-rendered HTML.
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> Error: Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

**Comment by kachar** [comment]
@kabaivanov It's recommended to have these topics in Discord. Feel free to join the conversation there. Besides that, you may want to update your branch with the latest master. There were many recent changes and the problem you mention might already be fixed there.
