### ISSUE TITLE
[Feature] Backend for uploading reports to Campaigns

### ISSUE THREAD

**Issue by batebobo** [podkrepi-bg/frontend#1176]
**Is your feature request related to a problem? Please describe.**
Backend of #1093

- [ ] DB schema changes to create reports and associate them to campaigns
- [ ] Endpoints and services for CRUD operations on reports

**Comment by kachar** [comment]
@batebobo Maybe this issue needs to be opened in https://github.com/podkrepi-bg/api

**Comment by batebobo** [comment]
Yup, you're right, thanks! I'll close it here and reopen in the api repo :bow:
