### ISSUE TITLE
[Feature] Filter&Search for Donations Grid in Admin View

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1184]
**Is your feature request related to a problem? Please describe.**
With the growing count of campaigns and donations the need comes for having better ways of searching and filtering of the donation grid in Admin View. Currently the grid shows all donations X per page, but they can only be sorted and not filtered or searched.

**Describe the solution you'd like**
When opening /admin/donations the page to allow:

- [ ] default page size to be 20 and selectable by dropdown
- [ ]  filtering of donations by status(deleted hidden by default)
- [ ]  filtering of donations by type
- [ ]  filtering of donations by date created(range)
- [ ]  Search by names, email

**Describe alternatives you've considered**
The filters could be on the grid column titles or as separate toolbar above the grid

**Additional context**

**Comment by AndreyGoranov** [comment]
Assign me
