### ISSUE TITLE
[Bug] The images on Homepage are not responsive

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1186]
**Describe the bug**
The images on Homepage are not responsive.

**To Reproduce**
1. Go to 'Homepage'.
3. Scroll down to 'Кой стой зад Подкрепи.бг' and 'Присъединете се зад Подкрепи.бг'.
4. Switch to mobile view.
5. Observe the images.

**Expected behavior**
The images on Homepage are responsive and adaptive for each resolution.

**Screenshots**

![1](https://user-images.githubusercontent.com/14351733/203907811-e880118d-3a04-4b86-9b6c-121679c01799.png)

![2](https://user-images.githubusercontent.com/14351733/203907825-59204019-a664-4c97-ac48-6759f1ca2a7c.png)

**Comment by Jarhead9956** [comment]
Проблема е, че размера на снимките е хардкоднат, но не знам как да го прменя.
![Screenshot (3)](https://user-images.githubusercontent.com/80678422/204005294-d7a9deb7-7f63-4fcb-ba02-b27ad1537d9d.png)

**Comment by Jarhead9956** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/80678422/204007373-7325640d-1d52-4f7c-a92e-52251eae590e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/80678422/204007375-7cb811a0-bd50-4794-a4dc-1a17b88388a3.png)

**Comment by pshumareva** [comment]
Ще може ли да ме assign-нете на това issue?

**Comment by Jarhead9956** [comment]
Аз нямам достъп или незнам как да те assign - а

На пт, 25.11.2022 г. в 16:54 ч. Pepa Shumareva (Pepsi) <
***@***.***> написа:

**Comment by dimitur2204** [comment]
Where are you on the issue @pshumareva?

**Comment by pshumareva** [comment]
Going to push the changes today.
