### ISSUE TITLE
[Bug] XML Bank Payments Import - "вноска на каса" 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#1205]
When somebody donates via bank transfer but gives the money cash to the bank cashier, the **MovementFunctionalType** type will contain the following string "Вноска на каса". In this case the tag **OppositeSideName** will be empty (nil="true"). This tag is necessary in order for the import to be successful. 

We should modify the import to not expect   **OppositeSideName** when we have "Вноска на каса".

**Comment by kachar** [comment]
@Nnachevvv With @igoychev we'll be checking if the requirements are resolved by the PR that you've provided.

From the description above it looks like the business requirement differs a bit from the actual implementation. Unfortunately, I saw that too late.

> the import to not expect OppositeSideName when we have "Вноска на каса".

**Comment by igoychev** [comment]
checked, reviewed and tested by @kachar and @igoychev
