### ISSUE TITLE
[Feature] Admin panel: Change user in anonymous stripe donations

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#1206]
In #958 we have added the option to change the user of a donation when it originates from bank transfer. 
We will need the same feature for anonymous stripe donations (Please note if the donation is NOT Anonymous it shouldn't be editable). 

The reason behind this request : If a donations is not associated with a user, he or she won't be able to have a donation certifcate and not able to use tax deduction. Some people donate anonymously by mistake and then would like to see their donations in their profile.

**Comment by igoychev** [comment]
To make this low-hanging fruit:
Currently only the donor of the bank donations is editable in AdminUI.  The needed change is to allow also card donations person to be editable and the logic for it is on this line:
https://github.com/podkrepi-bg/frontend/blob/9a9c4ec21d8e7b79db82a68deba5319b2a14e7e1/src/components/donations/grid/Grid.tsx#L205

**Comment by mariatopchieva** [comment]
Can I be assigned to this issue, please :)

**Comment by igoychev** [comment]
@mariatopchieva  ping - would you have time to complete this?

**Comment by mariatopchieva** [comment]
> @mariatopchieva ping - would you have time to complete this?

@igoychev I unassigned myself, I am having some issues and will take another task at a later moment. Sorry for blocking it until now.
