### ISSUE TITLE
All sticky payment cards on the right to be updates - campaign pages 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1220]
![Right payment card](https://user-images.githubusercontent.com/75036745/204932869-3a4c1208-eaa8-44e0-a980-f98b11b432b7.png)
As a donor user I would like to be able to pay and understand progress of the campaign goal upto cents, also how have you checked the campaign so that I am well aware and can make a payment on the portal

Acceptance criteria: 
- Tags on the top to be to change state on hover with a link to FAQ  https://podkrepi.bg/faq/campaigns (this is may be for another issue too) @MariK to add all explanation on others, posetena na miasto, etc. 
Prototype: https://www.figma.com/proto/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?page-id=0%3A7243&node-id=15737%3A46932&viewport=-2271%2C-29022%2C0.81&scaling=min-zoom&starting-point-node-id=7596%3A22594
- See all donation = should be a link which leads to the bottom of the campaign page where all donation can be seen in the expanded view of the campaing page where all donators and all messages can be seen

**Comment by swolf86** [comment]
@atomov93  if you remember/know where is our github issue to add documents, guarantors and other explanation to the FAQ please attach

**Comment by dimitur2204** [comment]
@swolf86 Looks great! Only one question. Where is the "See all ->" button supposed to lead or what is it supposed to do?

**Comment by swolf86** [comment]
@dimitur2204 
See all will lead to expanded view of the campaign page with all comments

**Comment by dimitur2204** [comment]
> @dimitur2204
See all will lead to expanded view of the campaign page with all comments

What we have now is the pagination with the arrows to show more donations. What is the vision for that expanded view, because we cannot just expand it to the bottom of the page. Should a scroll come up when it's expanded?

**Comment by swolf86** [comment]
Expanded view is linked to the new campaign design 
In the new design there is expanded view where you can see all donations all wishes 
By scroll I mean some sort of anchor the the bottom of the page where you can read comments and wishes

**Comment by swolf86** [comment]
New campaign design page https://github.com/podkrepi-bg/frontend/issues/1072

**Comment by dimitur2204** [comment]
@swolf86
And these three fields on top of the card:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/61479393/206915096-32e180ed-3985-4962-97ea-99ae83233219.png">
What information exactly should we show there. Asking specifically for "Документи: Проверена", "Други: ...". 
Where do we get that from, I don't see it on current pages?

**Comment by swolf86** [comment]
We should have a an explanation of documents: checked, others and etc this explanation should be on FAQ. And then we should have a link to FAQ page 
Also these links should be change state e.g colour light blue 
Does it make sense?

**Comment by swolf86** [comment]
Here's explanation of the tags documents, tags 
https://docs.google.com/spreadsheets/d/1QfWNWorA1fGPetqunSsmuMYBdI2jFMgr-CGyEW4qXAc/edit#gid=0

**Comment by swolf86** [comment]
Please reopen the all sticky payment card issue 

New design emphasizing on the percentage a little more states 
90% - should trigger a little bit more state( state 2) 
Tabs between last 3 payment / last 3 wishes 
See all would anchor to the end of the page to be linked with another issue  

![Mobile card  step 1](https://user-images.githubusercontent.com/75036745/228371398-15fc3712-94bd-4f48-93a3-20d9d34c0219.jpg)
![Mobile card  step 2](https://user-images.githubusercontent.com/75036745/228371817-d1ef9cae-2393-49db-9716-c61f4207fdfd.jpg)

![Mobile card  step 3](https://user-images.githubusercontent.com/75036745/228371407-e469673b-86bc-4aa5-9d75-ee0013c717e0.jpg)
![Sticky sidebar desktop+](https://user-images.githubusercontent.com/75036745/228371408-e75301f3-5cc8-43ff-95ba-e977492e8069.png)


this issue is linked to campaign epic https://github.com/podkrepi-bg/frontend/issues/1072
