### ISSUE TITLE
[Bug] Campaigns listing page is not full width

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1227]
**Describe the bug**
Campaigns listing page is not full width.

**To Reproduce**
1. Go to https://podkrepi.bg/campaigns
2. Observe the spacing around the campaigns listing section.

**Expected behavior**
Campaigns listing section has to be full width identical to the campaigns listing section on Homepage.

**Screenshots**
Campaigns page:
![image](https://user-images.githubusercontent.com/14351733/205310862-5ab014d0-8a90-4517-8d39-705baddc22ad.png)

Homepage:
![image](https://user-images.githubusercontent.com/14351733/205311115-9816d348-c232-43fb-8f34-ecb1ee6edc18.png)

**Comment by kachar** [comment]
@ani-kalpachka I think it's intentional to have a max width of the container. I would personally reduce the width of the homepage to a certain size. On a big screen like 24" it looks really annoying.

**Comment by kabaivanov** [comment]
> @ani-kalpachka I think it's intentional to have a max width of the container. I would personally reduce the width of the homepage to a certain size. On a big screen like 24" it looks really annoying.

Double that, here's a screenie from my 27k iMac at it's default 5k resolution.
<img width="2560" alt="Screenshot 2022-12-03 at 22 02 00" src="https://user-images.githubusercontent.com/118026471/205459708-b940d386-13f0-4edf-bfd3-eca47a8e8439.png">

@ani-kalpachka if you see what we mean, let's rename the ticket name and just fix the homepage instead.

**Comment by swolf86** [comment]
I think we can adapt the code that photos střech also title leaves a lot of space below
The benefit of having full width is that you use the whole real estate and see bigger more impactful cards  with photos 
Can we try to find optimal solution

Btw it should say urgent campaigns as some of them are competed

**Comment by kachar** [comment]
@swolf86 We're talking about the space on the side - if we make the content full-width of the page it will look cluttered and users will actually see less relevant with a broader focus area. 

What @kabaivanov and I are suggesting is that we use a narrower focus for the user and use the native up/down scroll to see more campaigns.

See for example how github are handling that with space on the sides

![image](https://user-images.githubusercontent.com/893608/205478949-2ce84d89-4854-4e91-b132-b0a6fd3a2bc5.png)

**Comment by kachar** [comment]
Adding some preview for brevity

:two: `maxWidth: lg` | :one: `maxWidth: 100vw`
---|---
![image](https://user-images.githubusercontent.com/893608/205486243-e1c507f6-c1a5-4bd6-90a6-81937cc65907.png)|![image](https://user-images.githubusercontent.com/893608/205486261-2f4bd04a-cdd8-461f-bf3e-4347c38b4ea3.png)
![image](https://user-images.githubusercontent.com/893608/205486293-866cbe85-fb77-46b0-9300-5bb7dd38f92e.png)|![image](https://user-images.githubusercontent.com/893608/205486326-277e266f-d6a1-4c7d-8374-51df9fcd1ed0.png)

**Comment by swolf86** [comment]
> We need to have an identical solution for Homepage and Campaigns page since they are currently different. Here are some suggestions:
> 
> 1. Full width for both pages. (I agree with you it could not look good for larger screens and may not be the best one.)
> 2. Side space for both pages.
> 3. Full width for less than 1536px (MUI xl breakpoint) and add space for larger screens.
> 
> Please share opinions. @swolf86 @kachar @kabaivanov

I am in favour of option 3. 
You can see how in option 2 most of the height is taken in writing the title. In option 1 the size of the cards should adjust

**Comment by ani-kalpachka** [comment]
Thanks for the opinions!
@kachar I was referencing the width of the Campaigns section only. 
So we are going to have to decide between 2 and 3. I personally think that 3 would be an optimal solution because it saves the width of the Campaign cards like @swolf86 suggested and it also would apply side space spaces for larger screens.

Here is how it looks like for maxWidth: lg

![Screenshot 2022-12-04 175331](https://user-images.githubusercontent.com/14351733/205501268-886b071d-f56e-45e4-95a8-69f4664386d1.png)

And for maxWidth: 100vw

![image](https://user-images.githubusercontent.com/14351733/205501333-dfcb1904-9d4b-44b5-b105-e6a0beb4133d.png)

**Comment by kachar** [comment]
> You can see how in option 2 most of the height is taken in writing the title. In option 1 the size of the cards should adjust 

I see that's this is a problem of the card layout and number of items per row. We trying to fix a poor card layout and font sizes with inadequate techniques. I don't consider this to be a long term solution.

**Comment by kachar** [comment]
@swolf86 Please check out the Material Design guidelines so we're all in sync with the options here:

- https://m3.material.io/components/cards/guidelines#1a70a07f-8b3f-4f7c-8bc0-e89a58b8f528
- https://mui.com/material-ui/react-card/

**Comment by igoychev** [comment]
+1 for option 3 from @ani-kalpachka 
3. Full width for less than 1536px (MUI xl breakpoint) and add space for larger screens.
