### ISSUE TITLE
[Bug] [Admin/Donations] Paging arrows are not clickable

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1229]
**Describe the bug**
We have paging arrow icons "<" and ">" on admin donation grid, but they are not clickable. It is possible to click them only if carefully aiming at the edge of the circle - see short video. Note, that this works well on the admin/campaigns grid.

**To Reproduce**

1. Login as Admin - check how to setup backend [here](https://github.com/podkrepi-bg/api#create-docker-containers-for-the-dev-databasepostgres-and-the-identity-serverkeycloak)
2. Go to /admin/donations
3. Make sure you have more than 5 donations
4. Try to move on next page or to change the rows per page
5. See how mouse doesn't change to "hand" for clicking 

**Expected behavior**
Clicking on the paging arrows < > or on "rows per page" dropdown to be possible.

**Screenshots**

https://user-images.githubusercontent.com/7055304/205483830-1b5c87b6-387c-46eb-94fe-f8b96ce058a3.mov

**Comment by kachar** [comment]
@igoychev This has already been solved via GTM. Discord chat bot is not showing anymore in any of the `/admin*` pages.

Can you please validate if the ticket is about an ongoing issue?

**Comment by kachar** [comment]
Alright, I saw what's going one. When user visits the page directly or refreshes the page the Discord icon is now showing.

But when the user comes from another page where Discord is enabled, it's not getting hidden automatically.

No idea how to solve this on the GTM side.

**Comment by igoychev** [comment]
Ah, I was looking at production and it was happening there. Now I checked on dev.podkrepi.bg and it looks fixed, so we just need to deploy...

**Comment by igoychev** [comment]
Deployment done, issue is fixed on prod.
