### ISSUE TITLE
Home page layout improvemet

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#124]
![info-site-sug](https://user-images.githubusercontent.com/75036745/111613622-9fe0e800-87d6-11eb-950e-c453f40d64ba.jpg)
![info site sugArtboard 2](https://user-images.githubusercontent.com/75036745/111616541-e7b53e80-87d9-11eb-9839-b37cd2a722ee.jpg)
![Volunteer](https://user-images.githubusercontent.com/75036745/111616543-e84dd500-87d9-11eb-93d3-92c8cf440c65.png)
![Мисия, Визия и Цели Напална страница инфо сайт](https://user-images.githubusercontent.com/75036745/111616544-e8e66b80-87d9-11eb-80b0-201f5764be07.jpg)

**Comment by swolf86** [comment]
1вото голямо изображение показва стил, разположение, размери
2 фон на заглавната част
3 Доброволец
4 фон мисия визия и цели

**Comment by codemenivo** [comment]
1. Това изображение с каратата за мене е много ясно и силно послание.
2. Така предложената структура на страницата дава ясна представа за:
   - Какво правим
   - От кого се прави
   - Каква е крайната цел
3. Мисля, че е прекрасна начална страница.

**Comment by kachar** [comment]
Adding some links for the rocket guide path:

- https://tympanus.net/codrops/2019/12/03/motion-paths-past-present-and-future/
- https://codepen.io/cassie-codes/pen/81fb45e6c28410f52be88ed8ae8d3e4b

**Comment by swolf86** [comment]
Info графика за начална страница 

![подкрепиБГ-инфографика-2 1-320](https://user-images.githubusercontent.com/75036745/112995369-0cf36680-9163-11eb-8ca4-a2fb867996ae.jpg)
![подкрепиБГ-инфографика-2 1-1096](https://user-images.githubusercontent.com/75036745/112995372-0d8bfd00-9163-11eb-9221-43945a7d355a.jpg)

**Comment by kachar** [comment]
@swolf86 Може ли да качиш svg вариант, ще бъде по-лесен за работа

**Comment by swolf86** [comment]
SVG
![image](https://user-images.githubusercontent.com/75036745/112997347-f2ba8800-9164-11eb-977b-f869ad1a5e48.png)

Къде в фигма, Кои файл

**Comment by swolf86** [comment]
[how it works graphics .zip](https://github.com/daritelska-platforma/frontend/files/6229525/how.it.works.graphics.zip)

**Comment by swolf86** [comment]
[info graphics.zip](https://github.com/daritelska-platforma/frontend/files/6244347/info.graphics.zip)
updated graphics

**Comment by kachar** [comment]
Uploaded the svg to figma at https://www.figma.com/file/IGERJuRUhZohuxq5b3O73w/Podkrepi.bg-Wireframes?node-id=1163%3A1461

**Comment by kachar** [comment]
@ani-kalpachka Can you please share your progress and roadblocks if any. You can push the progress so far in a dedicated branch with a pull request marked as Draft. This will help other people from the community to join the effort.

We can also split the effort in smaller tasks which can be completed within a day or two.

**Comment by ani-kalpachka** [comment]
The current progress is pushed here: https://github.com/daritelska-platforma/frontend/pull/155

**Comment by swolf86** [comment]
Home page improvement comments in the PDF 
[Comments Info site.pdf](https://github.com/daritelska-platforma/frontend/files/6318536/Comments.Info.site.pdf)
Infographics - removed white background behind the icons please update 
New files uploaded here https://www.figma.com/file/IGERJuRUhZohuxq5b3O73w/Podkrepi.bg-Wireframes?node-id=50%3A0

**Comment by ani-kalpachka** [comment]
"Mission, vission, goals" section is implemented.
The issue on "Support Us" section on mobile is fixed.
The changes are merged: https://github.com/daritelska-platforma/frontend/pull/190

**Comment by kachar** [comment]
@swolf86 Is there anything else left to be done in this card ? If not let's close it

**Comment by swolf86** [comment]
![header ](https://user-images.githubusercontent.com/75036745/123699823-9811f480-d857-11eb-9df6-081136add2b5.png)

I think it would be nice if: 
1 Header button is rounded edges, same as the yellow call to action button on the main image 
2 Header text colour should be the  darker blue #284e84 - this will enhance readability and also accessibility
Thanks,

**Comment by ani-kalpachka** [comment]
Closing this issue since the requirements are completed.
