### ISSUE TITLE
[Bug] Donation and total amount texts arrangement is different for BG and EN languages in Donation page

### ISSUE THREAD

**Issue by DanielTakev** [podkrepi-bg/frontend#1244]
### Describe the Bug

Donation and total amount texts arrangement is different when switch from BG to EN in Donation page. 
Maybe the problem is in file FirstStep.tsx, component "Trans".

### To Reproduce

1. Open any campaign and navigate to Donation page. 
2. Click "Donate" button
3. Choose "Other amount" for donation and fill 100 BGN
4. Check the text below. 

**Actual result:**
In BG: 
- За вашия превод от 101,72 лв., таксата на Stripe ще е 1,72 лв., а кампанията ще получи 100,00 лв.

In EN: 
- For your donation of BGN 100.00, the fee from Stripe will be BGN 1.72, and the total charged amount will be BGN 101.72

### Expected Behavior

The text arrangement should remain the same. 

In BG: 
- За вашето дарение от 100,00 лв., таксата на Stripe ще е 1,72 лв., а общият превод ще възлиза на 101,72 лв.

In EN: 
- For your donation of BGN 100.00, the fee from Stripe will be BGN 1.72, and the total charged amount will be BGN 101.72

### Which browser are you using? (if relevant)

Chrome v.105.0.5195.102

**Comment by pshumareva** [comment]
Could you assign me to this bug?

**Comment by pshumareva** [comment]
Hey guys, I've been having issues logging in locally because of the keycloak and its been quite a while I've been having this issue and the bug not getting fixed. After all attempts I guess its best if someone else can have a look at this bug and Ill tackle something different.
