### ISSUE TITLE
Create robots.txt on dev.podkrepi.bg to block traffic and avoid duplicate content

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#1246]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

SEO & Metadata

### Describe the Bug

Google indexes our dev subdomain and creates conflicting duplicate content which reduces the main website authority.

https://search.google.com/u/5/search-console/index/validation?resource_id=sc-domain:podkrepi.bg&item_key=CAMYDyAC&hl=en

![image](https://user-images.githubusercontent.com/893608/206904961-5c00e513-375c-43d2-987c-b75b34de2d58.png)

### To Reproduce

Visit https://dev.podkrepi.bg/robots.txt

See:

```
# *
User-agent: *
Allow: /

# Host
Host: https://podkrepi.bg

# Sitemaps
Sitemap: https://podkrepi.bg/sitemap.xml
```

### Expected Behavior

Visit https://dev.podkrepi.bg/robots.txt

See

```
User-agent: *
Disallow: /
```

We can achieve that on kubernetes ingress level

**Comment by yyosifov** [comment]
I have no idea how to do this in K8s, but I encountered how to do it in Next.js with dynamic robots.txt, so I've opened a PR.
