### ISSUE TITLE
[Bug] English version state is not preserved when open the Campaigns page by click Donate button from the header navigation

### ISSUE THREAD

**Issue by DanielTakev** [podkrepi-bg/frontend#1247]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the Bug

- This issue is visible **only** (as far as I see) when trying to open the Campaigns page by clicking `DONATE` button from the **HEADER navigation** into tag `header`. The `HREF` attribute value is **not changed** to `/en/campaigns` when the language is changed. 

- The additional `Donate` button on the body into tag `section` is fine. 

### To Reproduce

1. Open the Home page
2. Change the language from the Header navigation to EN
3. Click `Donate` button from the Header navigation
4. Check the Campaigns page

**Actual result**: The language is BG

### Expected Behavior

The language version is preserved. 

### Which browser are you using? (if relevant)

Chrome 108.0.5359.99

**Comment by Katzarov** [comment]
Can I be assigned to this one ?
