### ISSUE TITLE
Move Accessibility Widget to down right and remove Discord Widget

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1251]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Desktop layout, Mobile layout

### Describe the feature you'd like to request

Currently the accessibility widget shows top right where people expect to have the login/account/profile icon. The recommended place for accessibility is down right as per UserWay website.

### Describe the solution you'd like

Please move the Accessibility image down right and remove the Discord widget.

**Comment by kachar** [comment]
- Discord chat is disabled
- UserWay widget is moved to the bottom right corner

Desktop|Mobile
---|---
![image](https://user-images.githubusercontent.com/893608/207789000-34b44d59-865f-4be2-be2d-3a3f24d35f12.png)|![image](https://user-images.githubusercontent.com/893608/207788959-168d1753-0cb6-4f8e-abdd-8c43ac5bed4f.png)

**Comment by igoychev** [comment]
Do we need to remove also the WidgetBot code in chat.tsx?

**Comment by kachar** [comment]
@igoychev Yep, we need to take it off. I was looking for that but for some reason couldn't find it. Thanks for bringing it up.
