### ISSUE TITLE
[Bug] Login with Google returns user to step 1 again during the donation process.

### ISSUE THREAD

**Issue by kabaivanov** [podkrepi-bg/frontend#1260]
### Which area(s) of Podkrepi.bg are affected?

Donation

### Describe the Bug

When I initiate a donation before being logged:

1. I input the donation amount. (step 1)
2. I login via Google
3. I have to input the donation amount again (step 1)

### To Reproduce

1. Initiate a donation without being logged in
2. Login via Google

### Expected Behavior

When I initiate a donation before being logged in:

1. I input the donation amount. (step 1)
2. I login via Google
3. Step 2

### Which browser are you using? (if relevant)

Safari Version 15.5

**Comment by momchiii** [comment]
I think that this is happening because the google login is refreshing the page. The refresh creates a brand new stepsContext with the initial values. The first thing that comes to my mind is to store the step in localStorage. You can assign the task to me. I'll also try to think of another way to fix this.

**Comment by dimitur2204** [comment]
@momchiii I found some good info on how we can do it without the hassle:
Take a look at this article: https://frankmeszaros.medium.com/use-localstorage-and-formik-to-supercharge-your-form-experience-a175d68e5ecb

The article is kind of a do it yourself approach.
I also found this: https://github.com/kolengri/formik-persist-values, which if it works and is maintained might be a good fix.

That will leave the steps context to handle by ourselves, but that would be a small job if the whole formik state already is saved
