### ISSUE TITLE
Campaign card image responsiveness 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1278]
### Describe the feature you'd like to request

As as donor I would like to see images responsive so I can see it on different devices desktop, tablet, mobile equally good

![Screenshot_2023-01-07-22-11-14-560_com opera browser~2](https://user-images.githubusercontent.com/75036745/211172252-f2872541-5d17-41ed-a749-5af6944215f7.jpg)

### Describe the solution you'd like

Responsive image containers

**Comment by swolf86** [comment]
Image needs to expanded to the full width of the campaign card

**Comment by ani-kalpachka** [comment]
I will close this ticket because we have a new design for the campaign cards where this issue is not present. 
The development is in progress.
