### ISSUE TITLE
Delete campaigns

### ISSUE THREAD

**Issue by marianacat** [podkrepi-bg/frontend#1288]
### Describe the Request

please, the three campaigns to be deleted and
make the table rows 20 per page.

### To Reproduce

![Screenshot 2023-01-16 145236](https://user-images.githubusercontent.com/92619043/212685118-0ff1eb6b-20cc-4e2a-90a9-8e3bfde489f1.png)

**Comment by igoychev** [comment]
fixed with: https://github.com/podkrepi-bg/api/pull/417 and deployed on prod
