### ISSUE TITLE
New Donation Flow - Bank Transfer Content

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1291]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Donations

### Describe the feature you'd like to request

We need the bank transfer information to be present when the user chooses the bank transfer information payment method.
Mobile: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=16046%3A48652&t=isUvNTPmQtgx72VE-0
Desktop:https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=16211%3A49585&t=isUvNTPmQtgx72VE-0

### Describe the solution you'd like

Would be best if we reuse most of the functionality from the current form.

### Describe alternatives you've considered

There is a Stripe SEPA Direct Debit transfers that might be an option to automatically detect such payments. This suggestion is very much "in the air" though. Has to be synced with a lot of people.
https://stripe.com/docs/payments/sepa-debit

**Comment by dimitur2204** [comment]
@swolf86 @Juicebgs @kachar 

On our current flow the creation of the wish when the user clicks "Donate".
My question is specifically regarding bank transfer donations.

Do we want the person to be able to submit a wish? If that is the case than anyone can without having paid (which is also the case in the current flow)

If we do how do we want to do it? Just redirect to the new "Success" page where the user can submit a wish or something else?

**Comment by swolf86** [comment]
I think we can track if they have made the bank transfer or not. Let them see the success page and make a wish? Any concerns about that
