### ISSUE TITLE
Add editable campaign shortname to be used for permalink

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1296]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the feature you'd like to request

Currently if a campaign link is already shared, when editing the title the system will automatically generate a new permalink/slug and the old link will become invalid. In the same time It is normal to need to change the campaign title for more engaging words during progress of campaign.

So we need the permalink to be editable separately from the campaign title. We also can't leave the first generated permalink because with the edits of title it might become different than the title itself.

### The desired solution:
Add a field that allows editing the permalink_slug separately from the title. The field should be named "shortname" and additional "info" text should instruct that this is going to be used for permalink that is not meant to be changed.

Additional requirements:
 - When campaign is created for first time and the permalink is empty, when entering the title the permalink to be created from title. 
 - Subsequent editions of title should not change the short-name automatically
 - Editing the shortname should open "red text" explaining the old link will not be available
 - Editing the shortname should still slugify it and make it url-friendly

### Even better solution with additional complexity:
 - we can support multiple permalinks to a campaign, in the similar way github is preserving the old names of code repositories, so that old links don't break
 - if the shortnames are really short and good - we can use them for friendly Bank Reference identifiers, instead of the currently cryptic GHJP_ZCW4_I58U codes which the system generates currently

**Comment by BogoCvetkov** [comment]
I'm going to take this one!
