### ISSUE TITLE
Update `@react-pdf/renderer` to get the React 18 typings

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1312]
### Describe the feature you'd like to request

In the newest release -> https://github.com/diegomura/react-pdf/releases/tag/%40react-pdf%2Frenderer%403.1.3
the @react-pdf/rendered team fixed an issue we had with typings on the package.

### Describe the solution you'd like

We currently use `declare module @react-pdf/renderer` which ignores all typings so we don't get Typescript errors. With the new release that can go and we can have full type safety again 🥳

**Comment by HosamIntel** [comment]
May I work on this one?

**Comment by dimitur2204** [comment]
> May I work on this one?

@HosamIntel Yes everyone is welcome! 
Take a look at the contributors guide https://github.com/podkrepi-bg/frontend/blob/master/CONTRIBUTING.md and also the updated task distribution guide https://docs.podkrepi.bg/general/architecture/task-distribution - you would have to Google translate it (you can do so, by hitting right click and 'Translate' in most browsers).
