### ISSUE TITLE
Page for sponsors,  donators and media

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1320]
### Describe the feature you'd like to request

![partners](https://user-images.githubusercontent.com/75036745/216762922-4beee747-5717-4155-9e1b-b5365c2defc2.png)

The page should be indicated in header and footer 
There are 3 tabs on the page : 1. Sponsors  2 Donators and Guarantoors 3. Media

Page is in figma and all images can be taken from there 
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=3904%3A13406&t=petGCu14nupYwj5J-1

Interactive prototype - you can click on preview and see interactions
More info on design or functionality - @atomov93 

### Describe the solution you'd like

Please don't publish i the page without approval of Joro and Stanka for the published names ! in Prodcution

**Comment by AnzheloD** [comment]
I'll take this one
