### ISSUE TITLE
PDF certificate - include full donation id

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1333]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Donations

### Describe the Bug

When generating the PDF certificate, for the donation id currently the code takes only the first 2 symbols, which is incorrect. 
See this line of code:
<Text style={styles.subheading}>за дарение № {donation.id.slice(0, 2)}</Text>

This needs to be corrected so that it includes the full uuid, and because it is long the font of subtitle needs to become smaller to preserve the full line.

### To Reproduce

1. Login/Register on dev.podkrepi.bg
2. Donate to any campaign using the 4242 test card
3. Go to MyProfile and in the donations table click on Download Certificate - this will display the certificate

### Expected Behavior

see screenshot
<img width="819" alt="Screenshot 2023-02-09 at 13 36 46" src="https://user-images.githubusercontent.com/7055304/217802576-df46857d-04da-4a6a-b06d-10aaa58ba4ae.png">

**Comment by dimitur2204** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/61479393/218046866-3b7c5704-b829-4c74-b7a2-caa42f3a2333.png">

@igoychev It looks a little ugly. Maybe truncated to 10-15 symbols

**Comment by igoychev** [comment]
> @igoychev It looks a little ugly. Maybe truncated to 10-15 symbols

@dimitur2204 yep, that's the challenge - the id needs to be full and also to display nicely, so the one who takes the ticket should consider a lot smaller font.

**Comment by sashko9807** [comment]
A slightly more complicated idea if I may. Add a field called for example `DonationID` to the Donation model. This field will hold a randomly generated number represented as string with length of 10-15 symbols. 

Create either a JS or SQL function which will generate the random number for `DonationID` field, and then run a [customized migration script](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations#how-to-edit-a-migration-file), which will add value to  `DonationID` for the already existing records.

 As for the current id with the uuid value, it will be left as a surrogate key.

Although repetition of number this large is highly unlikely, you can still add a safeguard which will check if the freshly generated donation id is already in the DB, and generate a new one if that is the case.

**Comment by dimitur2204** [comment]
> A slightly more complicated idea if I may. Add a field called for example `DonationID` to the Donation model. This field will hold a randomly generated number represented as string with length of 10-15 symbols.
> 
> Create either a JS or SQL function which will generate the random number for `DonationID` field, and then run a [customized migration script](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations#how-to-edit-a-migration-file), which will add value to `DonationID` for the already existing records.
> 
> As for the current id with the uuid value, it will be left as a surrogate key.
> 
> Although repetition of number this large is highly unlikely, you can still add a safeguard which will check if the freshly generated donation id is already in the DB, and generate a new one if that is the case.

That is way too much for that in my opinion. I think the point here is just to be able to associate the certificate with the id in a way. The currently existing ID is enough for that.

**Comment by mm-hstefanova** [comment]
I would love to work on this ticket. Can you please assign it to me?
