### ISSUE TITLE
[BUG] Missing photo and caption on photo

### ISSUE THREAD

**Issue by Teodora-Krumova** [podkrepi-bg/frontend#1337]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the Bug

When Работилница ЕЛА campaign is opened, the logo photo is missing and the caption is copied to the main photo. There is also some text left over from another campaign: Фондация ПУЛС.

### To Reproduce

STEPS TO REPRODUCE: 
1.  Open https://dev.podkrepi.bg/
2. Go to campaign Работилница ЕЛА and open it

Actual result:
Campaign photo is missing, text is copied over the main photo, and there is leftover text from another campaign: Фондация ПУЛС.
![Screenshot 2023-02-10 at 0 27 34](https://user-images.githubusercontent.com/124900925/218196444-cd66482f-f77f-4aad-ba2c-1b9ff01cdbb8.jpg)
![Screenshot 2023-02-10 at 0 27 44](https://user-images.githubusercontent.com/124900925/218196457-cc2db2b8-34e6-4657-9412-621c8999f9bd.jpg)

### Expected Behavior

The campaign has a main photo, logo and headline

### Which browser are you using? (if relevant)

MacOS Monterey Version 12.4
Browser Google Chrome Version 109.0.5414.119

**Comment by ani-kalpachka** [comment]
- According to the new design of Campaign details page the avatar is removed. The name of the beneficiary (in this case 'Фондация ПУЛС') is removed too. 
https://github.com/podkrepi-bg/frontend/issues/1302

- The missing organizer's avatar on local environment has to be investigated.

**Comment by sashko9807** [comment]
> * The missing organizer's avatar on local environment has to be investigated.

The currently used default [image](https://github.com/podkrepi-bg/frontend/blob/master/src/common/util/campaignImageUrls.ts#L50)  was removed in [fb1bf05](https://github.com/podkrepi-bg/frontend/commit/fb1bf0558fb325c8eae3c286abd3e6518cbd6589)

**Comment by ani-kalpachka** [comment]
@sashko9807 Thanks! 
Fix provided here:
https://github.com/podkrepi-bg/frontend/pull/1338
