### ISSUE TITLE
[BUG] Spelling mistake in the picture of section "Как работи Подкрепи.бг?"

### ISSUE THREAD

**Issue by Teodora-Krumova** [podkrepi-bg/frontend#1342]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Images

### Describe the Bug

There is a spelling mistake in the picture.

### To Reproduce

STEPS:
1. Go to https://dev.podkrepi.bg/
2. Scroll down 
3. See section picture  "Как работи Подкрепи.бг?" and text: "Нуждаете се от стредства за лечение"
![Screenshot 2023-02-13 at 23 51 46](https://user-images.githubusercontent.com/124900925/218585792-f1a5d987-4b27-4be3-b80c-5085a672685c.jpg)

### Expected Behavior

The right text must be: "Нуждаете се от средства за лечение"

### Which browser are you using? (if relevant)

MacOS Monterey Version 12.4     Browser: Google Chrome Version 110.0.5481.77

**Comment by marianacat** [comment]
![BG web](https://user-images.githubusercontent.com/92619043/218707072-0e2ee45f-37e3-4356-9ae8-6a3fa649d1ca.png)
