### ISSUE TITLE
[Campaigns] Simple news on campaign page

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1352]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the feature you'd like to request

Currently when there are news for the campaign there is no place to show them.

### Describe the solution you'd like

The need is for a simple news section on a separate tab on the CampaignDetails Page. The news will be written in RichTextEditor in same way as the campaign description in a freestyle text one after another.

### Describe alternatives you've considered

This is intermediate feature, until a full-fledged blog-like campaign news functionality is implemented.

**Comment by swolf86** [comment]
![image](https://user-images.githubusercontent.com/75036745/236704226-55b54819-2bc6-4d17-9c39-285e35caee4f.png)
We ( design) worked on this option. At the moment we are working on the pages after you click see more
