### ISSUE TITLE
[BUG] Difference in Stripe's fee when user wants/doesn't want to cover the fee

### ISSUE THREAD

**Issue by sashko9807** [podkrepi-bg/frontend#1358]
### Describe the Bug

There is a slight difference in Stripe's fee between the following usecases:
-User wants to cover the fee
-User doesn't want to cover the fee.

### To Reproduce

1. Select a campaign to donate to.
2. Choose the amount you want to donate
3. Click on "I want to cover transaction fees for card issued in" checkbox
4. Observe the difference in Stripe's fee

### Expected Behavior

Stripe's fee to remain the same, regardless of whether user wants to cover the fee or not.

**Comment by igoychev** [comment]
The difference of the fee is actually expected because it is calculated on different base amount.
