### ISSUE TITLE
Financial Expenses - Organizer Expenses Form

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1362]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Administration

### Describe the feature you'd like to request

We need a form for the organizers to be create an expense which has the following schema:
* Type* - hardcoded type of the expense synced with the financial team with an option for "Others" for non-standard types
* Date* - date of the expense
* Amount* - amount of the expense
* Currency* - currency of the expense
* Description - description of what that expense consists of
* Files* - `.pdf`, `.jpg`, `.png` files (should we allow other types?) which can be uploaded as proof of the expense (maybe we should have 1 of them be mandatory)

### Describe the solution you'd like

Create a form on a new page which allows creation, deletion, edit of the expense explained in the first section.

There needs to be a way to indicate whether the expense has been Declined and you are resubmitting, or you are submitting for the first time. Maybe the button for submit should change text based on the action you are doing:
Create - Send for approval
Edit - Send revision

**Comment by dimitur2204** [comment]
Current form: 
![image](https://user-images.githubusercontent.com/61479393/220189947-30a01ee1-5cc9-4517-8157-ed40c33a3270.png)

**Comment by slavcho** [comment]
I believe we can close this now.
