### ISSUE TITLE
Financial Expenses - Organizers/Admin Data Table 

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1363]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Administration

### Describe the feature you'd like to request

Organizers should be able to view the current state of the expenses (approved or declined) in their panel/page in order to be able to take action.

Admins should have a similar view, with the option to Apporove / Decline currently active requests

### Describe the solution you'd like

A good solution would be a `DataTable` with fields as is the current implementation with one field extra for the admins to be able to approve and decline. On every action we should have a `ConfirmationDialog` to prevent the user from missclicking.

For the list of files we can have a button that has a dropdown list of the uploaded files that you can download on click. (some way to preview might be a good idea in the future)

Example:
![image](https://user-images.githubusercontent.com/61479393/220187307-26145305-6cc9-46c8-9bca-b093b654131f.png)

**Comment by slavcho** [comment]
This is done imo. I think we can close it.
