### ISSUE TITLE
Financial Expenses - View expenses on the Campaign Details page

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1364]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the feature you'd like to request

Normal users should be able to view campaign expenses that are approved by admins on the page. 

### Describe the solution you'd like

There should be a list of expenses categorized based on the type of the expense, with a way to download the files that are attached and view the description of the expense (design to be added)

We can have a nice pie chart (design to be added) showing how much of the expenses went for what and how much is still unspent.

**Comment by slavcho** [comment]
The pie chart is pending.

**Comment by igoychev** [comment]
> The pie chart is pending.

@slavcho could we close this one as the main functionality is implemented? We can create a separate ticket for the pie chart or actually a simple progress bar that won't take much space and will deliver the same info :)

**Comment by slavcho** [comment]
Sure - we can close it.

**Comment by slavcho** [comment]
Closing this as done. 
The pie chart is not an urgent issue as of now.
