### ISSUE TITLE
Clickable Partners' logos

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1367]
Go to https://podkrepi.bg/partners.
Observe the partners' logos - they are static images.
A partner's logo should be a link that leads the user to the partner's website.

**Comment by dzhaniivanov** [comment]
hello,
where can i find the all partner's websites ? :)
for 88  i don't found anything and for rinkoff only this linked profile- https://www.linkedin.com/company/rinkoff/about/
