### ISSUE TITLE
[Bug] We need to update the year in a footer in BG/EN

### ISSUE THREAD

**Issue by Melnida** [podkrepi-bg/frontend#1378]
### Describe the Bug

The year in the footer needs to be updated.

Currently, in both footers in BG/EN version, the text in the footer exists information for a previous year.
BG: Podkrepi.bg ©2022 Всички права запазени.
EN: Podkrepi.bg ©2022 All rights reserved.

I give you an element that we need to change: 
<div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 css-13t0m53">Podkrepi.bg ©2022 All rights reserved.</div>
and a XPATH  //*[@id="__next"]/div/footer/div/div[3]  

### To Reproduce

1. Go to www.podkrepi.bg
2. Scroll down and see text in the footer 

### Expected Behavior

Please change only the year - 2022 to become 2023.
BG:
Podkrepi.bg ©2023 Всички права запазени.
EN:
Podkrepi.bg ©2023 All rights reserved.

### Which browser are you using? (if relevant)

Chrome 110.0.5481.177

**Comment by Melnida** [comment]
Thank you for the fast reaction. The year is correct in BG and EN.

**Comment by Melnida** [comment]
![image](https://user-images.githubusercontent.com/46921089/224073898-35301bae-1e6e-4adc-b449-c73761019da2.png)

The year is again old. Please check.

**Comment by Melnida** [comment]
> ![image](https://user-images.githubusercontent.com/46921089/224073898-35301bae-1e6e-4adc-b449-c73761019da2.png)
> 
> The year is again old. Please check.

![image](https://user-images.githubusercontent.com/46921089/224078943-afa10647-af36-4093-bfbf-15a9d6e3c7b7.png)

**Comment by Melnida** [comment]
Please reopen it.

**Comment by sashko9807** [comment]
@Melnida it takes time before merged changes are applied directly to [podkrepi.bg](https://podkrepi.bg/). Check if the issue persist in [dev.podkrepi.bg](https://dev.podkrepi.bg).

**Comment by kachar** [comment]
Let's reopen until the fix reaches production.

**Comment by ani-kalpachka** [comment]
The changes are now replicated on production.
