### ISSUE TITLE
[Bug] Missing finance reports in an English

### ISSUE THREAD

**Issue by Melnida** [podkrepi-bg/frontend#1379]
### Describe the Bug

The error page is loaded if the user tries to open the reports in English. 

### To Reproduce

Steps to reproduce:

1. Open https://podkrepi.bg/ and choose EN or open directly https://podkrepi.bg/en
2. Click on About us
3. Select Reports
4. On the page https://podkrepi.bg/en/finance-report try to download one of the reports:
https://podkrepi.bg/en/finance-reports/Podkrepi.bg_Financial_Report_2021.pdf
https://podkrepi.bg/en/finance-reports/Podkrepi.bg_Financial_Report_062022.pdf

Currently, the user sees 404 - "Sorry, you landed on a non-existent page" ...

### Expected Behavior

If the user tries to reach reports in EN to can see them.  The report for the year is shown in EN, as in BG. 
It is better to show the Bulgarian one if we don't plan to translate this in English 

### Which browser are you using? (if relevant)

Chrome 110.0.5481.177

**Comment by dzhaniivanov** [comment]
i will try to fix this

**Comment by Melnida** [comment]
Guys, we duplicate this issue https://github.com/podkrepi-bg/frontend/issues/1384 because again is closed before it be fixed in production. 
**Please only close it after the changes are delivered.**
