### ISSUE TITLE
[Feature] Option to filtering/sorting only active/open campaign 

### ISSUE THREAD

**Issue by Melnida** [podkrepi-bg/frontend#1380]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the feature you'd like to request

When the user tries to review, all active campaigns will be good to have the option to see only Open/Active once. 

We need a new menu/ filter in the Open/Active Campaigns:
![image](https://user-images.githubusercontent.com/46921089/223670534-cec26d82-34f7-4eca-8b08-0ffd98d4dc35.png)

This filter is good to be used also when the user press Donate button. Currently, the user also saw a closed campaign and needs several clicks to find an active one.

Let's try to make it easy and fast and improve the user experience by giving a sorted list. In the future, the list of campaigns will be bigger, and filtering will be necessary. 

### Describe the solution you'd like

Use the same code as in All campaigns but show only Active once. 
Create a new menu - Active campaigns in the Campaign menu.
Change the link in Donate for a new one showing only open campaigns.

### Describe alternatives you've considered

We can also make a list with active campaigns and titles in one place to easily share and donate with max 3 clicks.

Improve searching in campaigns:
Use the same code as in All campaigns but show only Active once. 
Create a new menu - Active campaigns in the Campaign menu.

Improve donation process:
Create a new page listing all active campaigns with the button Donate for each.
![image](https://user-images.githubusercontent.com/46921089/223676780-d26c22d5-fcbe-48f5-9e28-0197093e0b31.png)

**Comment by ani-kalpachka** [comment]
Is this feature planned? If we implement it we are going to need a new page for the active campaigns and another one for all campaigns.
According to the new Homepage design we need to extract Active campaigns and Completed campaigns in separate sections: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=16874%3A51853&t=AnZm1CzPnmWRo77R-0
I personally think that the new design is the ultimate solution and copes with all this issues. 
More opinions would be helpful.

**Comment by ani-kalpachka** [comment]
Closing this issue because it seems not to be planned and conflicts with the new Homepage design. Please reopen if needed.
