### ISSUE TITLE
[Bug] Impossible to use a strong password suggestion from Google Chrome 

### ISSUE THREAD

**Issue by Melnida** [podkrepi-bg/frontend#1385]
### Describe the Bug

Users can't use a recommended strong password from Google Chrome.

The message from the site is: "Password should include at least 1 uppercase, 1 digit and 1 special character"

### To Reproduce

1. Go to http://www.podkrepi.bg/
2. Click on the PersonIcon
3. Select Signup from the dropdown
4. Add some correct data in name, surname, and email fields
5. After you click to add data in the password field, select the option Suggest strong password...
6. Press on Use a strong password 

You can try with: 6c6jrrLj8FgL9Qd and jD74pkkiCGs2AKx
Both are 15 symbols including uppercase, digit.

![image](https://user-images.githubusercontent.com/46921089/224774463-b18e5b18-201f-4758-8374-4acb2724365c.png)

### Expected Behavior

Succesfully use 15 symbols suggested by Google Chrome. 
Option signing is possible without errors. 

### Which browser are you using? (if relevant)

Chrome 110.0.5481.177

**Comment by sashko9807** [comment]
I don't think this is a bug. The google generated password doesn't contain any special characters(! @ # $ % ^ etc...), thus this is the expected behavior.

**Comment by Melnida** [comment]
You're right. I will close it because of missing at least one special character.
