### ISSUE TITLE
[New Feature] Apply for a new campaign to be created

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1388]
As a organizer of campaign I want to be able to easily apply for a new campaign online on the portal, so that I can follow the progress of application save my progress and see preview of the campign before it goes live. 

The flow includes organisation or ndividual login, / sign up, information filling, documents upload and preview

More info @lianazafeiri 
Interaction are shown on differen screens 

![01 Create Campain Organisation](https://user-images.githubusercontent.com/75036745/225384282-aa40cd0f-d58b-4f7d-ae09-1a4cadc1289d.png)
![01 Create Campain_Default](https://user-images.githubusercontent.com/75036745/225384328-27e25424-ae7c-4f4c-b4ba-e9cd9554dea8.png)
![01 Create Campain_Persona](https://user-images.githubusercontent.com/75036745/225384376-7a6247b6-45e3-45a0-9950-4e1254908f1a.png)
![02 Campain info](https://user-images.githubusercontent.com/75036745/225384426-ce1cd0e4-6022-48d6-8e22-b1914436a6f5.png)
![03 1 ФЛ](https://user-images.githubusercontent.com/75036745/225384467-999e4247-6bf6-4e48-bc4b-35520bfd9262.png)
![03 2 ЮЛНЦ](https://user-images.githubusercontent.com/75036745/225384482-e15dbe17-296b-4d26-8492-d05ded09000e.png)
![04 1  Login screen](https://user-images.githubusercontent.com/75036745/225384516-a6bb5a19-9148-4a98-ac4c-405fb147877a.png)
![04 Sign up screen](https://user-images.githubusercontent.com/75036745/225384542-565462c6-719c-457e-888e-5d740f878ba5.png)
![05 Campain info 2 part](https://user-images.githubusercontent.com/75036745/225384554-c2ccfbbb-b059-4d89-bd36-b3abe9910026.png)
![06 Photos and docs](https://user-images.githubusercontent.com/75036745/225384569-73270805-e407-4756-9eb9-459eb2d688d8.png)
![07 Preview](https://user-images.githubusercontent.com/75036745/225384604-67eed905-8842-4327-b6ee-6680578e5a71.png)
![08 Success](https://user-images.githubusercontent.com/75036745/225384637-0414783a-7e63-4e5b-9340-237261f9f2e5.png)

**Comment by AndreyGoranov** [comment]
I would like to work on this ticket

**Comment by lianazafeiri** [comment]
@AndreyGoranov I haven't added description of interactions, but we can work it step by step. Whatever you need, just contact me.

**Comment by AndreyGoranov** [comment]
@lianazafeiri  Sure, thanks!

**Comment by mm-hstefanova** [comment]
I want to continue working on this ticket (:

**Comment by lianazafeiri** [comment]
@mm-hstefanova if need some additional info regarding design, pls don't hesitate to reach me.

**Comment by mm-hstefanova** [comment]
@lianazafeiri @swolf86 
There is a decision about the fonts in this issue #1403.  Can you please confirm that I need to switch from 'Lato' to 'Raleway' for the Steps section? 
![image](https://user-images.githubusercontent.com/91142791/234001541-0528139a-d466-4a32-a8ac-f021bdabae3b.png)

Thanks!

**Comment by swolf86** [comment]
'Raleway' for all secondary fonts like  paragraphs, caption etc

**Comment by swolf86** [comment]
@mm-hstefanova 
Raleway look weird please use Lato for now

**Comment by swolf86** [comment]
![image](https://user-images.githubusercontent.com/75036745/234419306-161e2cca-8696-4762-aff8-f91dde30e89f.png)

**Comment by slavcho** [comment]
https://docs.google.com/forms/d/1qHCnuR-1Fe44ZZ7hlbIkGtjoVd6j6LiAXfSw-ugO1ZM/viewform?edit_requested=true#response=ACYDBNiiizeOU37Jq0XDMYAHEvARvp7xrJBQ-L3pewVdRyfwx1CIofM5au9Sa7j4njvs36c

This is the form that the team uses right now.

**Comment by slavcho** [comment]
And this is the figma that was previously created:

https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=7690%3A23718

**Comment by slavcho** [comment]
Some work on this has been done here in this branch: campaign-form-beneficiary-coordinator

**Comment by slavcho** [comment]
One very important feature on this campaign proposal document is the ability to be approved and to have a log of all the actions that have happened.

**Comment by slavcho** [comment]
[Campaign_Approval_DRAFT_v2_08_14_2023(2).xlsx](https://github.com/podkrepi-bg/frontend/files/15399661/Campaign_Approval_DRAFT_v2_08_14_2023.2.xlsx)

This document is a starting point of the workflow of the campaign.

**Comment by slavcho** [comment]
Yet another file that is currently used by the team:

https://docs.google.com/spreadsheets/d/1G2FB718Ra_6QbOjNPtwU-iq8_OZwfGY7bQGYOI8wpBc/edit#gid=0

**Comment by Juicebgs** [comment]
@swolf86 let's close this issue since it contains some old information, important information is cited in the comments and is not easy to understand the real requirement. I will open a new epic with latest information for easier planning.

**Comment by swolf86** [comment]
@Juicebgs we can close it and open the new one. Still an online form of application will be so much better than a form sent on an email from campaign team

**Comment by ani-kalpachka** [comment]
I will close this ticket having in mind the discussion above.

**Comment by Juicebgs** [comment]
A new issue has been added https://github.com/podkrepi-bg/frontend/issues/1842
