### ISSUE TITLE
All paragraph secondary fonts to be changed from now on to commissioner

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1403]
### Describe the feature you'd like to request

Please change all secondary / paragraph fonts to Commissioner
![image](https://github.com/podkrepi-bg/frontend/assets/75036745/774b7fc5-dd2a-4e88-ab2d-d5496ebf3324)

### Describe the solution you'd like

Let all paragraph and secondary text be raleway 16pt

**Comment by mm-hstefanova** [comment]
I've noticed that on this issue - #1354 there is a similar discussion about the secondary font. So, my suggestion is to put all requirements for the fonts in one place. It will be easier for us to develop, test, and track the updates. 

If I have understood correctly, we need the following:

- 'Monserrat' for all titles 
- 'Raleway' for the body text and the body of the campaigns

is that correct?

**Comment by swolf86** [comment]
> I've noticed that on this issue - #1354 there is a similar discussion about the secondary font. So, my suggestion is to put all requirements for the fonts in one place. It will be easier for us to develop, test, and track the updates.
> 
> If I have understood correctly, we need the following:
> 
> * 'Monserrat' for all titles
> * 'Raleway' for the body text and the body of the campaigns
> 
> is that correct?

Yes correct. Sounds good 
Heading1, H2, H3, H4, H5 Montserrat
Paragraph 1/Body 1, body 2, superscript  H6 - Raleway

**Comment by swolf86** [comment]
Raleway is on hold as the numbers look weird

**Comment by swolf86** [comment]
So selected secondary fort is google fong called commissioner
