### ISSUE TITLE
New Donation Flow - Thank you animation

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1408]
### Describe the feature you'd like to request

Add the new "Thank you animation" created by Yanina Yurukova after a successful donation.

### Describe the solution you'd like

We should preferably render a high quality GIF, if the smoothness of the GIF is not sufficient and the animation looks ugly, we opt to use a compressed MP4. 

We should however keep in mind the size on mobile and the bandwith that it would take for such an animation to be downloaded.

https://user-images.githubusercontent.com/61479393/232036280-8229fcd9-ee2e-4954-8b9a-117bcb01b11f.mp4

**Comment by igoychev** [comment]
We should be able to make a lot better video. Closing for now, until an animated gif is provided.
