### ISSUE TITLE
Long descriptions are not visible in the expenses list on campaign page

### ISSUE THREAD

**Issue by slavcho** [podkrepi-bg/frontend#1420]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the Bug

If the descriptions is too long - it cannot be easily read in the expenses list on the campaign page.

![image](https://user-images.githubusercontent.com/99622/235167054-8bd742fe-29aa-4699-91db-1b4b91b6afe7.png)

### To Reproduce

You will need some expenses in order to be able to test it.
Best use an admin login.

### Expected Behavior

May be we can add a mui popover when rendering the cell.
It would be best to extract this as a separate component.

**Comment by dzhaniivanov** [comment]
![Screenshot 2023-05-01 200054](https://user-images.githubusercontent.com/68897146/235493332-551fa9cc-f73b-42de-8fbe-b628a00d7f33.png)
is this the column you mean ?
