### ISSUE TITLE
Show progress and interesting wishes on the top of the campaign page

### ISSUE THREAD

**Issue by slavcho** [podkrepi-bg/frontend#1426]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

The campaign page.

### Describe the feature you'd like to request

Sometimes we have some cool donation wishes.
We can use the top right hand side of the campaign page to show them.
It would make things more encouraging for the other donors.

### Describe the solution you'd like

We can put some of the latest donation wishes below this box.
Probably even one would be enough if it is randomly selected from the last 10.
I suggest to choose messages that have at least 5 words. 

![image](https://user-images.githubusercontent.com/99622/236290134-b184e1b8-020d-4064-a1b8-463b453045c3.png)

If there are no such choose something from the last 24 hours.
If there are no such then don't show it at all.

**Comment by swolf86** [comment]
On the latest design of the payment card I have added a tab switching between wishes and latest donations 

I think we need to define the rules of wishes - who is going to select them ? 
![image](https://user-images.githubusercontent.com/75036745/236704146-2f9ddb08-2c2f-4518-8c06-59eb9e29eb0a.png)

**Comment by slavcho** [comment]
This looks much better.
Is it possible to add a bubble at the bottom with one random (long) wish?

**Comment by slavcho** [comment]
Closing this as duplicate of: #1426

**Comment by swolf86** [comment]
![Property 1=Variant2](https://github.com/podkrepi-bg/frontend/assets/75036745/d72e6e8a-e04e-44e5-b703-466642a36b73)

**Comment by slavcho** [comment]
I am reopening this as the #1220 is already closed, but we have new design ideas from the design team:

![image](https://github.com/podkrepi-bg/frontend/assets/99622/3c9d6036-bbc6-4dcf-aeb9-a883f6007533)

![image](https://github.com/podkrepi-bg/frontend/assets/99622/bef1b9d9-82ce-4a34-b5cc-75d2317da648)

![image](https://github.com/podkrepi-bg/frontend/assets/99622/2811a3fe-fc93-4e24-a961-4de66d4eb753)

![image](https://github.com/podkrepi-bg/frontend/assets/99622/f3cf4bbd-9eca-45c7-9fba-5e605b10d0cd)

**Comment by kzhecheva** [comment]
I'd like to take this one.

**Comment by ani-kalpachka** [comment]
@kzhecheva The ticket is assigned to you.
