### ISSUE TITLE
User account, created via Google SSO, cannot be deleted

### ISSUE THREAD

**Issue by donangel** [podkrepi-bg/frontend#1434]
### Describe the Bug

When the user tries to delete their account created through Google SSO, they get a password prompt:

<img width="658" alt="image" src="https://github.com/podkrepi-bg/frontend/assets/4919119/6b11e88b-61d6-41f9-a596-e3208b4b70ea">

Since there's no assigned password for the account, they can never delete their profile from the system.

### To Reproduce

1. Go to https://podkrepi.bg/register
2. Choose "Вход с Google"
3. Go to [My Profile](https://podkrepi.bg/profile/donations), [Лична информация](https://podkrepi.bg/profile/personal-information)
4. Click on "[изтриване на акаунт/ профил]"

### Expected Behavior

The user does not get a password prompt, just "Изтрий моя акаунт", maybe with some additional "Are you sure" checkbox to prevent deleting the account by mistake.

**Comment by PetarDimitrov91** [comment]
I will take a look on this ticket.

**Comment by PetarDimitrov91** [comment]
@igoychev after PR #1662 this issue can be closed.

**Comment by igoychev** [comment]
The initial problem is solved in #1662 , however while fixing we discovered that not all personal information is deleted. 
So we need an extension of the fix that enables "The right to be forgotten" which removes all personal information - this will be a new ticket.

**Comment by sashko9807** [comment]
Doesn't seem to be the case anymore.

**Comment by Tuscann** [comment]
https://github.com/podkrepi-bg/frontend/assets/16596102/19923df1-b876-4865-8ca3-05b8bbd7a49d

Please open this bug @sashko9807.

**Comment by sashko9807** [comment]
Opened a new issue instead, as this issue isn't Google SSO specific. 
Link to new issue [api#641](https://github.com/podkrepi-bg/api/issues/641)
