### ISSUE TITLE
[Socket.io]Check connection count

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1454]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Donations

### Describe the Bug

We use socket.io for displaying notification to all users who are currently browsing in podkrepi.bg.

We have a suspicion that the web site is making more than 1 connection to the backend. This is a problem that could create resource leak and we want to make sure it is not the case.

### To Reproduce

Start the backend and open the website on localhost. 
Observe the logs in console and see messages like these:

```
[Nest] 77508  - 06/21/2023, 7:13:09 PM    WARN New Client Connected: vcSBg2PniHRgeVUqAABT
[Nest] 77508  - 06/21/2023, 7:13:09 PM    WARN New Client Connected: GdhT4EXjAVXA2qsrAABV
[Nest] 77508  - 06/21/2023, 7:13:09 PM    WARN New Client Connected: Ny_6dxo0hAUhfWfVAABX
[Nest] 77508  - 06/21/2023, 7:13:09 PM    WARN New Client Connected: fx5Rb3hLfHkKLcJdAABZ
[Nest] 77508  - 06/21/2023, 7:13:09 PM    WARN New Client Connected: gm_Be2jMvGVUzxCpAABb
[Nest] 77508  - 06/21/2023, 7:13:10 PM    WARN OUhyKx7dB48K9aWmAABP disconnected
[Nest] 77508  - 06/21/2023, 7:13:10 PM    WARN Ny_6dxo0hAUhfWfVAABX disconnected
[Nest] 77508  - 06/21/2023, 7:13:10 PM    WARN vcSBg2PniHRgeVUqAABT disconnected
[Nest] 77508  - 06/21/2023, 7:13:10 PM    WARN mT1z4ps2Kc6G39bDAABJ disconnected
[Nest] 77508  - 06/21/2023, 7:13:10 PM    WARN yrdPRFN-DAgRWcJWAABN disconnected
```

### Expected Behavior

Expected behavior is to show only one connect/disconnect when browsing locally with a single user.

**Comment by slavcho** [comment]
Please assign this to me.

**Comment by slavcho** [comment]
I think it is fine.

It creates +2 sockets at the beginning, but after that it is only one connection per web page.
This means if you open 5 tabs, you end up with 7 connections.
But after we close them - we are back to 2.

![image](https://github.com/podkrepi-bg/frontend/assets/99622/f08f2702-a872-4316-9866-21f760ee3852)

**Comment by slavcho** [comment]
> I think it is fine.
> 
> It creates +2 sockets at the beginning, but after that it is only one connection per web page. This means if you open 5 tabs, you end up with 7 connections. But after we close them - we are back to 2.
> 
> ![image](https://user-images.githubusercontent.com/99622/250190409-f08f2702-a872-4316-9866-21f760ee3852.png)

I take this back. There is (was) a problem.
It reproduces if you start clicking multiple pages. 

It is fixed in this PR:  https://github.com/podkrepi-bg/frontend/pull/1460

Kudos to @sashko9807 !
