### ISSUE TITLE
[bank donations] Must use bank account currency

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1462]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Donations

### Describe the Bug

We have received a bank donation in EUR, however the bank account is in BGN, so we need to account the money in BGN only.

### To Reproduce

See the received amount in the Admin UI:
<img width="1020" alt="Screenshot 2023-07-03 at 10 16 37" src="https://github.com/podkrepi-bg/frontend/assets/7055304/2616979f-3bd8-4f17-883b-98f172a0b000">

It is shown correctly, but the calculation of total donated amounts will be wrong as the system will calculate all numbers in the main currency.

### Expected Behavior

After some research it appears the solution needs to be the following implemented on the backend:
The bank is sending the transaction with the below message, where the currency is in EUR and there is no exchange rate. This is obviously a bug in the bank API and we have reported it. 

Until waiting we noticed that the actual converted BGN amount is existing in the long transactionId field. The amount is at the end of the transaction between dates like this: 20230703amount_20230703. So the logic could be: if currency <> BGN take the BGN amount from the transaction id. 

When the bank fixes the message, we will remove this custom logic.

Full bank message here:

```
{
      "transactionId": "Booked_6516347588_70001524349032963FTRO23184809601C202307034024.69_20230703",
      "bookingDate": "2023-07-03",
      "creditorAccount": {
        "iban": "BG66UNCR70001524349032"
      },
      "creditorName": "СДРУЖЕНИЕ ПОДКРЕПИ БГ",
      "debtorAccount": {
        "iban": "BG21UNCR111111111111"
      },
      "debtorName": "Name not relevant for the example",
      "entryReference": null,
      "remittanceInformationUnstructured": "98XF-SZ50-RC8H",
      "transactionAmount": {
        "amount": 2069.25,
        "currency": "EUR"
      },
      "exchangeRate": null,
      "valueDate": "2023-07-03",
      "creditDebitIndicator": "CREDIT",
      "category": null
}
```

**Comment by yyosifov** [comment]
Can I take it, please? @igoychev

**Comment by igoychev** [comment]
fixed on backend: https://github.com/podkrepi-bg/api/pull/537
