### ISSUE TITLE
Loading the donation page executes a request to http://localhost:5010/api/v1/[object Object]

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1496]
### Which area(s) of Podkrepi.bg are affected?

Donations

### Describe the Bug

While on localhost, having started the frontend with 'yarn dev':
After clicking the donation button for any campaign, the donation page is executing request to http://localhost:5010/api/v1/[object Object]

and in the terminal you can see a long error finishing with:
```
data: {
      statusCode: 404,
      message: 'Cannot GET /api/v1/[object%20Object]',
      error: 'Not Found'
    }
```
also on the backend in the terminal window this is logged as:
```
[Nest] 43551  - 07/25/2023, 5:14:07 PM    WARN [HTTP] GET /api/v1/[object%20Object] 404 Not Found
```

The problem has no visible or functional effect on the completion of the donation.

### To Reproduce

same as above

### Expected Behavior

no error in console and no request with invalid url

**Comment by dzhaniivanov** [comment]
can't reproduce this, I tried all donation buttons which saw

**Comment by igoychev** [comment]
Here is a screenshot for how to reproduce on localhost:

<img width="1195" alt="Screenshot 2023-07-25 at 17 14 33" src="https://github.com/podkrepi-bg/frontend/assets/7055304/76357687-8735-4141-9ef4-da5b0962adcc">


also for the error log you need to look at the terminal window where the 'yarn dev' is executed
