### ISSUE TITLE
Automate nightly builds

### ISSUE THREAD

**Issue by miraclebg** [podkrepi-bg/frontend#150]
Find a way to make the process of building nightly builds automatic:

- Automatically tag the deploy/nightly/ tag
- May be automatically merge pending PRs? (to be discussed)

**Comment by igoychev** [comment]
Currently it is happening by this action, but manually: https://github.com/podkrepi-bg/frontend/actions/workflows/deploy-nightly.yml and the target is dev1.podkrepi.bg but the deployment is not live(@miraclebg can help here for access to the host)

**Comment by kachar** [comment]
Let's see if the fix of @nedstrike works tonight

**Comment by kachar** [comment]
The deploy is failing when we run it manually with:

```
Add known hosts
write (78.130.245.130): Connection refused
```

https://github.com/podkrepi-bg/frontend/runs/2823828136?check_suite_focus=true

It seems it's host related

cc @miraclebg

**Comment by kachar** [comment]
Builds are automated by github actions now
