### ISSUE TITLE
Try MDXEditor for our RichTextEdit component

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1503]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the feature you'd like to request

[MDXEditor](https://mdxeditor.dev/) is new editor component that could be used as replacement of Quill which we currently use.
The MDX Editor is in active development by @petyosi with whom we talked recently and we see common interest in cooperation.

### Describe the solution you'd like

The MDXEditor should support these common use-cases:
- [ ] Standard text editing and formating
- [ ] Copy/Paste from Google Docs including Images and embeding them as <img> in the same way Quill does
- [ ] Ability to embed videos from Youtube
- [ ] Extra Feature: an image handler which upon paste to call a server upload function to upload and upon img delete to remove it from server.

**Comment by petyosi** [comment]
Assign to me. 
- Pasting from google docs works.
- Image uploading is now supported when you copy-paste an image from a clipboard or drag it from the file explorer/finder. 
- I am going to work on Youtube support and showcase how it works.
