### ISSUE TITLE
deprecated @next/font library

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1525]
### Describe the Bug

When starting the frontend there is a warning message:
```
warn Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14
```

### To Reproduce

Run 'yarn dev' and the warning will appear

### Expected Behavior

Remove the import of the @next/font in package.json and fix the import where used

**Comment by tongo-angelov** [comment]
I would like to help with this issue
