### ISSUE TITLE
images with legacy property objectFit

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1529]
### Which area(s) of Podkrepi.bg are affected?

Multiple places

### Describe the Bug

It looks migration to NextJS13 was not completely done everywhere.
The following warning message appears in terminal:
```
Image with src "http://localhost:5010/api/v1/campaign-file/6b06bfbd-85fe-4d2f-945e-53f1f9e43f3e" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
```

### To Reproduce

1. run yarn dev
2. load any campain page

### Expected Behavior

remove objectFit as per the upgrade instructions https://nextjs.org/docs/messages/next-image-upgrade-to-13  on all places

**Comment by Nkiriobasi** [comment]
I’ll fix this
