### ISSUE TITLE
[Donations] Add Statistics Dashboard for Donations

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1532]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns, Donations

### Describe the feature you'd like to request

Currently users of Podkrepi.bg can see the donations log, but cannot see an overall impression of how the donations were collected during time, what is the distribution of amounts and who are the biggest donors. Adding this information in a Statistics Dashboard would improve user engagement, will focus the marketing efforts and will increase the transparency of the platform.

### Describe the solution you'd like

Donations Statistics Dashboard should appear as a separate tab on every campaign page and should be visible by all users of the web site. 

#### Performance considerations:
- the data should be loaded only when the tab is visible
- load only the needed data fields from the backend and if needed create /statistics API endpoints
- the backend endpoints serving the data should be cached for at least 30min with a notice on the page saying "The Donations Statistics are intentionally showing cached data delayed to max 30min of your first load."

#### List of charts needed for now:
- [ ] Cumulative Donations Timeline(vertical area) - shows the accumulation of the total amount over time. The impression the chart makes is always growing with flat periods where no donations are made 
- [ ] Donations Amounts Timeline (vertical barchart) - shows the sum of the donated amounts as they came in the selected time interval (daily, weekly, monthly) without addition with the previous interval. If possible on a second Y axis we can show the count of donations too or add it as a separate graph. The chart will show 0 amounts when no donations are made during that interval.
- [ ] Donations Amount Distribution (vertical barchart) - shows the count of donations of the same amount. On X axis are the unique amounts like 10, 20, 50, 100, 1000 etc and on the Y axis is the count of donations of the same amount. The goal of this chart is to show which are the preferred amounts, as well as the min and max amounts donated.
- [ ] Donations During Day Distribution (vertical barchart) - shows how users are donating during the day. On X axis we show only the time of the donation, on Y axis is the count of donations done. Some charts allow grouping in time intervals like 5, 15, 30min or 1h automatically - please enable it for selection

The ticket can be broken in subtickets as each chart brings huge value and it's better to deliver them in iterations.

### Describe alternatives you've considered

A main cross-campaign dashboard can be added too, however that will be a separate effort as it will probably require preprocessing of the huge amount of data and preparing summary reports.

**Comment by igoychev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature 1](https://trello.com/c/1mx5qi66/2-feature-1)

**Comment by tongo-angelov** [comment]
I would like to help
