### ISSUE TITLE
[Notification Subscription] Update UI For The Notifications Functionality

### ISSUE THREAD

**Issue by BogoCvetkov** [podkrepi-bg/frontend#1550]
### Which area(s) of Podkrepi.bg are affected?

Notification Subscription

### Describe the Need

Need to update the current simplistic subscription forms (screenshots here) with the new improved design from Milena's comment: https://github.com/podkrepi-bg/frontend/issues/1550#issuecomment-1756087392

Current(old) design for reference:
 - Non-logged users - General subscribe
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/8e0a36ef-0f8b-4180-8471-f67abe082b02)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/8f581e4f-1fa9-4445-81e6-41a7b53cb84c)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/37431580-4ebf-4ecc-88e5-4752b2a8a60d)

NOTE: No one will go to the footer to subscribe. We should add some pop-up that will show up when a visitor lands on the home page. It should contain an input field for the visitor to subsribe his/her email. So probably there should be a design for that one as well

 - Non-logged users - Campaign subscribe
 
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/db5d1649-263f-4baa-b3e0-2ea07c015a6f)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/75d3d71b-62b8-4842-925c-7a2248e379e7)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/bd5f2606-c6bb-405c-b961-d722c44a43be)

- Confirm Subscribe Email
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/9491b9ed-bd13-4f9d-bfaf-e5f757ab15e6)

- Subscribe/Unsubscribe confirmation flow
![Loader](https://github.com/podkrepi-bg/frontend/assets/78339364/6c8b2e8e-aeb7-4782-bb9e-e4a0f35db385)

 - Subscribe Success / Fail
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/a4325742-d8aa-42a1-be4a-158733dc07de)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/8701cb1b-09b0-481f-a59f-358d0c15023d)

-Unsubscribe Success/Fail
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/4c4c90df-6473-4c09-9964-2f4a26074085)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/6affa7a7-8a72-4e46-8b68-2d44bafacafb)

- Logged User Dashboard Notifications Tab
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/5036f21a-0306-4197-acad-2fb6ae0ce490)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/265b74a2-9695-4027-8b27-f21a1af0a029)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/579b79bd-ea59-4fa6-8267-fe95f5717c87)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/0b9f1f06-5301-481a-9bcc-1d7dc948aeb5)

Logged user campaign modal
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/2152a9b2-0ad1-437e-9d22-e0e710c49534)
![image](https://github.com/podkrepi-bg/frontend/assets/78339364/df355763-1850-4c24-a129-c0900b856580)

### To Reproduce

This is a design ticket

### Expected Behavior

New Design to be applied

### Which browser are you using? (if relevant)

Chrome

**Comment by milenasp** [comment]
Hi Bogo and all, 

Analysis of Hotjar user sessions found that the subscription feature should appear in four places throughout the Homepage:

1. in the existing“Какво постигнахме досега” section (aka Position 1)
2. in the existing "Кой стои зад Подкрепи.бг" section (aka Position 2)
3. in a new section located right under Стани доброволец (aka Subscription Section)
4. in the footer

In points 1 and 2 above, the feature is indicated with an icon (envelope), text explaining the feature, CTA button. Clicking the CTA button opens an overlay, the CTA button behind it is disabled, the envelope icon changes to "opened envelope". The overlay is specific to the user state - logged or unlogged. Logged users are invited to choose whether to receive the newsletter on their profile address or an alternative address. Unlogged users are invited to log in or continue as guest. 

Logged user overlay:

![Subscription_Modal_Logged_User](https://github.com/podkrepi-bg/frontend/assets/6492044/8375769e-f50d-4a5c-b910-be7a48285c26)

Non-Logged user overlays:

![Subscription_Modal_Non-Logged_User_As-Guest](https://github.com/podkrepi-bg/frontend/assets/6492044/801ce5c7-c6ec-4629-bb9a-aff0237a49d2)

![Subscription_Modal_Non-Logged_User](https://github.com/podkrepi-bg/frontend/assets/6492044/3048806b-30d6-42f4-b339-dff429ad2ecf)

Success overlay:

![SignUp_Successful](https://github.com/podkrepi-bg/frontend/assets/6492044/7b0e17f4-ae1a-43da-964f-6c82d3051e5b)

Position 1 screen:
![Subscription_Position1](https://github.com/podkrepi-bg/frontend/assets/6492044/9892e762-c73f-4399-b029-e0959a743995)

![Subscription_Position1_Non-Logged_User_Modal](https://github.com/podkrepi-bg/frontend/assets/6492044/0a6549ea-4338-429f-9a45-b9b60957d025)

Position 2 screen:

![Subscription_Position2](https://github.com/podkrepi-bg/frontend/assets/6492044/f92d63bf-28d7-44c5-97ae-0a598c7108ec)

![Subscription_Position2_Non-Logged-User_Modal](https://github.com/podkrepi-bg/frontend/assets/6492044/31840d64-2542-4d61-b748-1d1f0ef4ffc1)

Subscription Section:

![SubscriptionSection](https://github.com/podkrepi-bg/frontend/assets/6492044/fd9528e0-e82b-490b-aaa2-44236a326af8)

Footer: 

If accessing the feature from the footer, the user is navigated (scroll up) to the Subscription Section. 

![footer_hover](https://github.com/podkrepi-bg/frontend/assets/6492044/bb2b899f-d4c5-46ee-80e6-16bd86efb860)

Emails: 

After signing up for the newsletter, the user receives and email prompting them to confirm their subscription. If the user's email exists, the email informs them about their Личен профил. If the email doesn't exist, the email invites them to register. 

![SubscriptionSection_ConfirmationEmail_Registered User](https://github.com/podkrepi-bg/frontend/assets/6492044/c470a69b-48fc-4b14-b7e8-6dee554f46f4)

![SubscriptionSection_ConfirmationEmail_Non-Registered User](https://github.com/podkrepi-bg/frontend/assets/6492044/9fb50a66-99d2-4cde-8ac2-ede2544c3ca8)

After confirming their subscription, the user gets Success or Failure message on Podkrepi.bg

![Subscription-Confirmation_Successful](https://github.com/podkrepi-bg/frontend/assets/6492044/25556688-e9bb-498c-859d-bfa43fe4c348)

![Subscription-Confirmation_Failed](https://github.com/podkrepi-bg/frontend/assets/6492044/ed0d6124-b124-4f05-8d96-cefe795710e7)

For more details, please check out the design in Figma and please don't hesitate to direct message me in Discord. https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?type=design&node-id=20162%3A16553&mode=design&t=eVRpHE0XknUGJXIq-1 

P.S. will send over the design for Campaign Page asap.
