### ISSUE TITLE
Campaign Financial Report Chart

### ISSUE THREAD

**Issue by yoanamanolova** [podkrepi-bg/frontend#1556]
### Describe the feature you'd like to request

Campaign Financial Report - Pie Chart Pie and Icons assigned to expenses types
Outstanding item from ticket #1348
Position of reports in campaign below gallery in new design
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?type=design&node-id=17103%3A52878&t=yGtnHCQ1lUpijG5R-1
![236704296-00652d76-ed94-4841-93e9-fe8c6513aed4](https://github.com/podkrepi-bg/frontend/assets/125492215/ec13a94b-a6b9-4536-bcb8-6f7b388a331e)

### Describe the solution you'd like

As a donor I want to see a pie chart that breaks down campaign expenses by type with amounts.

**Comment by igoychev** [comment]
When implementing this, it will be a lot more optimal to use Horizontal Stacked Bar Chart that reaches 100%. As seen on the example below, the stacked bar will be on a single line which is a lot more optimal than the pie chart and will have the nice effect of growing from zero to the 100%. 
<img width="447" alt="Screenshot 2023-08-17 at 13 51 02" src="https://github.com/podkrepi-bg/frontend/assets/7055304/7306640e-1be0-4e92-b095-bc81b10a9e2a">

**Comment by tongo-angelov** [comment]
I can take a crack at it
