### ISSUE TITLE
Withdrawal: New field 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#1558]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Administration

### Describe the feature you'd like to request

Currently the system tracks the date a withdrawal is created and edited, but we need an additional date field - the date money has been transferred to the organizer bank account. This will make it easier for us to make cross-checks with the bank account availabilities and also will give us the opportunity to show this information on the frontend. 

### Describe the solution you'd like

Please add a date field called "Date" in the withdrawals edit / add screen in the admin section.

**Comment by igoychev** [comment]
to make this easy for implementers:
there is already a field targetDate which is shown in the Withdrawals Grid - that field should be shown also on the Edit/Add forms as per the requirement above

**Comment by aybeedee** [comment]
I'd like to work on this, can I kindly be assigned?

**Comment by igoychev** [comment]
> I'd like to work on this, can I kindly be assigned?

Sorry, it was already taken by @hiapetrov but not marked as assigned.
