### ISSUE TITLE
forgotten password is missing on login/ payment page 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1560]
### Describe the feature you'd like to request
On the second step of the donation process we ask the user to login, but the forgotten password link is missing on that screen.

![image](https://github.com/podkrepi-bg/frontend/assets/75036745/b75c4bd6-46aa-4d5c-a50d-178ccf411525)

### Describe the solution you'd like
Please add an option to retrieve your forgotten password in the same way it is on the login page.

**Comment by swolf86** [comment]
Agreement with the GDPR/data policy is needed on that screen too 

![image](https://github.com/podkrepi-bg/frontend/assets/75036745/6cfb4fab-bc86-48a9-bf09-5eddd967c333)

**Comment by igoychev** [comment]
> Agreement with the GDPR/data policy is needed on that screen too

Clarifying the above: The GDPR agreement checkboxes, should be the same as on the main Registration page: https://podkrepi.bg/en/register

**Comment by ani-kalpachka** [comment]
Forgotten password is added on the Login form on donation: https://github.com/podkrepi-bg/frontend/pull/1572
