### ISSUE TITLE
Other amount field for donation custom sum 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1561]
### Describe the feature you'd like to request

Please allow users to enter sum in the exact filed which they entered so that they are not confused by adding separate field 

### Describe the solution you'd like

on click  this field
![image](https://github.com/podkrepi-bg/frontend/assets/75036745/b448cb57-ace1-47a6-bebf-012705ded983)
 should transform to active state of the field which they can enter a sum 
 
![image](https://github.com/podkrepi-bg/frontend/assets/75036745/e820f2a0-da9a-4cb6-ad3f-67352a46b945)

**Comment by dphilipov** [comment]
I can work on this :)

**Comment by ani-kalpachka** [comment]
@dphilipov Great! The ticket is assigned to you.
