### ISSUE TITLE
Campaign News sections layout improvement 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1562]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaign News

### Describe the feature you'd like to request

As a donor I would like to see neatly arranged news articles for the campaigns, so that I am aware of what is going with the campaign. 

The campaign news page is here: https://podkrepi.bg/campaigns/news reachable from menu Campaigns/News

### Describe the solution you'd like
Reduce the width of container and center it similarly to how the blog articles look https://podkrepi.bg/blog/priedi-da-napravite-darenie

**Comment by igoychev** [comment]
@swolf86 is the issue about https://podkrepi.bg/campaigns/news or about https://podkrepi.bg/blog ?
