### ISSUE TITLE
Add a refund donation button in the admin panel

### ISSUE THREAD

**Issue by slavcho** [podkrepi-bg/frontend#1585]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Donations, Administration

### Describe the feature you'd like to request

Sometimes we need to return the money from a specific donation.
There could be many reasons for it.
Currently the only way to do this is manually via direct db changes.

### Describe the solution you'd like

We need a "refund" button in the admin panel on the donations list.
The refund should mark the donation as refunded and should remove the money from the campaign's vault.
This should be done in a single transaction.

### Describe alternatives you've considered

It would be best if we have an explicit "right" and this access only to some admins - not all.
But that could be extracted as a different ticket later.

**Comment by igoychev** [comment]
assigned to @Nnachevvv
