### ISSUE TITLE
Sort bank transactions by created date in descending order

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1588]
### Which area(s) of Podkrepi.bg are affected?

Donations

### Describe the Bug

Currently the bank transactions grid is sorted in ascending order. 
https://podkrepi.bg/admin/bank-transactions

### To Reproduce

Check this URL: https://podkrepi.bg/admin/bank-transactions

### Expected Behavior

The grid to be sorted in descending order by transaction date

**Comment by dphilipov** [comment]
Can you assign this to me, please.
