### ISSUE TITLE
CTA on main campaign has shifted on homepage

### ISSUE THREAD

**Issue by MartinaMitz** [podkrepi-bg/frontend#1591]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

The button on the hero-campaign (homepage) has shifted downwards and is too close to the sum-goal. It seems that the button is actually aligned with the other buttons, but the hero-image is a few pixels shorter, which leads to the shift of the information below.
<img width="1239" alt="Screenshot 2023-09-14 at 07 34 59" src="https://github.com/podkrepi-bg/frontend/assets/132821177/7d308fdd-8ab9-4a92-983d-25360c4836e0">

### To Reproduce

Open the homepage on Chorme, 1440x900 resolution

### Expected Behavior

The hero image should be aligned with the lower edge of the other images.

### Which browser are you using? (if relevant)

Chrome Version 114.0.5735.248 (Official Build) (arm64)

**Comment by ani-kalpachka** [comment]
The issue still seems to be present:

![image](https://github.com/podkrepi-bg/frontend/assets/14351733/aa68203c-0a5f-4b73-a9ba-2fe967009f03)

**Comment by sashko9807** [comment]
@ani-kalpachka 
Unable to reproduce
![image](https://github.com/podkrepi-bg/frontend/assets/27433690/2b865acb-484d-4537-9afa-963eaa41dc4b)

**Comment by ani-kalpachka** [comment]
I retested again with the latest changes on master branch and it still looks the same.
The problem might be only on my environment.
Could someone else test the view on this resolution please?

**Comment by igoychev** [comment]
here is how it looks on dev.podkrepi.bg after the merge of the changes:
<img width="1240" alt="Screenshot 2023-09-18 at 09 51 09" src="https://github.com/podkrepi-bg/frontend/assets/7055304/e2831f4a-c9c6-4a68-b1bd-44cbdf66d763">

**Comment by ani-kalpachka** [comment]
Thank you!
There was a problem on my environment.
I will close the ticket.
