### ISSUE TITLE
The images on 'Completed campaigns' section are not responsive

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1594]
### Which area(s) of Podkrepi.bg are affected?

Homepage

### Describe the Bug

The UI for the cards on 'Completed campaigns' carousel seems to be displaced.

- For mobile devices the images are cut: 
![image](https://github.com/podkrepi-bg/frontend/assets/14351733/6aa573f3-8aaf-47bf-a08f-d3a3d5ea6bdd)

- For tablets they are not centered:
![image](https://github.com/podkrepi-bg/frontend/assets/14351733/fb50d561-8541-4062-af72-2e3320f10b27)

### To Reproduce

1. Open the homepage.
2. Scroll down to 'Completed campaigns' section.
3. Switch to responsive view.

### Expected Behavior

The images have to be responsive.

### Which browser are you using? (if relevant)

Tested on Chrome and Firefox

**Comment by sashko9807** [comment]
The images in tablet/mobile view should be fixed in [1592](https://github.com/podkrepi-bg/frontend/pull/1592). 

As for the images being cut, `objectFit` property could be removed, but imho it seems to retain the image quality better in this case.

**Comment by ani-kalpachka** [comment]
I retested again. It it fixed. Thank you @sashko9807!
