### ISSUE TITLE
Language Change Button Translates Page to Incorrect Language

### ISSUE THREAD

**Issue by zeroskurt** [podkrepi-bg/frontend#1602]
### Which area(s) of Podkrepi.bg are affected?

Translations (i18n)

### Describe the Bug

I encountered a bug related to the language change button. When I click the button to change the language from Bulgarian (BG) to English (EN), the page is translated into Bulgarian instead of English. Additionally, when I click the button to change the language from English (EN) to Bulgarian (BG), it translates the page into English rather than Bulgarian.

https://github.com/podkrepi-bg/frontend/assets/145425188/887608ba-d163-48d2-9913-becd417838ad

### To Reproduce

1. Open https://podkrepi.bg/
2.Locate the language change button. "Top Right corner"
3.Click the button to switch from BG to EN or from EN to BG.

### Expected Behavior

When clicking the button to switch from BG to EN, the page should translate into English (EN).
When clicking the button to switch from EN to BG, the page should translate into Bulgarian (BG).

### Which browser are you using? (if relevant)

Version 117.0.5938.89 (Official Build) (64-bit)

**Comment by ani-kalpachka** [comment]
I cannot reproduce a problem related to translation switching. Everything seems to work correct on the recorded video - the button language is changed and the content is translated to the correct language.
The language button does not show the current language, but the language which the user can switch to.
Could you please explain? I may misunderstood the issue.
