### ISSUE TITLE
Incorrect text alignment in "News" sub tab under "Campaigns"

### ISSUE THREAD

**Issue by CVTdnb** [podkrepi-bg/frontend#1604]
### Which area(s) of Podkrepi.bg are affected?

The "news" sub tab under Campaigns

### Describe the Bug

The latest news showing the information in the left of the screen, while older news are centered

### To Reproduce

![image](https://github.com/podkrepi-bg/frontend/assets/145843144/61c4f3d7-79c2-4db1-aa63-1526b9106434)

### Expected Behavior

All of the content need to be centered

### Which browser are you using? (if relevant)

Chrome

**Comment by zahariev** [comment]
max-width: 1200px;
must be set on grid container
