### ISSUE TITLE
[Bug] Body font changes upon hard browser refresh

### ISSUE THREAD

**Issue by miraclebg** [podkrepi-bg/frontend#165]
**Describe the bug**
First time the browser opens the font is shown correctly. As soon as you reload the page (F5) the font changes.

**Environment**

Dev: https://dev1.podkrepi.bg

**To Reproduce**
See the attached video.

To reproduce press F5 / reload.

**Expected behavior**
Font should stay as it is iinitally.

**Screenshots**
See the attached video.

**Desktop (please complete the following information):**

- OS: Mac OSX 11.2.3 (20D91)
- Browser: Safari Techn. Preview (Release 123 (Safari 14.2, WebKit 16612.1.7.10))

https://user-images.githubusercontent.com/126405/114164176-a8d75c00-9933-11eb-86f6-f8af6d5de6bc.mov

**Comment by Garchev** [comment]
It seems to be connected with "bg.json" file, which is fetched after click on the logo, but not after refresh. 
I hope this helps fixing the problem.

**Comment by spazbg** [comment]
I can confirm this issue. When the page load and user click on Home button, the font of the navigation bar was changed. 

You can spot the change from this:
![image](https://user-images.githubusercontent.com/22222777/120885217-6e670400-c5f0-11eb-8e7a-8ce0ce2b27b9.png)

to this:
![image](https://user-images.githubusercontent.com/22222777/120885232-85a5f180-c5f0-11eb-9b2f-2bb4898d0903.png)

if you take a look at the latter "Д"

**Comment by kachar** [comment]
@spazbg The core problem seems to be with the actual cyrillic version of the font `Montserrat` 

The english version of this font works okay without any changes in shape.

The best thing we can do is to use it from local source or ... change the font

**Comment by dimitur2204** [comment]
Is this issue still relevant?

**Comment by igoychev** [comment]
looks not happening anymore, please report it again with the latest version if happening again

**Comment by kachar** [comment]
@igoychev Thanks for closing the issue, it was resolved by switching to NextAuth for the authentication layer
