### ISSUE TITLE
What did we achieve text change 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#1724]
### Describe the feature you'd like to request

Please change the text:
 ̶ ̶П̶р̶и̶ ̶д̶а̶р̶е̶н̶и̶е̶ ̶с̶ ̶к̶а̶р̶т̶а̶ ̶и̶з̶п̶о̶л̶з̶в̶а̶м̶е̶ ̶у̶с̶л̶у̶г̶и̶т̶е̶ ̶н̶а̶ ̶S̶t̶r̶i̶p̶e̶,̶ ̶к̶а̶т̶о̶ ̶з̶а̶ ̶в̶с̶е̶к̶и̶ ̶т̶р̶а̶н̶с̶ф̶е̶р̶ ̶S̶t̶r̶i̶p̶e̶ ̶н̶а̶ч̶и̶с̶л̶я̶в̶а̶т̶ ̶т̶а̶к̶с̶а̶ ̶с̶п̶о̶р̶е̶д̶ ̶р̶е̶г̶и̶о̶н̶а̶ ̶н̶а̶ ̶к̶а̶р̶т̶о̶и̶з̶д̶а̶т̶е̶л̶я̶ ̶в̶и̶.̶ ̶З̶а̶ ̶д̶а̶ ̶с̶е̶ ̶о̶р̶и̶е̶н̶т̶и̶р̶а̶т̶е̶ ̶з̶а̶ ̶н̶е̶т̶н̶о̶т̶о̶ ̶д̶а̶р̶е̶н̶и̶е̶,̶ ̶с̶л̶е̶д̶ ̶к̶а̶т̶о̶ ̶и̶з̶б̶е̶р̶е̶т̶е̶ ̶ж̶е̶л̶а̶н̶а̶т̶а̶ ̶с̶у̶м̶а̶,̶ ̶щ̶е̶ ̶в̶и̶ ̶п̶о̶к̶а̶ж̶е̶м̶ ̶и̶з̶ч̶и̶с̶л̶е̶н̶а̶т̶а̶ ̶т̶а̶к̶с̶а̶.̶ ̶П̶о̶в̶е̶ч̶е̶ ̶з̶а̶ ̶т̶а̶к̶с̶и̶т̶е̶ ̶о̶т̶ ̶С̶т̶р̶а̶й̶п̶ ̶в̶и̶ж̶т̶е̶ ̶т̶у̶к̶:̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶s̶t̶r̶i̶p̶e̶.̶c̶o̶m̶/̶e̶n̶-̶b̶g̶/̶p̶r̶i̶c̶i̶n̶g̶

to: 
Даренията, платени с карта се обработват през системата на Stripe и за всеки трансфер Stripe удържат такса. Моля, изберете сумата, която желаете да преведете и по-надолу ще видите изчислена конкретната такса:

За вашия превод от 10,00 лв., Stripe ще удържи 0,62 лв. и по кампанията като дарение ще се отразят 9,38 лв. Повече за таксите на Stripe вижте тук: 

Искам да покрия банкова такса за карта издадена в  регион ( Европа ) .

За вашия превод от ХХ.ХХ лв. Страип  удържа Х.ХХ лв. Маркирайки полето по-горе, бенефициента ще получи точно 10.00лв. 
Страйп такси  (подчертан линк в синьо- https://stripe.com/en-bg/pricing )

**Месечно дарение**
Желая да дарявам същата сума всеки месец до края на кампанията
Може да се откажете по всяко време в профила си (линк към https://podkrepi.bg/profile/recurring-donations).“

### Describe the solution you'd like

as above

**Comment by dzhaniivanov** [comment]
you want to move the dropdown after the strong with fees? Do I understand correctly the issue
![Screenshot 2024-02-29 173845](https://github.com/podkrepi-bg/frontend/assets/68897146/4624d179-8cac-4522-a319-ba18dd7b601a)

**Comment by swolf86** [comment]
@dzhaniivanov сори че не съм го описал по ясно. Ще го поправя за да е по ясно 

1вата част от текста за промяна е тази
![Screenshot_2024-03-07-08-57-13-06_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/podkrepi-bg/frontend/assets/75036745/9e6370fc-5da9-4e69-a03d-bf07286ca377)
