### ISSUE TITLE
Reorganize repository

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#173]
This issue contains general discussion for repository reorganization phase

Motivation:

The current layout of monorepo is not well-structured as it grew out of the frontend repo and there is a mixup of mandatory and non-mandatory root items

To be done:

- [x] Rename repository from `frontend` to something more appropriate (ideas are welcome)
  - [x] Provide easy to use git command to sync local environments of developers
  - [x] Rename packages `ghcr.io/daritelska-platforma/frontend/campaign` @miraclebg 
  - [x] Update deployment scripts @kachar 
  - [x] Update build scripts @kachar 
- [x] Extract frontend code in dedicated frontend folder `/frontend` @kachar 
  - [x] Move `Dockerfile`
  - [x] Move `public` folder
  - [x] Move `src` folder
  - [x] Check if env is well resolved
  - [x] Make sure root `package.json` scripts are functional
  - [x] Split `.gitignore` in dedicated files per microservice
  - [x] Make sure `.dockerignore` is set properly
  - [x] Update `docker-compose.dev.yml` with local mounting volumes
  - [x] Update links to old repo with the new name once renamed

Repo name ideas:

- `daritelska-platforma/podkrepi.bg`
- `daritelska-platforma/web`
- `daritelska-platforma/platform`
- `podkrepi-bg/web`
- `podkrepi-bg/app`
- `podkrepi-bg/platform`
- `podkrepi-bg/frontend`

:warning: Renaming the organization will have [additional impact](https://docs.github.com/articles/renaming-an-organization/)

**Comment by miraclebg** [comment]
I'm taking this one but it won't be earlier than end of next week.

**Comment by kachar** [comment]
@miraclebg It's not about whos taking it but what shall be implemented. I'd like to take care of the frontend work instead of you as I'm more acquainted with it.

**Comment by kachar** [comment]
@miraclebg Here's the first PR that extracts the frontend files in dedicated folder and fixes the nextjs build PR checks

**Comment by kachar** [comment]
Please everyone join us on this somewhat big decision about the monorepo proper naming

So far we've got the following repo name ideas:

- [ ] `daritelska-platforma/podkrepi.bg`
- [ ] `daritelska-platforma/web`
- [ ] `daritelska-platforma/platform`
- [ ] `podkrepi.bg/web`
- [ ] `podkrepi.bg/platform`



cc @daritelska-platforma/backend @daritelska-platforma/frontend @daritelska-platforma/devops

**Comment by igoychev** [comment]
voting for this one: 
daritelska-platforma/podkrepi.bg

**Comment by ani-kalpachka** [comment]
My vote is for "podkrepi.bg/platform".

**Comment by polibb** [comment]
- podkrepi.bg/platform :)

**Comment by xenry** [comment]
vote for podkrepi.bg/platform :)

**Comment by stanimirdim92** [comment]
vote for podkrepi.bg/platform

**Comment by igoychev** [comment]
Cools, so the vote winner is the podkrepi.bg/platform!

In this ticket we will rename the Organization only from daritelska-platforma to podkrepi.bg

For the repo itself, there is a popular demand to solve complications and move to a multi-repo environment, which will be done in separate effort.

So from the current mono-repo daritelska-platforma/frontend we will create multi-repos like this:
podkrepi.bg/platform for the whole deployment
podkrepi.bg/frontend - will hold the frontend only
podkrepi.bg/types - holds the Protobuf grpc contracts
podkrepi.bg/module-campaigns - will hold the Campaigns
podkrepi.bg/module-payments - will hold the Payments and so on

**Comment by igoychev** [comment]
Organization renamed to "podkrepi-bg" - it turned out '.' is not allowed.

**Comment by imilchev** [comment]
Are we still going for multiple repos? Some of the modules are already pretty detached and we could just move the folders to a new repo

**Comment by kachar** [comment]
@imilchev Let's create subtasks for migration of the modules to dedicated repos

- [ ] graphql gateway
- [ ] contact
- [ ] campaigns
- [ ] account ?

**Comment by imilchev** [comment]
This sounds like a good start. I can move contact the Go modules. They should be fairly simple to move now. We can also move the relevant issues to the respective repos.

**Comment by kachar** [comment]
@imilchev How does the update sound - extracting the `docker-compose` to a separate repo `platform` or in `infrastructure` to simplify and limit the scope of each module

**Comment by imilchev** [comment]
I am not sure if we want to keep the compose file. If we are going to a Kubernetes deployment, then the compose is irrelevant.

**Comment by kachar** [comment]
How will that impact the development process - should all devs bring up a local kubernetes cluster to start frontend development ?

We might support local compose stack for development and kubernetes for remote deployments

**Comment by imilchev** [comment]
To come back to this. I think we should just have a development cluster which can be accessed by the developers. By access I don't mean allow them to deploy stuff, but allow them to port-forward certain pods. Deployments should go only via workflows and we can deploy to dev on each commit on master for each component.

## Front-end developers
Port-forward the graphql-gateway while you actually work on the front-end locally. I don't see a realistic use-case where you need to the entire stack locally here. If you have any cases in mind, let's discuss them.

## Back-end developers
I think from an architectural point of view we do not want any direct dependencies between the modules. The only think that will have that is the graphql-gateway as it has to unify all gRPC interfaces into a single GraphQL instance. Assuming I work on the campaigns module I have no dependencies to other modules. The only thing is a database, which is now PostgreSQL and should be possible to run it locally on my development machine. I should also write unit and integration (on db level) tests for my code which should make sure it works according to specification. After I have all of that a PR is opened, reviewed and merged. When it is merged to master my changes will be automatically deployed to the dev cluster and there we can all see if I broke integration with other modules.

I think that should be more than sufficient start for the time being. Once our code base grows we might encounter different types of issues but those can be addressed then.

**Comment by kachar** [comment]
@imilchev You've got my support on this one.

As for port-forwarding maybe it should not be the only way to develop, but it should be limited to organization members.

For the general public we might keep the compose file with prebuilt public packages fixed at certain version so they can use the latest modules and develop locally without fear of breaking dev cluster.

**Comment by kachar** [comment]
I had in mind that the devs will have access to cluster config in order to port-forward the services locally. 
Having the cluster config might expose delpoying things to it, no?

Let's roll with the current plan and think about the compose file on later stage when it becomes a necessity.

**Comment by imilchev** [comment]
I think we can fix that with rights but we have to try it

**Comment by kachar** [comment]
Closing this one as it's a bit outdated and all modules now live in their own repos:

- https://github.com/podkrepi-bg/frontend
- https://github.com/podkrepi-bg/module-campaigns
- https://github.com/podkrepi-bg/module-contact
- https://github.com/podkrepi-bg/module-payment
- https://github.com/podkrepi-bg/module-admin
- https://github.com/podkrepi-bg/graphql-gateway
- https://github.com/podkrepi-bg/infrastructure
- https://github.com/podkrepi-bg/dev-containers
