### ISSUE TITLE
Disable the possibilty to write numbers in the card holder name during the payments 

### ISSUE THREAD

**Issue by Eduard990s** [podkrepi-bg/frontend#1761]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Desktop layout

### Describe the feature you'd like to request

Disable the possibility to write numbers in the card holder name during the payments

### Describe the solution you'd like

For the other fields where are required only numbers like the card number, date, cvc code you cannot put any letters, the same should be for the card holder field but with the numbers, you should not be able to put numbers in the cardholder name.
<img width="383" alt="Screenshot 2024-04-04 214228" src="https://github.com/podkrepi-bg/frontend/assets/163032619/f85c1479-22cf-4d94-8be0-edfb12018267">

### Describe alternatives you've considered

it's not a big deal so no other alternatives but could help people that are not very able with the technology to avoid mistakes.

**Comment by katina-anachkova** [comment]
please, assign this task to me.
