### ISSUE TITLE
Login Page/Register Page - Clicking on "Login/Continue with Google button" doesn't redirect to login with Google

### ISSUE THREAD

**Issue by FlyWithMarie** [podkrepi-bg/frontend#1762]
### Describe the Bug

Clicking on "Login with Google" button only refreshes/ reloads the Login page.
Same happens with Register Page - clicking on "Continue with Google" button only refreshes/ reloads the page.

I reproduced it many times with Mozilla and Chrome, had my browser's cookies and cache, history cleared (just in case). 

Same bug was reported on Mar 16, 2023 - #1389 and closed. 
There is one comment saying: "The good news is that the Google login does work, if you are persistent and patient enough, to click on the button until it does." -- I tried that many times and it doesn't work. 

https://github.com/podkrepi-bg/frontend/assets/158328628/c6bc11d6-8990-470b-bb15-2e219b0ae8ac

### To Reproduce

For Login Page:
1. Open https://podkrepi.bg/login 
2. Click on "Login with Google"

For Register page:
1. Open https://podkrepi.bg/en/register
2. Click on "Continue with Google button"

### Expected Behavior

User should be redirected to a page to login using his Google Credentials or login directly using his Google Profile. 

### Which browser are you using? (if relevant)

Chrome: Version 123.0.6312.106 (Official Build) (64-bit), Mozilla: 124.0.2 (64-bit)

**Comment by ani-kalpachka** [comment]
I tested several times (on desktop and mobile) and could not reproduce this issue. 
I will close the ticket assuming it is fixed. If it appears again please feel free to reopen it.
