### ISSUE TITLE
Login Page - Login Form - Error message when I first try to "Login with Google" and then proceed to login via the Login form

### ISSUE THREAD

**Issue by FlyWithMarie** [podkrepi-bg/frontend#1763]
### Which area(s) of Podkrepi.bg are affected?

Other

### Describe the Bug

If I try to login with Google (at the moment this option is inactive as reported in [#1762](https://github.com/podkrepi-bg/frontend/issues/1762)) and then proceed to login through the Login Form, I get an error message: "Wrong user/password". 
Refreshing the page or clicking on your Profile shows that you've already been successfully logged in.

https://github.com/podkrepi-bg/frontend/assets/158328628/a44c545e-f40a-4c36-8708-e2ea7e258ca9

https://github.com/podkrepi-bg/frontend/assets/158328628/6ad267fc-dd42-484d-8eed-139b13876d0f

### To Reproduce

Precondition: User has already been registered. 

1. Open https://podkrepi.bg/login
2. Click on "Login with Google" button (this option is inactive at the moment)
3. Enter a valid username and password in the login form 
4. Click "Login" button

### Expected Behavior

User should be notified that he logged in successfully and be redirected to his profile page.

### Which browser are you using? (if relevant)

Chrome: Version 123.0.6312.106 (Official Build) (64-bit), Mozilla: 124.0.2 (64-bit)

**Comment by ani-kalpachka** [comment]
The "Login with Google" option is active now and the problem seems not be valid anymore.
