### ISSUE TITLE
Active Campaings - Error 500 when clicking on "Subscribe for email notifications for the campaign"

### ISSUE THREAD

**Issue by FlyWithMarie** [podkrepi-bg/frontend#1770]
### Which area(s) of Podkrepi.bg are affected?

Other

### Describe the Bug

User gets an Internal Server Error message when clicking "Subscribe for email notifications for the campaign". 

This only happens for around 50% of the active campaigns. The issue is reproducible after clearing the cache and cookies.

All active campaigns have been tested and here is a list of those that get the Error msg:
1) https://podkrepi.bg/en/campaigns/zaedno-da-izgradim-vila-autistika
2) https://podkrepi.bg/en/campaigns/breast-cancer-rotary-club
3) https://podkrepi.bg/en/campaigns/da-vuzrodim-chitalishnata-dejnost-i-zaedno-da-postroim-edno-novo-moderno-chitalishe-trotoara-2020
4) https://podkrepi.bg/en/campaigns/da-sbudnem-mechtata-na-valeriya-da-vleze-v-top-5-na-evropa-v-tenisa
5) https://podkrepi.bg/en/campaigns/myastoto-kudeto-starite-zanayati-se-sreshat-s-novite-tehnologii-rabotilnica-ela
6) https://podkrepi.bg/en/campaigns/champions-canoeing-bdin-77
7) https://podkrepi.bg/en/campaigns/uchilishe-za-rabota-v-pomosh-na-mladezhi-lisheni-ot-roditelska-grizha
8) https://podkrepi.bg/en/campaigns/krizisen-centur-za-postradali-ot-nasilie-gr-pernik-shans-za-nov-zhivot
9) https://podkrepi.bg/en/campaigns/konna-terapiya-za-detsa

https://github.com/podkrepi-bg/frontend/assets/158328628/975a76bb-2f4f-4418-908c-90054f931563

![Subscribe_For_email](https://github.com/podkrepi-bg/frontend/assets/158328628/14937ba6-313c-4185-b8e3-4885cccd0818)

### To Reproduce

1) Open https://podkrepi.bg/
2) Login with a valid username and password
3) Click "Campaigns" and select "All Campaigns"
4) Select any of the listed in the "Describe the Bug" section campaigns (ex: "„Вила АутистикА” - ..")
5) Click "Subscribe for email notifications for the campaign"
6) Click "On the profile one" button in the pop-up window

### Expected Behavior

A success message should appear confirming that the user subscribed successfully for email notifications for the chosen campaign.

### Which browser are you using? (if relevant)

Chrome: Version 123.0.6312.124 and Firefox: Version 124.0

**Comment by ani-kalpachka** [comment]
Closing the ticket since it seems to be fixed as part of #1788

**Comment by sashko9807** [comment]
Still awaiting the fix to be merged.

**Comment by Tuscann** [comment]
Please do not close this bug before merge and deployed.
