### ISSUE TITLE
Not working hyper link on campaign (404 not found page on external website)

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1789]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/03cad656-8ab1-4251-9718-6459c5b7bb23)
Not working link under "257 podcast"

### To Reproduce

1. Open [https://podkrepi.bg/campaigns/uchilishe-za-rabota-v-pomosh-na-mladezhi-lisheni-ot-roditelska-grizha](https://podkrepi.bg/campaigns/uchilishe-za-rabota-v-pomosh-na-mladezhi-lisheni-ot-roditelska-grizha)
2. Try to click on "257 podcast"
3. Open 404 error page on external webpage.

### Expected Behavior

Open website

### Which browser are you using? (if relevant)

Vivaldi Firefox Brave

**Comment by ani-kalpachka** [comment]
Good catch! Closing the issue here as a responsibility of the Campaigns team.
We can list the issues regarding campaign texts and ping Campains team for them.

**Comment by ZGornachka** [comment]
It's working
