### ISSUE TITLE
Wrong nomeration for campaign "Boris and his steps towards space" .

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1793]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout, Mobile layout, Campaigns

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/af084739-1d0d-4889-af58-3b5313b49919)

Wrong nomeration in campaign.
Why we have 3 times 1?

### To Reproduce

1. Open [https://podkrepi.bg/campaigns/boris-steps-towards-space#wishes](https://podkrepi.bg/campaigns/boris-steps-towards-space#wishes)
2. Check bulet points.
3. Why we have 3 time 1

### Expected Behavior

1.
2.
3.

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
@Tuscann Thanks for noticing this. Could you please connect the Campaigns team? They are responsible for editing the texts of the campaigns. I will close the issue here because it is not accessible on the front end.

**Comment by ZGornachka** [comment]
Done
