### ISSUE TITLE
Not seen fully message after subcription for campaign on mobile phone

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1795]
### Which area(s) of Podkrepi.bg are affected?

Mobile layout, Campaigns

### Describe the Bug

https://github.com/podkrepi-bg/frontend/assets/16596102/bbdf899a-64e0-4709-adf2-ff7a5940815c

Not seen message on mobile phone.

### To Reproduce

Watch video first.
1. Subsribe for campaign [https://podkrepi.bg/en/campaigns/tatianas-space-journey-continues](https://podkrepi.bg/en/campaigns/tatianas-space-journey-continues)
2. Click on button "На профилния"
3. **Open email on mobile phone**
4. Open website and message is not fully visible.

### Expected Behavior

To see full message.

### Which browser are you using? (if relevant)

Vivaldi mobile.

**Comment by Tuscann** [comment]
Interesting currently not possible to reproduce the bug on same device.

**Comment by ani-kalpachka** [comment]
I think your screen was zoomed and that is what caused this effect.
I will close the ticket. If the issue appear again, please feel free to reopen.
