### ISSUE TITLE
Add space for better view in campaign „Земята на розите“- филм за болката и надеждата!"

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1805]
### Which area(s) of Podkrepi.bg are affected?

Campaigns

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/0f6ceb75-925b-44d1-a846-9c611a2b2d15)
Add extra space before dash. Looks better.

### To Reproduce

1. Open [https://podkrepi.bg/en/campaigns/the-land-of-roses](https://podkrepi.bg/en/campaigns/the-land-of-roses)
2. Check space before dashes

### Expected Behavior

Add extra space before dashes in all 32 rows

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
Closing this ticket as a Campaigns team responsibility.

**Comment by ZGornachka** [comment]
Fixed
