### ISSUE TITLE
Error link on youtube video on Campaign

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1806]
### Which area(s) of Podkrepi.bg are affected?

Campaigns

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/1acd6e1f-587b-457f-9619-4c616f382616)
Not working YouTube link.

### To Reproduce

1. Open [https://podkrepi.bg/campaigns/scouts-jamboree-korea](https://podkrepi.bg/campaigns/scouts-jamboree-korea)
2. Click on link "YouTube канала на Организация на българските скаути"
3. Open wrong Youtube

### Expected Behavior

Fix or remove YouTube link.

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ZGornachka** [comment]
> ### Which area(s) of Podkrepi.bg are affected?
> Campaigns
> 
> ### Describe the Bug
> ![image](https://private-user-images.githubusercontent.com/16596102/333199508-1acd6e1f-587b-457f-9619-4c616f382616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTc1MDEsIm5iZiI6MTcyMTM5NzIwMSwicGF0aCI6Ii8xNjU5NjEwMi8zMzMxOTk1MDgtMWFjZDZlMWYtNTg3Yi00NTdmLTk2MTktNGM2MTZmMzgyNjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEzNTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmNkNTcxYTgyOWVkZWNhZDgzYTVjYzJlNDlmYWE1YzkwNjljMWUwN2QzYTZhOGU5NjdlNjg4NjdjNDkxMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ifrVytKbIC1Ed9p060mwfQzb9Yfc9kqLEXd53igGJA) Not working YouTube link.
> 
> ### To Reproduce
> 1. Open https://podkrepi.bg/campaigns/scouts-jamboree-korea
> 2. Click on link "YouTube канала на Организация на българските скаути"
> 3. Open wrong Youtube
> 
> ### Expected Behavior
> Fix or remove YouTube link.
> 
> ### Which browser are you using? (if relevant)
> Vivaldi

**Comment by ZGornachka** [comment]
Fixed
