### ISSUE TITLE
[Feature] Add user register / authentication

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#181]
At the moment we don't have a clear way to register users in the platform.

We've added an integration with social providers via https://next-auth.js.org/ but that's not completed.

Already done:
* https://podkrepi.bg/register
* https://podkrepi.bg/login
* https://podkrepi.bg/logout

List of things to be accomplished:

- [ ] Store users to internal datastore after social login
- [ ] Provide authentication graphql layer for other microservices (via #180)

**Comment by igoychev** [comment]
depends on https://github.com/podkrepi-bg/infrastructure/issues/6

**Comment by imilchev** [comment]
Isn't this a duplicate of #315?

**Comment by kachar** [comment]
Done
