### ISSUE TITLE
Why sticky header change vertical size when scrolling ?

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1815]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

https://github.com/podkrepi-bg/frontend/assets/16596102/30afadbb-27aa-465b-8102-17fc1cbfe47f

Top bar change vertical size when scrolling .

### To Reproduce

1. Open [https://podkrepi.bg/en](https://podkrepi.bg/en)
2. Start scrolling with mouse up and down on page
3. Check size of the top bar

**Fixed (Sticky) header
Sticky headers present another trend able to boost usability is applied effectively. Actually, it enables to provide users with navigation area available at any point of interactions, which can be helpful in terms of content-heavy pages with long scrolling.**

### Expected Behavior

Top bar do not change vertical size on scrolling.

### Which browser are you using? (if relevant)

Brave

**Comment by ani-kalpachka** [comment]
This effect is supposed to be implemented by design - when the user opens the page the Header has height of 88px. When the page is scrolled down - the height of the Header is changed to 64px.
