### ISSUE TITLE
Translate to bulgarian table in tab "Доброволци" in admin panel

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1816]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/641e48b1-872e-4d77-9856-7f1261d33a27)

Need translation to bulgarian name of columns

### To Reproduce

1.Open [https://podkrepi.bg/admin/supporters](https://podkrepi.bg/admin/supporters)
2. Login with admin user
3. Check all columns names.
4. 

### Expected Behavior

Name of columns to be in bulgarian.

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
The issue is fixed here: https://github.com/podkrepi-bg/frontend/pull/1838
I will close the ticket as completed.
