### ISSUE TITLE
Not possible see end home page on Mobile layout before take decision for cookies

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1822]
### Which area(s) of Podkrepi.bg are affected?

Mobile layout

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/5284f5d0-0f03-45f9-9bba-b6ef830e5652)

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/7dabccb7-0f6a-4166-b643-463e8dc6a19b)

### To Reproduce

1. Open [https://podkrepi.bg/en](https://podkrepi.bg/en) on mobile device
2. Scroll to end of the page
3. Check is possible to see end of the page before agree with cookies?

### Expected Behavior

Changed to see full page after that to see message for cookies on mobile version.

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
Isn't this the standart behaviour?
The cookie consent dialog is intentionally on the top of the other elements and is sticked at the bottom of the screen. On desktop it is the same. On some websites the content is even blocked until rhe cooki consent is accepted.
If this behaviour is not longer a wanted, we cound change it into modal or find another solution. I am closing this issue. If some future changes are requested, please feel free to reopen.
