### ISSUE TITLE
Toolltip now shown on register on mobile device

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1823]
### Which area(s) of Podkrepi.bg are affected?

Mobile layout

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/c12c8ab5-57ff-4585-ad01-bd6509ab9870)

Toolltip on "Повече информация" not shown on mobile device
Missing way to see Toolltip "Дарения от този профил ще се извършват от името на организацията, която представлявате" on mobile device.

### To Reproduce

1. Open [https://podkrepi.bg/register](https://podkrepi.bg/register) on mobile device
2. Put mouse over "повече информация"
3. Wait tooltip to be shown.

### Expected Behavior

Show missing tooltip

### Which browser are you using? (if relevant)

Vivaldi

**Comment by iliyan90** [comment]
I suggest Modal ???

**Comment by sashko9807** [comment]
Seems like there is some delay of 700ms on touch events, before the tooltip is shown. It should work if the tooltip is held long enough. 
We could decrease the on touch delay for now, thru enterTouchDelay prop of Tooltip [Tooltip Api Docs.](https://mui.com/material-ui/api/tooltip/#tooltip-prop-enterTouchDelay)
