### ISSUE TITLE
Subscribe for email notifications for the campaign not work again

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1914]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout, Mobile layout, Campaigns

### Describe the Bug

Subscribe for email notifications for the campaign not work again

### To Reproduce

https://github.com/podkrepi-bg/frontend/issues/1770 Maybe same bug closed
https://github.com/podkrepi-bg/frontend/issues/1788 Maybe same bug closed

1. Open https://podkrepi.bg/en/campaigns/social-workshop-missionconstrustion-russe
2. Click on text "Subscribe for email notifications for the campaign."
3. On another one
![image](https://github.com/user-attachments/assets/3f745f8c-eebe-408a-94d6-2bd3746462f9)
Click close 
4. Click on text "Subscribe for email notifications for the campaign."
5. On profile one
6. Throw error

https://github.com/user-attachments/assets/beaee749-84e5-4fcc-9a8b-9f36f86a11d0

### Expected Behavior

Subscribe for email notifications

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
It is fixed on dev environment: 

![image](https://github.com/user-attachments/assets/5f9ed922-d646-4d49-a92e-aaba34a6f374)

The changes could be seen on prod after deployment.
