### ISSUE TITLE
Try to change Birthdate in personal-information to 03/10/2017 not work

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1915]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

Try to change Birthdate in personal-information to 03/10/2017 not work

### To Reproduce

1. Open https://podkrepi.bg/en/profile/personal-information on English
2. Click edit on Birthday
3. Add date 03/10/2017
4. Click button Send
5. Noting happen

https://github.com/user-attachments/assets/7051c91b-e299-4943-a2c3-a6cdd084983c

### Expected Behavior

Show some message that user need to be more than 18 years or not possible to add dates in future

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
@Tuscann I tried to reproduce it with normal login and I was able to change it.
Can you please confirm that the user is not allowed to change the date only when logged with Google?

**Comment by Tuscann** [comment]
https://youtu.be/AKGD3JYSwjU  This is with abv mail.
