### ISSUE TITLE
[Feature] As an Organizer, I can Create new Campaign

### ISSUE THREAD

**Issue by stann1** [podkrepi-bg/frontend#192]
As an Organizer, I can create a new campaign, using the 'campaign creation form' (reference: wireframes, name: TBD).

Acceptance criteria:
1. User can fill-in the form fields
2. Fields have inline validation for data type and required status
3. User can submit the form if it is correct
4. Campaign is created and the user is redirected to next step (approval)
5. Campaign is auto-associated with the current organizer
6. The user can only select an existing beneficiary, creating one is out of scope
7. The user can only select an existing category/sub-category, creating one is out of scope
8. Campaign entity is created with meta props: created on (date), created by (identifier)

Input fields:

- Title * (string, max-length 100)
- Beneficiary * (identifier - beneficiery id)
- Category * (dropdown)
- Sub-category * (dropdown)
- Description (string, max-length 2000)
- TargetSum (number)
- Attachments * (file-upload, multiple)

---

Wireframes:

- https://www.figma.com/file/nt261pv6aIFMzvu3S9hxSN/Untitled?node-id=1%3A7
- https://www.figma.com/file/RYfJNeymmqXdbVTtdmQzva/Podkrepi-Campaign?node-id=0%3A1

**Comment by kachar** [comment]
Added figma wireframe links to description

- https://www.figma.com/file/nt261pv6aIFMzvu3S9hxSN/Untitled?node-id=1%3A7
- https://www.figma.com/file/RYfJNeymmqXdbVTtdmQzva/Podkrepi-Campaign?node-id=0%3A1

![2_Дарителство - създай кмапания - Step 3](https://user-images.githubusercontent.com/893608/120918537-95d7d280-c6bd-11eb-9b02-bdd321fdbcd6.png)
