### ISSUE TITLE
Typos in Annual financial report for 2023

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1950]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout, Mobile layout, Other

### Describe the Bug

Typos in Annual financial report for 2023

### To Reproduce

1. Open https://podkrepi.bg/finance-reports/Podkrepi.bg_Financial_Report_2023.pdf
2. Got to page 24
![image](https://github.com/user-attachments/assets/f6fd40cf-4f4e-4d7c-88ae-37026cd66317)

 **Add space between 2024г and 2033г.
 бешезаписано** change to беше записано

### Expected Behavior

Fix typos

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
Here is the updated file for the annual 2023 report:
[Podkrepi.bg_Financial_Report_2023.pdf](https://github.com/user-attachments/files/17290330/Podkrepi.bg_Financial_Report_2023.pdf)
