### ISSUE TITLE
Bugs in campaign "Да помогнем на Дори да осъществи мечтата си да учи и работи"

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1959]
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

1. Do we need dot (.) after 8.клас ?

![image](https://github.com/user-attachments/assets/ae568a87-a5f5-41e1-a955-62e6d626e8c7)

2. What is meaning of word "са".  Can write this text in different way or remove "са"?
![image](https://github.com/user-attachments/assets/d5ec5e69-2035-4f9b-9d32-4e00c0c98d52)

3. Why has two rows of empty lines ? Only one line.
![image](https://github.com/user-attachments/assets/ff76fbc0-0280-4c7b-a28d-6fd7a4c495bc)

4. Сумата, необходима на Дори . Do we need , between Сумата, необходима 
![image](https://github.com/user-attachments/assets/1d8c3b4a-9288-4af9-9b8b-186ab06c08e3)

5. Why only here is the full name "Доротея" not  "Дори"?
![image](https://github.com/user-attachments/assets/cba96701-6534-4af2-b21c-003e2cebb148)

6.  Can we have same order in text the like in table?
![image](https://github.com/user-attachments/assets/f8e0e6bf-539b-46d0-9fd6-1d15fd30d717)

7. Missing closing bracket.
![image](https://github.com/user-attachments/assets/5144cb83-960b-4ea0-aaae-a5a21241e437)

### To Reproduce

1. Do we need dot (.) after 8.клас ?

![image](https://github.com/user-attachments/assets/ae568a87-a5f5-41e1-a955-62e6d626e8c7)

2. What is meaning of word "са".  Can write this text in different way or remove "са"?
![image](https://github.com/user-attachments/assets/d5ec5e69-2035-4f9b-9d32-4e00c0c98d52)

3. Why has two rows of empty lines ? Only one line.
![image](https://github.com/user-attachments/assets/ff76fbc0-0280-4c7b-a28d-6fd7a4c495bc)

4. Сумата, необходима на Дори . Do we need , between Сумата, необходима 
![image](https://github.com/user-attachments/assets/1d8c3b4a-9288-4af9-9b8b-186ab06c08e3)

5. Why only here is the full name "Доротея" not  "Дори"?
![image](https://github.com/user-attachments/assets/cba96701-6534-4af2-b21c-003e2cebb148)

6.  Can we have same order in text the like in table?
![image](https://github.com/user-attachments/assets/f8e0e6bf-539b-46d0-9fd6-1d15fd30d717)

7. Missing closing bracket.
![image](https://github.com/user-attachments/assets/5144cb83-960b-4ea0-aaae-a5a21241e437)

### Expected Behavior

Fix the bugs

### Which browser are you using? (if relevant)

Vivaldi

**Comment by ani-kalpachka** [comment]
Closing the ticket as completed.
It is synced with Campaigns team.
