### ISSUE TITLE
Fix typo in Homepage heading

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#1986]
### Describe the Bug

There is a spelling error in the heading "How does Podkrepi.bg work?" section on Homepage:

<img width="943" alt="Screenshot 2024-11-27 083430" src="https://github.com/user-attachments/assets/0ff1ee2c-9a91-4f40-b2f8-96ad5d4b733b">

### To Reproduce

1. Go to https://podkrepi.bg/en
2. Scroll to "How does Podkrepi.bg work?" section.
3. Obsere the section heading.

### Expected Behavior

The platform's name should be written correctly.

**Comment by slusy** [comment]
Hey, I would like to work on this

**Comment by ani-kalpachka** [comment]
@slusy it is assigned to you.
