### ISSUE TITLE
[Feature] Add jest or other testing framework to frontend stack

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#222]
At the moment testing framework has not been set up.

With this issue we'll track the progress of integrating a testing framework

**Candidates**

- https://jestjs.io/
- https://github.com/testing-library/react-testing-library
- Others (add with comment)

https://reactjs.org/docs/testing-recipes.html

**Comment by arthas168** [comment]
I think we could go ahead with Jest, since it's a widely known framework and even React themselves seem to recommend it the most :)

**Comment by spazbg** [comment]
Currently, Cypress is one of the most famous e2e testing frameworks. 
Since the last stable version 7.0 has new functionality - Component Testing. It can be used for running tests on a component in isolation. 
https://docs.cypress.io/guides/component-testing/introduction#What-is-Component-Testing
I am a big fan of Cypress, it can be used for unit, integration, e2e testing, and so on - one framework, same commands :)

**Comment by StanislavSt** [comment]
react-testing-library running with Jest is best approach for integration tests in my opinion. Very easy to use with the least boilerplate code. I can create a PR, where I set it up and add a couple of tests.

**Comment by StanislavSt** [comment]
I have been out of the development in this project so not sure what is the state and if we have REST/GraphQL API calls , but this is also worth checking if we want to test API calls with proper mocking - https://github.com/mswjs/msw

**Comment by spazbg** [comment]
Cypress can test the frontend as well as the backend (including mocking). Sorry, big fen of the framework here :)

**Comment by arthas168** [comment]
Yep, Cypress is awesome

**Comment by StanislavSt** [comment]
Any updates on this feature? I have only seen cypress being used for e2e tests that are slow and ran nightly or even weekly. For integration/unit tests I have personally seen only Jest/react-testing-library tests, that would run on every push to a PR inside the CI/CD. Does Cypress offer integration/unit test options , where no browser needs to be spawned ?
