### ISSUE TITLE
[Bug] Skip (leave empty) input sections (Role and Additional questions) in Support form.

### ISSUE THREAD

**Issue by tanyogeorgiev** [podkrepi-bg/frontend#229]
1. Go to [https://podkrepi.bg/en/support](https://podkrepi.bg/en/support)
2. Check some option
3. Click Next
4. Click Back
5. Uncheck option
6. Click on upper Additional Section Image (not Next button)
7. Click Next Button

**Comment by kachar** [comment]
Code reference: https://github.com/daritelska-platforma/frontend/blob/0f074f5695c6516b4ec6adfad38cd71c53bb3baf/frontend/src/components/support-form/SupportForm.tsx#L166-L173
