### ISSUE TITLE
[Feature] Optimize images size

### ISSUE THREAD

**Issue by tvalchev** [podkrepi-bg/frontend#249]
**Is your feature request related to a problem? Please describe.**
I saw that the performance is not bad, but it is not optimal. I saw that the images are not optimized.

**Describe the solution you'd like**
There is online tool that reduce the image size, without losing quality: https://squoosh.app/.
For example the image discord-team-image.png reduce the size from 325 KB to 66.1 KB.
Also is recommended to use webp extension. Lazy loading also could help for performance.

**Describe alternatives you've considered**
N.A

**Additional context**
![podkrepibg_performance](https://user-images.githubusercontent.com/7523222/121357796-c11b2580-c93a-11eb-8282-aab6a64a734f.JPG)
![podkrepibg_performance2](https://user-images.githubusercontent.com/7523222/121357801-c1b3bc00-c93a-11eb-8809-eaab5b0f6543.JPG)

**Comment by tvalchev** [comment]
Proposal:

1. add LazyLoad component to load specific part

```
const LazyLoad = ({ ...props }) => {
  const [isLoaded, setIsLoaded] = useState(false);

  const onLoad = useCallback(() => {
    setIsLoaded(true);
  }, []);

  useEffect(() => {
    window.addEventListener('load',onLoad);

    return () => {
      window.removeEventListener("load", onLoad);
    };
  }, [onLoad]);

  let retObject = null;

  if(isLoaded){
    retObject = props.children;
  }

  return retObject;
};

export default LazyLoad;
```

For example MissionVisionGoalsSection component load 3 images as background.

if we wrap the elements like this:

  ```
<LazyLoad>
      <Grid container justify="center" component="section" className={classes.container}>
        <Grid item className={classNames(classes.mission, classes.wrapper)}>
          ...
        </Grid>
        <Grid item className={classNames(classes.vision, classes.wrapper)}>
         ...
        </Grid>
        <Grid item className={classNames(classes.goals, classes.wrapper)}>
          ...
        </Grid>
      </Grid>
    </LazyLoad>
```
	
We will have benefit to load images on background on first load.

2. The other option is to modify the code and use React.lazy import.

Not sure which approach is better. 

@kachar Can you give opinion or add another person into thread

**Comment by kachar** [comment]
@tvalchev Next.js has a builtin image loading component `next/image`

* https://nextjs.org/docs/basic-features/image-optimization
* https://nextjs.org/docs/api-reference/next/image

I don't think we need to re-ceate that functionality with custom code

**Comment by kachar** [comment]
About the image optimization with a tool - I think that's a must have

There are online services as the one you've mentioned and alsoe there's `optipng` http://optipng.sourceforge.net/ tool

**Comment by tvalchev** [comment]
What about webp format, i didnt find any good example without using some libraries :). Do you know something for this?

**Comment by kachar** [comment]
@tvalchev Please read the links provided. Next.js image component converts the images to `webp` format automatically.

> The Automatic Image Optimization allows for resizing, optimizing, and serving images in modern formats like WebP when the browser supports it. This avoids shipping large images to devices with a smaller viewport. It also allows Next.js to automatically adopt future image formats and serve them to browsers that support those formats.

https://nextjs.org/docs/basic-features/image-optimization
