### ISSUE TITLE
[Bug] TeamPie chart rescale on window resize

### ISSUE THREAD

**Issue by wessly** [podkrepi-bg/frontend#255]
**Describe the bug**
When user resize Index page from low to high resolution Highcharts (for TeamPie chart) rescales the chart properly. But when user downscales the resolution of the page - chart did not downscales properly.

**To Reproduce**

1. Go to Index page
2. Resize window from high resolution to low
3. Scroll down to TeamPie chart

**Expected behavior**
Properly rescaled chart when window is resized.

**Screenshots**
https://imgur.com/a/mh22HQb

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 89

**Additional context**
I suggest of using .reflow() on chart when window is resized.

**Comment by kachar** [comment]
@wessly Thanks for reporting it, indeed it's quite annoying. Feel free to submit a proposal with a fix for the problem.

Maybe the problem only occurs when user switches the resolitions from dev console, not sure if the real user behavior will follow this pattern.

**Comment by igoychev** [comment]
fixed by @skilldeliver with #282
