### ISSUE TITLE
[Feature] Apply english translations

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#257]
Apply english and bulgarian translations from the following document

https://docs.google.com/spreadsheets/d/1yy2Gu9cETR2i5H_AyPR2tNqVJNcNHZru/edit#gid=1949333258

**Comment by ani-kalpachka** [comment]
New translations changes are applied. PR created: https://github.com/daritelska-platforma/frontend/pull/263
The needed changes on the graphics are in progress.
