### ISSUE TITLE
[Feature] Integrate CMS so articles can be remotely fetched and edited

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#274]
**Is your feature request related to a problem? Please describe.**
Marketing team needs to add and edit articles dynamically so no release is required for them to be present on the website.

**Describe the solution you'd like**
Integrate open-source headless CMS ghost as part of the stack or standalone

## Ghost

- https://ghost.org/
- https://github.com/TryGhost/Ghost
- https://ghost.org/docs/api/v3/nextjs/
- https://hub.docker.com/_/ghost
- https://hub.docker.com/r/bitnami/ghost/

## Strapi

- https://strapi.io/
- https://github.com/strapi/strapi
- https://strapi.io/blog/build-a-blog-with-next-react-js-strapi
- https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html
- https://medium.com/swlh/deploy-strapi-on-kubernetes-with-https-1e3437bf2ca3

**Describe alternatives you've considered**

- Wordpress - too much overhead to make it completely headless

Feel free to suggest other alternatves

**Comment by skilldeliver** [comment]
Perhaps [Strapi](https://strapi.io/) is worth to be considered too as headless CMS.

Compared with Ghost I think Strapi provides more flexibility with the data types and the relations.

In my opinion Ghost provides more friendly interface for non-technical people than Strapi maybe it is a better choice overall.

**Comment by kachar** [comment]
@skilldeliver Added Strapi to the list of candidates, it looks nice and supports docker containers out of the box

https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html

**Comment by kachar** [comment]
This is done, we've got https://blog.podkrepi.bg/ up and running on top of https://ghost.org/
