### ISSUE TITLE
[Feature] Automate CSV export of registered volunteers list

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#281]
At the moment the support requests are being stored in local db with no way of exporting them to the people that will contact those supporters.

We need to find a way to automate those exports so we can notify the team about new support requests

**Comment by skilldeliver** [comment]
I have some questions:
What is the current workflow?
Perhaps we need to create separate endpoint for exporting db info into CSV?
Do we need some kind of admin page where non-technical people can export the support requests, I don't know what is the state of this project: https://github.com/podkrepi-bg/admin?

**Comment by imilchev** [comment]
Why is a CSV even needed? We could make a simple front-end for that, I guess? I want to update the contact module a bit to setup linting, building etc. Then I was planning to create an issue to completely refactor it. @preslavgerchev was up for that. Set up logging, tests, split the json columns into dedicated tables where needed. Then we can look into making a front-end or something for it unless there is a specific reason why CSV is needed

**Comment by kachar** [comment]
@imilchev It will be best if we have an interface for the supporters and other records.

At the moment the admin is on hold as nobody is working on it

**Comment by imilchev** [comment]
then I don't think CSV export will be of much use. We might as well give someone read credentials to the DB and a query to run

**Comment by igoychev** [comment]
It looks like this depends on the system having permissions and user login. Adding dependency to: https://github.com/podkrepi-bg/infrastructure/issues/6

**Comment by kachar** [comment]
The team can browse the latest contributors at https://podkrepi.bg/admin

Closing the issue as the main goal is to have that list available for use, no matter the format.
