### ISSUE TITLE
[Feature] Add partners section in the index page

### ISSUE THREAD

**Issue by skilldeliver** [podkrepi-bg/frontend#284]
We need to create a section in the index page where we can list logos with URLs to partners of https://podkrepi.bg/

**Comment by chandu-jadhav** [comment]
hey can I work on this?

**Comment by valkirilov** [comment]
Do we have a design for that or it's still not a priority one?

**Comment by MartinHristovv** [comment]
can you assign it to me ?

**Comment by igoychev** [comment]
completed https://podkrepi.bg/partners
