### ISSUE TITLE
[Feature] Prepare ghost blog instance for usage

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#291]
Ghost instance is running at http://ghost.ghost.185.80.0.162.nip.io/

- [x] Link DNS to actual running pod
- [x] Setup ghost theme and branding
- [x] Add DNS to ghost instance - `blog.podkrepi.bg`
- [x] Add SSL to ghost instance (via cloudflare)
- [x] #293
- [x] #296

**Comment by imilchev** [comment]
I guess this can be closed now?

**Comment by kachar** [comment]
Sure! All good now! :rocket:
