### ISSUE TITLE
[Feature] Frontend: As a visitor, I can list all available campaigns

### ISSUE THREAD

**Issue by mayapeneva** [podkrepi-bg/frontend#295]
Acceptance criteria:

Accessible by registered and unregistered users
Campaigns are showed in a paged list/grid-view, which can be ordered by Campaign Title or Creation date (default selection, ascending)
Campaigns can be searched using a search input
Visible columns:

- Title
- Category
- Description
- Beneficiary (name)
- Details link
- Status

**Comment by igoychev** [comment]
Available here: https://dev.podkrepi.bg/campaigns
