### ISSUE TITLE
[Feature] Build contact and campaign modules on every PR

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#311]
**Is your feature request related to a problem? Please describe.**
Add a workflow to build campagins module on each PR so we know if something is not okay with the dockerfile

Similar to https://github.com/podkrepi-bg/frontend/blob/master/.github/workflows/docker-build-pr.yml

**Comment by imilchev** [comment]
I guess that would mean extending this https://github.com/podkrepi-bg/frontend/blob/master/.github/workflows/contact.yml with a docker build

**Comment by kachar** [comment]
@imilchev Looks like we need it both for contact and campaigns, so we don't break the build without noticing
