### ISSUE TITLE
Move `campaigns` to new repo

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#323]

**Comment by preslavgerchev** [comment]
@xenry @mayapeneva what do you think of also moving campaigns-related migrations to the new repo as well? Then it's a completely standalone module

**Comment by mayapeneva** [comment]
I believe all migrations should be in one place. I have no objections.

**Comment by xenry** [comment]
@preslavgerchev currently we have a single database for all modules, so all migrations need to be in one place and to be executed in order. I have no objections to having a separate db for the campaigns module though.

**Comment by imilchev** [comment]
I will hopefully do that today
