### ISSUE TITLE
Replace `cockroachdb` with `postgres`

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#325]

**Comment by imilchev** [comment]
@kachar how do you want to handle that with the current production deployment which is still running cockroachdb? We already have the modules migrated to PostgreSQL (except for accounts but it is not used at all). Should we aim at fixing the compose environment or should we move everything to the production cluster and just delete the compose structure?

**Comment by kachar** [comment]
@kachar let's start the new prod environment and switch to that one

We don't really need to transfer the data from the old cluster to the new db as there like 5 records that we can move manually.

I don't think we need to fix the compose env anymore for the old cluster. We might keep the compose file only for local development and make it work with pre-built packages instead of runtime building them. It will be awsome if we take it out of the frontend repo all together.

The best and simplest way to develop frontend locally still remains to do it without docker containers.
