### ISSUE TITLE
[Feature] Setup a cloud mail services provider (AWS SES)

### ISSUE THREAD

**Issue by miraclebg** [podkrepi-bg/frontend#329]
- Setup a new AWS account
- Setup SES services
- Setup frontend / backend to send transactional mail through it
- Setup keycloack to send transactional mail through it

**Comment by miraclebg** [comment]
Created - to use the smtp server use the following data (request user/password from me directly):

Server Name:	
email-smtp.eu-central-1.amazonaws.com
Port:	25, 465 or 587
Use Transport Layer Security (TLS):	Yes
Authentication:	Your SMTP credentials. See below for more information.

**Comment by miraclebg** [comment]
Keycloack configured.

Pending AWS acc approval and this card can be closed.

**Comment by kachar** [comment]
@miraclebg The AWS account should be working fine by now, correct? If so we might close this one

**Comment by igoychev** [comment]
The account is created and the access details are in MartinK and igoychev
