### ISSUE TITLE
Bug - Hero image is missing on opera browser

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#331]
![image](https://user-images.githubusercontent.com/75036745/127402726-2784df14-da0a-4513-8f3b-d57d1734e5ed.png)
Hero image is missing on home page. Test done on opera

**Comment by ani-kalpachka** [comment]
I am not able to reproduce this issue on Opera browser:

![image](https://user-images.githubusercontent.com/14351733/127513051-e91999c4-57bb-4d10-b35a-c27fad7d3bb9.png)

Could it be fixed?

**Comment by swolf86** [comment]
I don't know what is it, It is just my personal PC others are fine

Opera 
Version:77.0.4054.277
Update stream:Stable
System:Windows 10 64-bit

**Comment by imilchev** [comment]
Could it be your ad blocker that is blocking it? Can you check in the console of the browser what's the error when retrieving the image? Otherwise close the ticket

**Comment by swolf86** [comment]
Nope not ad blocker. Another extensions was the issue (day/night reading extension)
