### ISSUE TITLE
[Feature] Frontend: As an Operator, I can check individual campaign details and update the Status

### ISSUE THREAD

**Issue by stann1** [podkrepi-bg/frontend#332]
Clicking on the campaign link in List view opens a detailed view. Visible campaign details are the same from [here](https://github.com/podkrepi-bg/frontend/issues/299)

with added fields:
- documents download (button)
- comments (list), with author and date, sorted in descending order by date

Acceptance criteria:
1. I can download all attached documents and can add a comment
2. I can also update the status of the campaign from the initial **PendingValidation** to **Approved** or **Rejected**
All available statuses are described [here](https://docs.google.com/spreadsheets/d/1aBAZr25W_YWoQsMF-OBN4Zf2d1E9b095_SjFn7vIdiE)
2.1 In case of Approval, the Payment module needs to be notified, so that payments are open for this campaign
2.2 In case of Rejection, I need to provide a **mandatory** comment about the rejection reason
3. If the campaign was in **Active** state, I can mark it as **Completed**. 
3.1 This should disable further donations on the campaign, so the Payments module needs to be notified

**Comment by ani-kalpachka** [comment]
Currently available in Admin view.
