### ISSUE TITLE
[Bug] Frontend - Scroll button on Homepage does not work

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/frontend#334]
**Describe the bug**
The scroll arrow button on Homepage on hero slider does not work on click.

**To Reproduce**
1. Go to Homepage.
2. Click on the arrow down button.
3. See error - clicking on the button does not scroll to the next section.

**Expected behavior**
Clicking on the button should scroll to the next section.

**Comment by kachar** [comment]
Closed by https://github.com/podkrepi-bg/frontend/pull/335
