### ISSUE TITLE
Change image on home and about the project page - BG [Bug]

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#337]
Ще може ли да замениm Бг картинките в начална и за проекта страници
има повторение на думата "на"  в стъпка "отчитане на разходи"

Нови картинки 
https://drive.google.com/file/d/1rc8AA1PdNmefnbTb4TgxY7c5Hd9lUch5/view?usp=sharing
https://drive.google.com/file/d/1adMg-87HSRH7OLRrLHF5t2qpV95VUZGd/view?usp=sharing

**Comment by ani-kalpachka** [comment]
PR created: https://github.com/podkrepi-bg/frontend/pull/338
