### ISSUE TITLE
Add accessibility widget [Feature]

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#339]
Please add if possible accessibility code to the website.
More about the code 
https://userway.org/code/

example of used accessibility menu https://rndc.bg/en/homepage-english/

registration email : 

The JS Embed Code for Your UserWay Accessibility Widget
basic script:

```html
<script>(function(d){var s = d.createElement("script");s.setAttribute("data-account", "BViSR5zmYb");s.setAttribute("src", "https://cdn.userway.org/widget.js");(d.body || d.head).appendChild(s);})(document)</script><noscript>Please ensure Javascript is enabled for purposes of <a href="https://userway.org">website accessibility</a></noscript>
```

Advanced script:

```html
<script>
      (function(d){
         var s = d.createElement("script");
         /* uncomment the following line to override default position*/
         /* s.setAttribute("data-position", 1);*/
         /* uncomment the following line to override default size (values: small, large)*/
         /* s.setAttribute("data-size", "large");*/
         /* uncomment the following line to override default language (e.g., fr, de, es, he, nl, etc.)*/
         /* s.setAttribute("data-language", "null");*/
         /* uncomment the following line to override color set via widget (e.g., #053f67)*/
         /* s.setAttribute("data-color", "#2d68ff");*/
         /* uncomment the following line to override type set via widget (1=person, 2=chair, 3=eye, 4=text)*/
         /* s.setAttribute("data-type", "1");*/
         /* s.setAttribute("data-statement_text:", "Our Accessibility Statement");*/
         /* s.setAttribute("data-statement_url", "http://www.example.com/accessibility";*/
         /* uncomment the following line to override support on mobile devices*/
         /* s.setAttribute("data-mobile", true);*/
         /* uncomment the following line to set custom trigger action for accessibility menu*/
         /* s.setAttribute("data-trigger", "triggerId")*/
         s.setAttribute("data-account", "BViSR5zmYb");
         s.setAttribute("src", "https://cdn.userway.org/widget.js");
         (d.body || d.head).appendChild(s);})(document)
 </script>
<noscript>
Please ensure Javascript is enabled for purposes of 
<a href="https://userway.org">website accessibility</a>
</noscript>
```

White label 

```html
<script>(function(d){var s = d.createElement("script");s.setAttribute("data-account", "BViSR5zmYb");s.setAttribute("src", "https://accessibilityserver.org/widget.js");(d.body || d.head).appendChild(s);})(document)</script><noscript>Please ensure Javascript is enabled for purposes of <a href="https://accessibilityserver.org">website accessibility</a></noscript>
```

After installing the widget on your site use the credentials below to sign into your widget to customize its appearance.

To access your account, please sign in from manage.userway.org or click the "Manage
link from your widget footer (only from the widget that is installed on your website) to access the widget management area.

Login user  name: info@podkrepi.bg
Pass: send as  email on info@

**Comment by kachar** [comment]
Do we still need this?

**Comment by swolf86** [comment]
Yes why not - it improves accessibility

**Comment by kachar** [comment]
@swolf86 Let's add this via GTM instead of code modifications.

**Comment by swolf86** [comment]
Not sure what is GTM, but I guess the method of delivery is not so important

**Comment by kachar** [comment]
@swolf86 GTM is Google Tag Manager which allows us to add runtime snippets to the production website without deployment.

We're using it for google analytics, heatmap.com and webtrends right now.

Please provide credentials for userway in Discord so we can set it up

**Comment by kachar** [comment]
It's added to the website

Top right corner as instructed by @swolf86 

Desktop|Mobile
---|---
![image](https://user-images.githubusercontent.com/893608/206515983-675713db-38b1-49ad-aa1b-23e8f4f28ba2.png)|![image](https://user-images.githubusercontent.com/893608/206516101-fcafc8a8-3828-4ab4-80dd-711d0fe3dfe3.png)
