### ISSUE TITLE
[Bug] There is no password requirements for registration, you can register with 1 symbol

### ISSUE THREAD

**Issue by rkgeorgiev** [podkrepi-bg/frontend#349]
**Describe the bug**
There is no password requirements for registration, you can register with 1 symbol

**To Reproduce**

1. Go to 'podkrepi.bg/register'
2. Fill up all the fields and on Password set 1 symbol
 - You can register with just 1 symbol

**Comment by kachar** [comment]
@rkgeorgiev The requirement should be tested at
