### ISSUE TITLE
[Bug] The user is able to create an account with invalid e-mail adress (Dev environment)

### ISSUE THREAD

**Issue by PetiaTaneva** [podkrepi-bg/frontend#350]
**Bug Description:** 
When making a registration, the user is able to create an account by using an invalid e-mail format.

**Dev environment**

1. Go to [https://dev.podkrepi.bg/register](URL)
2. Click on the 'Регистрация' button 
3. Enter a random first name: Petia
4. Enter a random last name: Taneva
5. Enter an invalid e-mail format: nibelunga19@gmailcom
6. Enter the password: test123
7. Confirm the password: test123
8. Click on the 'Register' button

**Expected behavior**
When using an invalid e-mail format for creating an account, an error message should be displayed. The user should not be able to make a successful registration.

**Screenshots**
![invalid e-mail format](https://user-images.githubusercontent.com/88198885/132330774-a9513ec2-a28a-4f07-9a8d-1db1307044ef.png)

**Desktop device:**

- OS: Windows 10 Pro
- Browser: Chrome
- Version: 92.0.4515.159 (Official Build) (64-bit)

**Smartphone device:**

- Device: Huawei POT-L21
- OS: Android 10
- Browser: Chrome
- Version: 92.0.4515.166

**Additional context**
The problem is occurring only on the desktop device!!!

**Comment by StanislavSt** [comment]
When this is done https://github.com/podkrepi-bg/frontend/issues/371, we will have control over the forms and can implement our own validation. Currently I don't think this can be fixed.

**Comment by igoychev** [comment]
To solve this, we have enabled mail verification from keycloak side. Now before enabling the account the system will send a verification link to the mail, so no invalid accounts will be created.
