### ISSUE TITLE
[Feature] Create beneficiery and coordinator inputs during campaign creation

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#362]
At the moment the campaign creation form requires user to input UUID for beneficiary and coordinator persons. This is not user friendly at all so we need to change it

Steps to be done:

- [x] #364
- [x] #366
- [x] #363
- [ ] #365
- [ ] #433

![image](https://user-images.githubusercontent.com/893608/134007854-e3eb2ae2-dc73-44b4-8767-2927296a8d03.png)

**Comment by igoychev** [comment]
closing as this is working now
