### ISSUE TITLE
[Log in] Successful login with WRONG CREDENTIALS 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#370]
**Describe the bug**
Successful login with wrong credentials in podkrepi.bg

Reproducibility: 3 of 3
**To Reproduce**

1. Go to https://podkrepi.bg/
2. Click on "Включи се" button
3. Choose "Доброволец"
4. Click on "Напред" button
5. Choose "QA"
6. Click on "Напред" button
7. Enter wrong credentials:
 - име: Phitef
 - Фамилия: Aqvcbn
 - Имейл: Pelibdbd@abv.bg
 - телефонен номер: 908765430
 8. Check all checkboxes that you agree
 9. Click on "Изпрати" button

**Expected behavior**
A message that the email is wrong or non-existing, also a message for the wrong format of the telephone number.

Actual result: 
Confirmation for successful registration.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10, version 21H1
- Browser - Chrome 
- Version - 94.0.4646.61, 64 bit

**Smartphone (please complete the following information):**

- Device: Huawei, Y7, 2019
- OS: Android 8.1.0
- Browser - Google Chrome
- Version -

**Comment by kachar** [comment]
Hi @Polina1985 

> Enter wrong credentials:
> име: Phitef
> Фамилия: Aqvcbn
> Имейл: Pelibdbd@abv.bg
> телефонен номер: 908765430

These inputs seem to be a valid email and international phone number, at least if we're discussing the format of the data.

- The email validation info can be found at https://github.com/typestack/class-validator/blob/2e9a2d88259110de752d26127f9a554d1600a584/src/decorator/string/IsEmail.ts#L9-L10
- The phone number validation info can be found at https://github.com/typestack/class-validator/blob/2e9a2d88259110de752d26127f9a554d1600a584/src/decorator/string/IsPhoneNumber.ts#L8-L13

The data can be found in the DB
![image](https://user-images.githubusercontent.com/893608/136045007-d806d397-987f-45d2-903a-fb4f7a903e17.png)


Some action points that can be done:

- make the email field lowercase

**Comment by kachar** [comment]
About the title of the issue stating "Successful login with WRONG CREDENTIALS" I find it incorrect as during the given process user is submitting a contact form and they are not being registered in the platform (which happens at /register)

**Comment by kachar** [comment]
Closing this issue as outdated, feel free to reopen if there's an update
