### ISSUE TITLE
[Bug] Campaign form requires user to input UUID for beneficiary and coordinator

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#383]
**Describe the bug**
Problem with creation of a Campaign from the environment - dev.podkrepi.bg/campaign

Device: Huawei Y9, 2019

**To Reproduce**
Reproducability 2 of 2

1. Go to 'dev.podkrepi.bg/campaign
2. Try to fill out the rows with the necessary info 
3. Scroll down to Beneficiary
4. Try to input name/ names of the Benediciary
4. Try to input info about Coordinator

**Expected behavior**
Successful creation of a Campaign

Actual
No availability of Campaign creation. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [huawei Y9, 2019]
- OS: [android 8.1]
- Browser [Google chrome]
- Version ]

**Additional context**

PRIORITY BUG

**Comment by ani-kalpachka** [comment]
This issue seems to be deprecated because currently we do not have the fields for beneficiary and coordinator implemented on Create Campaign form. 
@kachar could you please take a look and confirm if we can close it?
