### ISSUE TITLE
[Feature] Integrate file uploader in campaigns flow

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#387]
**Is your feature request related to a problem? Please describe.**

We need to upload and edit (crop, rotate) photos during campaign creation.

Support multiple sources (local, google drive, google photos, Facebook)

**Describe the solution you'd like**

- [x] Integrate https://uppy.io + own storage
- [ ] Integrate https://uppy.io + https://transloadit.com/ on a free plan
- [ ] Integrate https://www.filestack.com/ on a free plan

**Describe alternatives you've considered**

- Upload files to own storage via https://uppy.io (https://github.com/transloadit/uppy)
- Implement a photo editor for the uploaded files

**Comment by kachar** [comment]
@vann4oto98 Please share the approach you've taken and let us know if there are questions or obstacles on the way

**Comment by vann4oto98** [comment]
@kachar I think that Transloadid still needs an external storage provider or tus.io server, so our only completely free, serverless option is Filestack. Unfortunately, Filestack's free plan has certain worrying limitations to consider: 
 - 1 GB Bandwith (viewing and downloading)
 - Maximum of 500 uploads (monthly?) with 20 MB file size limit.
 - 1 GB Storage
 
 For that reason, I consider an alternative using Uppy + AWS S3 as it potentially is the cheapest, non-limiting variant.
 
 AWS S3's pricing:
 - Storage $0.0245 per GB
 - Per 1000 request (GET) $0.00043, (PUT) $0.0054
 
I am not sure which approach to take and I am open to suggestions. 
Using a paid service is probably a matter of organizational/architectural discussion, for that reason I can start implementing the free Filestack solution.

**Comment by kachar** [comment]
So far we've got our own storage setup set up in the Kubernetes cluster. We're using Rook / Ceph block storage https://github.com/rook/rook/blob/master/Documentation/ceph-block.md which is with compatible S3 interface.

We've also got an AWS account set up for mailing, so we can use AWS S3 service if we need to.

Anyhow at the moment, the limits of Filestack will be more than enough to get us started. We're planning to start with 3 campaigns, so we don't need more than 1gb of storage for sure. The problem here is that Filestack does not support S3 storage on the free plan, so I'm leaning towards Uppy + S3 storage

I'm adding @imilchev and @igoychev to follow up here.

**Comment by imilchev** [comment]
Since we already have a solution that is hosted on our cluster and provides an S3 interface, why are we even considering other services at the moment?

**Comment by kachar** [comment]
The aim here is to find a frontend solution that works well with our internal S3 storage.

How can we reach the S3 endpoints of our storage? It's a bit unclear to me

**Comment by kachar** [comment]
@vann4oto98 We/ve managed to set up the Ceph Object storage thanks to @imilchev 

Now we've got the following endpoints 

- https://cdn.podkrepi.bg/
- https://cdn-dev.podkrepi.bg/

Secrets will be given in Discord or another communication channel
