### ISSUE TITLE
[Feature] Create FAQ page

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#400]
**Is your feature request related to a problem? Please describe.**
Many people request the same information from us regularly

**Describe the solution you'd like**
Create a `/faq` page that will help them gather the data

**Additional context**

- [ ] faq answer might be expandable
- [ ] the page should have direct link to specific heading (either full URL path or # hash based)
- [ ] every heading should have the option to be copied
- [ ] only bulgarian language should be supported at this point
- [ ] ssr support for better SEO
- [ ] link to `/faq` page should be added to `routes.ts`
- [ ] links in nav menu and mobile nav menu should point to the new page

**Comment by kachar** [comment]
@vann4oto98 The content for the page can be found at https://docs.google.com/document/d/1jGKQwlKlR0Bj91MNySVNtLxFk295Z6FephqvsV02__4/edit?usp=sharing

**Comment by kachar** [comment]
@vann4oto98 Do you have any updates on this issue? 

If you're not having the time to contribute maybe you can unassign it so somebody else can join

**Comment by vann4oto98** [comment]
@kachar Sorry, I had a really busy December... 

I will continue my work on this issue and I will be ready by the end of the week.
