### ISSUE TITLE
Смяна на графики

### ISSUE THREAD

**Issue by marianacat** [podkrepi-bg/frontend#406]
**Моля, да се смени графиката на  началната страница на инфо сайта.** 
https://podkrepi.bg/

**Графиките се намират тук:**
https://drive.google.com/drive/folders/1IHpUj-JKRpAZbzJn2clyQBNdKy7rjSQf?usp=sharing

- [ ] EN web
- [ ] EN mobile
- [ ] BG web
- [ ] BG mobile

 Благодаря!

**Comment by ani-kalpachka** [comment]
PR created: https://github.com/podkrepi-bg/frontend/pull/409
