### ISSUE TITLE
[EPIC][UserProfile] Create User Profile Page

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#438]
Currently the user profile page is text only: https://dev.podkrepi.bg/profile. 

We need to apply the design for the User Profile page from here: 
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=7413%3A22511

And implement the Tabs 

- [x] #439
- [x] #440
- [ ] #441

**Comment by ani-kalpachka** [comment]
Closing the issue since all the described requirements are implemented.
