### ISSUE TITLE
Personal Info Tab

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#440]
Create a personal info tab as per the design here https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=7413%3A22511

The data for the user profile can be loaded from the backend API by executing a request to:
 https://dev.podkrepi.bg/api/account/me
in the same way as executed here: https://dev.podkrepi.bg/profile

**Comment by Georgiev86** [comment]
[Bug] No adjustment possible in User Profile. Unable to edit Username, Password and Data in Profile .

**Comment by Georgiev86** [comment]
https://user-images.githubusercontent.com/97630899/158014586-4956cc55-a622-41ad-aa65-a5cdca984394.mp4

**Comment by kachar** [comment]
@Georgiev86 Please create a dedicated issue so this bug you found gets fixed.
