### ISSUE TITLE
[UserProfile]Donation Certificates(Docs for download)

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#441]
This task is created only for completeness, but is low priority. Implementation is needed after Campaign Creation, Donation and Donation Tracking is implemented.

The design is here:
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=7597%3A22549

**Comment by ani-kalpachka** [comment]
The task is completed. Closing the ticket.
