### ISSUE TITLE
[Campaign] Implement Donation History for Campaign

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#442]
On the Campaign Details Page create a history of donated amounts. 

See the Figma Design here: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=6874%3A22174

Donations should be loaded via the backend API as per this issue https://github.com/podkrepi-bg/api/issues/67

**Comment by dimitur2204** [comment]
Isn't that done or am I not understanding the issue?

Look here
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/61479393/163349393-b6235d3e-c191-413e-adcc-5e145cf209ea.png">

**Comment by dimitur2204** [comment]
Should we limit the amount of  donations that we show. Maybe the latest 5-10, because if there are a lot the UI wouldn't look good.
