### ISSUE TITLE
[Donation] Implement field for custom amount donation

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#445]
Currently the UI allows only pre-selected amounts to be donated. We need to extend this with a field where the user can enter his own desired amount for donation.

**Comment by ani-kalpachka** [comment]
Closing the issue since now we have this option:

![image](https://user-images.githubusercontent.com/14351733/186175283-e8be4466-080a-4a04-9752-76bbc4b295f5.png)
