### ISSUE TITLE
[Bug] FAQ page/ Links in FAQ page - "not implemented"

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#446]
Reproducability:always on mobile device Android, and Desktop

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Click on Menu "Дарителство" 
3. SCROLL DOWN TO "Често задавани въпроси" 
4. Select random question 

**Expected behavior**
The user must read smoothly the text written and to open the links implemented. After that he/ she must be redirected to a new page. 

Actual: No redirection to relevant information. Not implemented links

**Screenshots**
![Screenshot_20220121-163324.jpg](https://user-images.githubusercontent.com/77857494/150544996-cd816570-ffcd-494e-96cb-dbe85421afe7.jpg)![IMG_20220121_163119.jpg](https://user-images.githubusercontent.com/77857494/150544931-cb5a0474-c709-459a-993a-c3b6c990f202.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser - Chrome 
- Version - 97.0.4692.99 (Official build) (64 bit) 

**Smartphone (please complete the following information):**
Huawei Y7, 2019

- Device: Huawei Y7, 2019
- OS: 
- Browser Chrome
-![IMG_20220121_163119.jpg](https://user-images.githubusercontent.com/77857494/150544379-1ea64737-dbb5-4615-a347-55aacefcf7fd.jpg)

**Additional context**

**Comment by igoychev** [comment]
For the FAQ question "Как се издържа сдружението", the link to Monthly Donations Reports (Отчети) should open a page podkrepi.bg/npo/reports. Let's create a sub-menu item under The Project menu that leads there too. 
The page reporst, should show list of donations and expenses of the NPO Podkrepi.bg
