### ISSUE TITLE
[Bug]Home page/ My profile page/ Valid credentials/ My Profile UI - not user friendly 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#453]
**To Reproduce**

1. Go to dev.podkrepi.bg
2. Click on on "my profile" icon on the menu bar
3. Enter valid credentials (already registered  user)
4. There is new page opened with My profile

**Expected behavior**
To see user-friendly UI/UX that is easy to understand and use.

Actual result:
Jason format info with info from Keykloak

**Desktop (please complete the following information):**

- OS:  Windows 7 home premium
-google chrome (32 bites)
- Version - 97.0.4692.99

**Smartphone (please complete the following information):**

- Device: Samsung a22 5g[]

**Comment by Polina1985** [comment]
![Uploading u2{290cd5c} (7890cc3c-51e3-41e7-88e1-6bc3e07841ac id=0x7f0a03a0 tag=BaseCommentFragment) …]()

**Comment by dplamenov** [comment]
@Polina1985 I thinks this issue can be closed. 
![Screenshot at Apr 14 17-18-05](https://user-images.githubusercontent.com/30602242/163409945-922ee3bf-25b6-40d3-b15b-09e6e22ea6ab.png)

**Comment by kachar** [comment]
@dplamenov Thanks for letting us know, indeed it can be closed now
