### ISSUE TITLE
[Company] Implement dashboard layout with datagrid for Company entity

### ISSUE THREAD

**Issue by TodorBelchev** [podkrepi-bg/frontend#471]
The task is to create a brand new Layout which should contain the following components inside of itself.

 1.Appbar
- [ ] hamburger menu
- [ ] logo
- [ ] search input field
- [ ] profile button(icon) to the most right side with a dropdown menu with few options

2.Drawer
- [ ] menu items
- [ ] submenu items when clicked on main menu items
- [ ] should keep open state across pages

3.Footer - should be part of the whole layout

4.Datagrid
- [ ] Should have a title above it to say what we display in it
- [ ] Should display company entity loaded from the back-end
- [ ] Should have a + button/icon at the top which leads to a new page displaying the create form
- [ ] Should have a delete button/icon which opens a confirmation modal & deletes all selected items by the checkbox column 
- [ ] checkbox column
- [ ] Should have a last column with 3 icons aligned to the right :
    - [ ] view icon (opens a modal that shows all the values of the entity clicked)
    - [ ] edit icon (opens a new page with form in which you can edit all the form values, also on this form we should have 2 buttons -save/cancel)
    - [ ] delete icon (a normal confirmation pop-up asking "Are you sure" and 2 answers yes/no)

5.Notifications
- [ ] Should show success/error notification after create/edit/delete

**Comment by TodorBelchev** [comment]
> Could you please add a screenshot

![image](https://user-images.githubusercontent.com/71307782/153835059-43ab2705-afed-499b-92b9-ce9d4da78c07.png)
![image](https://user-images.githubusercontent.com/71307782/153835118-753c5029-2c5a-4e34-b764-cf5f5ab36aba.png)
![image](https://user-images.githubusercontent.com/71307782/153835182-1c1ec168-4795-4d45-b8d4-01a6bbab3750.png)
![image](https://user-images.githubusercontent.com/71307782/153835229-a93ca557-5a6e-43f9-82c8-bcff4a9c998d.png)
![image](https://user-images.githubusercontent.com/71307782/153835341-5db34487-dc44-421f-a859-e713f9ee205e.png)

**Comment by kachar** [comment]
@podkrepi-bg/softuni-bootcamp Feel free to develop this entity in the admin
