### ISSUE TITLE
[City] Create admin panel for city entity 

### ISSUE THREAD

**Issue by Yakimov1337** [podkrepi-bg/frontend#474]
- [x] Create CRUD functionality based on #451

**Comment by Polina1985** [comment]
It is ok. I have tested. The admin can +new city, can delete.

I am returning the task to "To Do" to correct the name "Добави нов Града" to "Добави нов град" in the Form.
@Yakimov1337 

Please, turn back the ticket in QA  after it is ready :)

**Comment by Polina1985** [comment]
![Uploading InkedТекст на заглавието - да се поправи_LI.jpg…]()

**Comment by Polina1985** [comment]
![InkedТекст на заглавието - да се поправи_LI](https://user-images.githubusercontent.com/77857494/156732469-c02cda42-7e7e-4c52-a6cc-8e9f214eb0c3.jpg)
