### ISSUE TITLE
[Document] Create admin dashboard panel

### ISSUE THREAD

**Issue by stilian-nikolaev** [podkrepi-bg/frontend#475]
Creating dashboard panel for the "bank accounts" model according to Bootcamp/first-layout [#451](https://github.com/podkrepi-bg/frontend/issues/451) standarts.

**Comment by Polina1985** [comment]
Can you please, add a screen shot or picture for more clarity?

**Comment by Polina1985** [comment]
I maybe need to upload manually a Document. 
Maybe I should register a Campaign/ or register as a user, then I have to upload a document and after that, as an administrator, I should see the Documents in the Administrative email and I should be able to manipulate the data with it.
Could you please give me Discord account to contact you there?

**Comment by kachar** [comment]
@Polina1985 The documents section still does not support handling actual documents, only their descriptions which are stored in the database.

Not much functionality yet

**Comment by Polina1985** [comment]
Yes,  I have create a Document and it is possible to ADD a Document to the Administrative Panel.

I would, however (for the usability of the Panel) propose the following:

In the "Добави нов документ" Form:

**FIELD:  "Вид"** not to be restricted only to - invoice, receipt, medical_record, other... and not to be only in English
**FIELD: "Линк**" - options to be uploaded from PC or Google Drive, etc.
@kachar
