### ISSUE TITLE
Implement a layout for Coordinator entity

### ISSUE THREAD

**Issue by dplamenov** [podkrepi-bg/frontend#478]
Implement a layout for Coordinator entity

**Comment by TeDy-A-K** [comment]
Could you please add screenshot. And some short description so it will be easier to QA

**Comment by Polina1985** [comment]
When I logged in as an administrator I could:
- see the List of all Coordinators
- delete a Coordinator

**But I could not:**
- search in the **field "Търси'** in the left upper corner 
- Add a new Coordinator (manually) - neither via email, nor using name
- Manipulate data through - **"share" button**
- save the list of Coordinators in my PC **("save" icon")**
- print the List of Coordinators ("print icon")

Please, fix the abovementioned and return for retesting.
![Поле Търси - не работи](https://user-images.githubusercontent.com/77857494/156007057-9905745b-81dd-4bd4-a50c-8e926ac1ea78.jpg)
![възникна грешка 1](https://user-images.githubusercontent.com/77857494/156007091-89f66a5d-a41b-4a6d-9f76-f240e240211d.png)
![когато се натисне бутон сподели](https://user-images.githubusercontent.com/77857494/156007095-1c9dc3cb-fdfe-44dd-a1c0-49de7f9a89a2.png)

**Comment by Polina1985** [comment]
Hello, 

Have you fixed the problems above? Should I retest or still not? @

**Comment by Polina1985** [comment]
Still staying not fixed in dev.podkrepi.bg --> admin panel--> Добави нов координатор

**Comment by Georgiev86** [comment]
https://user-images.githubusercontent.com/97630899/156937012-55436a24-c562-4baa-a5eb-f995bf2b9ca1.mp4

**Comment by dplamenov** [comment]
> default.mp4

The problem is that this person has already been added as a coordinator. This problem will be fixed #584

**Comment by kachar** [comment]
The last PR has been merged and deployed to staging environment

**Comment by Polina1985** [comment]
Hello,
@kachar and @dplamenov I would like to say that I have tested the admin panel after the last PR, but no results yet:

1. Still no possibility to ADD A NEW COORDINATOR, not existing one from the list.
2. All the buttons from the ATHENA in the right corner are not working (преглед, delete, save, print, share).

Please fix and return for testing.
