### ISSUE TITLE
Campaign page/ UI-UX elements are missing according to UI mockup (Design)

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#489]
**To Reproduce**

1. Go to dev.podkrepi.bg
2. Navigate to main menu "Дарителство"
3. Scroll down to 'Кампании.'
4. Choose random Кампания
5.Select button "Вижте повече"
6.You should be successfully redirected to the new Campaign page

**Expected behavior**
All UX elements from the Design UI should be according to the Design mock ups.

**Actual result:** 
Campaign page/ UI-UX elements are missing according to UI mockup (Design):
1. Missing Subheader
2. Slider for sums (too large according to UI mocк ups from Design)
3. List of donors and donation sums missing (under the "Сподели" button)
4. Missing image carousel (under the Description of the Campaign)
5. Missing section "Последни новини"
6. Missing section "Коментари"

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows
- Browser  chrome
- Version - Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by Polina1985** [comment]
[
![Campaign page_Design mock up_1](https://user-images.githubusercontent.com/77857494/153866094-fbc5bf03-dd7f-46bd-970d-757093970d11.png)
![Campaign page_Design_mock up_2](https://user-images.githubusercontent.com/77857494/153866099-df1230ad-83b2-4d00-be2f-66655364f762.png)
![Campaign page_Design_mock up_3](https://user-images.githubusercontent.com/77857494/153866101-58a53636-6252-4707-b324-b6b8113535b6.png)
](url)

**Comment by Polina1985** [comment]
@ani-kalpachka 
@kachar

**Comment by kachar** [comment]
If any of the @podkrepi-bg/softuni-bootcamp  team wanna try solving this issue it would be great
