### ISSUE TITLE
Campaign page/ Functional testing/ Button "Сподели" not active and no redirection 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#490]
**Describe the bug**
**Button "Сподели" in Campaign page not working**

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Navigate to main menu "Дарителство"
3. Scroll down to 'Кампании"
4. Choose a random Campaign from the list of Campaigns
5. Select "Подкрепете сега" button
6. Successfully redirected to the new page

**Expected behavior**
Working "Сподели" button in the Campaign page.  Opportunity for the user to share the Campaign through 
-Facebook
-linkedin
-Instagram
other social networks...

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser: Chrome 
- Version: Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by ani-kalpachka** [comment]
The sharing functionality is currently working for all social media options and the issue in no longer valid.
