### ISSUE TITLE
[Bug] Minor - podkrepi.bg/support buttton "Копирай" should be blue

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#494]
**Describe the bug**
The button "Копирай"  on  page: podkrepi.bg/support is gray not blue

**To Reproduce**

1. Go to podkrepi.bg/support

**Expected behavior**
The button "Копирай" should  be blue, because it is active

**Screenshots**
Screenshots added

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge and Chrome
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
![Bug_UX_CopiraiButona_Sin](https://user-images.githubusercontent.com/99661273/154029138-2e664f12-f10d-4f86-9863-9284488ff416.JPG)

**Comment by ani-kalpachka** [comment]
Hello, @TeDy-A-K!

Currently the color of the Copy button is blue when it is clicked/active and is grey when it is not.
I think the behavior is correct. Could you please recheck and confirm?

**Comment by TeDy-A-K** [comment]
@ani-kalpachka, alextomov comfirm that the defect is valid, and the button should be blue
