### ISSUE TITLE
[Bug] Minor - podkrepi.bg/support checkbox validation under "Включете се в организацията като" and the sequential pages appears before the "Напред" button is used

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#495]
**Describe the bug**
When I check and then uncheck a checkbox  from mandatory group, a validation message "Моля, изберете си роля" appears

**To Reproduce**

1. Go to podkrepi.bg/support
2. Click on "Дарител" checkbox
3. Then uncheck the same checkbox
4. Validation error appears  before the "Напред" button is used

**Expected behavior**
I expect the validation is triggered after "Напред" button is used. This bug was observed all over the sequential pages

**Screenshots**
![Bug_UXCheckBox_Validaciq](https://user-images.githubusercontent.com/99661273/154034385-1f1b1067-ab23-46f4-8fe3-344e5fd7a17d.JPG)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge 
Version Version 98.0.1108.50 (Official build) (64-bit)

**Additional context**
Please double check that the behavior is not by design with front end expert before fixing

**Comment by kachar** [comment]
This behavior is by design, validation is triggered on `touch` of the checkbox fields or on Next page button
