### ISSUE TITLE
[Bug] Major - podkrepi.bg/support/"Как да се свържем с вас"  field "Допълнителен коментар" accepts javascript injection

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#498]
**Describe the bug**
User is able to type unwanted symbols like "javascript:alert("Hello!");" in the "Допълнителен коментар" field. The server blocks the request so it prevents the security issue, but still client site validation is needed. Also it is not clear for the user if he had registered successfully ( see screenshoots)

**To Reproduce**

1. Go to podkrepi.bg/support/"Как да се свържем с вас"
2. Fill all the fields appropriately except "Допълнителен коментар"
3. Fill "javascript:alert("Hello!");" in the  "Допълнителен коментар" ( no validation error is shown)
4. Click "Изпрати" button

**Expected behavior**
There is validation on the "Допълнителен коментар" field

**Screenshots**
![Bug_KakDaSeSyrjemSVas_2](https://user-images.githubusercontent.com/99661273/154054806-24336e6a-916d-4109-8591-8c3b1c93404e.jpg)
![Bug_KakDaSeSyrjemSVas_1](https://user-images.githubusercontent.com/99661273/154054812-74ea8b76-32f9-4cc6-a165-f5be70c629cc.jpg)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge 
Version Version 98.0.1108.50 (Official build) (64-bit)

**Additional context**

**Comment by dimitur2204** [comment]
I don't know if that was fixed, but it currently does not run the javascript it sends the message as javascript:alert("hello!"); which I don't think is a problem in any way!
