### ISSUE TITLE
[Bug] Minor - podkrepi.bg/support/"В каква роля искате да ни подкрепите?" buttons are moving up and down after validation for required field is triggered

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#504]
**Describe the bug**
 At page "В каква роля искате да ни подкрепите?" if a user check and then uncheck a checkbox, so that the validation for required field is triggered. It is observed that the buttons "Напред"  and "Назад" are moving up and down

**To Reproduce**

1. Go to podkrepi.bg/support/"В каква роля искате да ни подкрепите?" page
2. Click on one checkbox and then uncheck it again
3. Observe that the buttons "Напред"  and "Назад" are moving up and down when the validation is trigered

**Expected behavior**
The buttons stay on the same position no matter if there is validation message or not

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154231229-6a7e45f9-f41e-4388-a158-4e53d69b8829.png)
![image](https://user-images.githubusercontent.com/99661273/154231320-80dbb3f2-22f5-4f41-8e4d-21a024e5f2b9.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Additional context**

**Comment by kachar** [comment]
Doesn't seem too bothering. Otherwise, it would have big empty spaces for each hidden error text.

We might add animation but it looks like a waste of time at this point. If issue is brought up by more people we'll find a solution.
