### ISSUE TITLE
[Bug] Critical - POST Request on page podkrepi.bg/support/"Как да се свържем с вас" fails on Chrom and Firefox

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#505]
**Describe the bug**
POST Request  with valid data on page podkrepi.bg/support/"Как да се свържем с вас" fails on Chrome and Firefox. On Edge it si not  reporduced

**To Reproduce**

1. Go to page podkrepi.bg/support/"Как да се свържем с вас"
2. Enter valid data in all fields. ( see screenshoots)
3. Click "Изпрати"
4. See  the error on js console and on the user screen (( see screenshoots)

**Expected behavior**
The flow completes successfully,without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154234147-aab79da9-191f-4272-a4b0-69a268f6f8e4.png) - Test Data
![image](https://user-images.githubusercontent.com/99661273/154234204-1f879dd0-dab0-4241-b0d0-dfb18dbfb8c0.png) - Error
![image](https://user-images.githubusercontent.com/99661273/154234494-aa10789d-2194-4257-8426-42499f28936e.png) - Consol Error 1
![image](https://user-images.githubusercontent.com/99661273/154234642-047b88f2-0b4a-4625-9e68-bab90e87ee9d.png) - Consol Error 2

**Desktop (please complete the following information):**

- OS: Winows 10
- Browser Firefox and Chrom . Not reproduced on Edge
- Version Edge - 91.6.0esr (64-bit) /  Chrom 98.0.4758.102 (Official Build) (64-bit)

**Additional context**
I have manage to reporduce it and on chome  version : 98.0.4758.102 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/99661273/154235295-1c3acb42-9c26-4bd2-8f98-40956fdb09db.png)

**Comment by TeDy-A-K** [comment]
XHRPOSThttps://dev.podkrepi.bg/undefined/api/support/create-request
[HTTP/3 404 Not Found 43ms]
{"person":{"email":"asd@ds.bg","firstName":"aaa","lastName":"aaa","phone":"123456789","address":"","comment":"asd","terms":true,"gdpr":true,"newsletter":false},"supportData":{"roles":{"benefactor":false,"partner":false,"associationMember":false,"company":false,"volunteer":true},"benefactor":{"campaignBenefactor":false,"platformBenefactor":false},"partner":{"npo":false,"bussiness":false,"other":false,"otherText":""},"volunteer":{"backend":false,"frontend":false,"marketing":false,"designer":false,"projectManager":true,"devOps":false,"security":false,"financesAndAccounts":false,"lawyer":false,"qa":false},"associationMember":{"isMember":true},"company":{"sponsor":false,"volunteer":false,"other":false,"otherText":""}}}

**Comment by kachar** [comment]
Looks like the environment variables form the container are not being passed down to the `next` process

Steps to verify if it's working or not:

1. Open Console
2. Enter `__NEXT_DATA__.runtimeConfig`
3. Check if `API_URL` is part of the response
![image](https://user-images.githubusercontent.com/893608/155858272-1028d505-32f5-4e0a-b8e6-64f24d016fcb.png)


I've checked the kubernetes container and it seems that it's working properly and it has the environment vars inside of it:

![image](https://user-images.githubusercontent.com/893608/155858320-e58259dd-3f5a-44bf-bc87-99bc9471fd3b.png)

**Comment by kachar** [comment]
Should have been fixed now

I've deployed the tag `v0.9.8` to dev.podkrepi.bg and then returned `master` build there.

That seems to have fixed the problem, the actual problem remains unclear.

@podkrepi-bg/qa please verify if this and other similar issues (contact form) are working correctly now

**Comment by TeDy-A-K** [comment]
Verified
