### ISSUE TITLE
[Bug] Minor - podkrepi.bg/support/"Как да се свържем с вас" all the fields and buttons on the form are moving up and down when validation message appears

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#506]
**Describe the bug**
At page podkrepi.bg/support/"Как да се свържем с вас" all the fields and buttons on the form are moving up and down when validation message appears. This makes it uncomfortable for the user to read, and looks unprofessional

**To Reproduce**

1. Go to podkrepi.bg/support/"Как да се свържем с вас"
2. Observe the layout of the page
3. Click on all the fields, but do not enter data, to the validation is triggered
4. Observe the layout of the page again, with every validation message  the hall page is displaced

**Expected behavior**
When validation messages appear the main structure of the page is not changed or displaced

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154237586-2cab73dd-65e8-4b06-a920-464a69e45302.png)
![image](https://user-images.githubusercontent.com/99661273/154237662-5150b2a2-a8c2-4879-9a45-36afab08aa99.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by kachar** [comment]
Doesn't seem too bothering. Otherwise, it would have big empty spaces for each hidden error text.

We might add animation but it looks like a waste of time at this point. If the issue is brought up by more people we'll find a solution.
