### ISSUE TITLE
[Bug] Minor - Email "Добре дошъл в Подкрепи.бг" - the link for Discord server in unreadable

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#508]
**Describe the bug**
In the email "Добре дошъл в Подкрепи.бг" the link for Discord server in unreadable because it is blue on blue background 

**To Reproduce**

1. Cоmplete the flow and register as  "Доброволец"
2. Open the email send in the end of the registration
3. Observe that the link for Discord server in unreadable because it is blue on blue background

**Expected behavior**
he link for Discord server in readable

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154241723-649f2f2b-7008-4ef3-a3e8-d5619b1985dd.png)

**Comment by borislavstoychev** [comment]
https://github.com/podkrepi-bg/api/pull/252
