### ISSUE TITLE
[Bug] Minor - podkrepi.bg/home page the anchor buttons should be removed

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#518]
**Describe the bug**
podkrepi.bg/home page the anchor buttons next to the subtitles for ex "Какво правим" should be removed, because they ate not used

**To Reproduce**

1. Go to podkrepi.bg/home page
2. Scroll down to "Какво правим" subtitle
3. Hover it
4. Anchor button appears

**Expected behavior**
As consulted with UX designer the anchor buttons are not used so should be removed on the hole page

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154679983-1f7268d6-3c8c-4061-aef2-2f1f1ac10518.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by TeDy-A-K** [comment]
The same is valid аlso for pages: podkrepi.bg/about-project#our-story , podkrepi.bg/about#principles-that-unite-us ,

**Comment by kachar** [comment]
@TeDy-A-K how do you gather the data to decide that these anchors are not used?

I'd love to analyze the data before we take a step further to the actual development.

Until then I'll add a label "on hold"

**Comment by TeDy-A-K** [comment]
Hi @kachar , before logging the bug I have communicated it with ux team (Alex Tomov). And he confirmed they will not be used, and need to be removed. I have mentioned it in the defect description of the  expected result part

**Comment by kachar** [comment]
Six months ago we've got a feature request (https://github.com/podkrepi-bg/frontend/pull/278) that expected this functionality. I'd stay it's a waste of time and development effort to do this back and forth of want/do not want.

I'd say we keep it as is and focus on more important additions instead of removals. 
If there are further expectations I hope Alex Tomov will discuss them prior to sending them for development.

**Comment by TeDy-A-K** [comment]
@kachar. Totally agree, I didn't know for the feature request. And anyway its a minor, no need to fix it at all

**Comment by kachar** [comment]
However, I do agree we can improve the UX of the actual anchor functionality and make the icon more subtle with a smaller size.
