### ISSUE TITLE
[Bug] Minor - Home page/" Подкрепи ни като:" bullets should be used in the list instead of dashes 

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#521]
**Describe the bug**
At page Home page/" Подкрепи ни като:" bullets should be used in the list instead of dashes 

**To Reproduce**

1. Home page/" Подкрепи ни като:"
2. Observe the list

**Expected behavior**
the standard bullets should be used in the list instead of dashes 

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/154687386-3f65d493-ae18-43e9-a694-80ce123134f6.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by TeDy-A-K** [comment]
Alex Tomov from UX team will dive us more details about the exact bullet and color

**Comment by Polina1985** [comment]
Tedi, исках да ти споделя линк към user storita. 
https://docs.google.com/spreadsheets/d/1WVxlDB7iF34-VVffUU4geKLbsT6HjtQhkjEBOLYfJJ8/edit?usp=sharing

**Comment by ani-kalpachka** [comment]
I think we could close this issue since it refers to the old appearance of Homepage which is no longer valid.
@kachar, could you please confirm?
