### ISSUE TITLE
[Bug] Critical  - New Campaign Form/ UI/UX and Functional defects

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#522]
New Campaign Form/ UI-UX and Functional defects

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Click on menu "Дарителство"
3. Scroll down to "Предложи кампания"
4. А New Campaign Form is opened

**Expected behavior**
The user must see a well - design and functional New Campaign Form with all the buttons and fields working

Actual result: Not working buttons, irrelevant fields,  it is not possible to attach pictures in the Form

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome
- Version -Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by Polina1985** [comment]
[Defects-podkrepi_Създаване на Кампания.docx](https://github.com/podkrepi-bg/frontend/files/8098113/Defects-podkrepi_.docx)

**Comment by Polina1985** [comment]
@ani-kalpachka Моля да погледнеш

**Comment by ani-kalpachka** [comment]
We are now able to upload images, all buttons and fields are working.
@Polina1985, could you please advise if this bug is still valid?
