### ISSUE TITLE
admin panel needs refactoring

### ISSUE THREAD

**Issue by dpmarkov** [podkrepi-bg/frontend#528]
> a suggestion..
> In the context of the **admin** page.
> It would be a good idea if we **reuse the action buttons** in the grids for every entity.
> 
> ![Clipboard01](https://user-images.githubusercontent.com/71282381/155106603-615caeb6-4a97-4971-8d82-55424e1364a1.jpg)
> 
> Currently every entity uses its own component for the actions (view, edit & delete) which is repeating and not code efficient.
> 
> Also adding these buttons a **tooltip** would be a nice touch and very user friendly.

In addition to the task, I'm adding some needed **refactoring** in the admin panel.

For added consistency we need to have **modals** for `delete, delete all and details` to share the same look and feel across all entities. This will ensure they'll be easy to maintain and modify in the future if necessary.

**Comment by kachar** [comment]
Go for it, looks useful
