### ISSUE TITLE
[Bug] Minor - podkrepi.bg/Home page button "Включи се" should be the same color like the standard "Напред"/"Назад" navigation buttons

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#533]
**Describe the bug**
At page podkrepi.bg/Home page button "Включи се" should be the same color like the standard "Напред"/"Назад" navigation buttons 

**To Reproduce**

1. Go to podkrepi.bg/Home page
2. Scroll down to "Подкрепи ни като":

**Expected behavior**
Включи се" should be the same color like the standard "Напред"/"Назад" navigation buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155528686-f82b3e95-7697-4ce0-bb0f-970f260d19e6.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Additional context**
Verified with UX alexvtomov

**Comment by ani-kalpachka** [comment]
I think we could close this issue since it refers to the old appearance of Homepage which is no longer valid.
@kachar, could you please confirm?
