### ISSUE TITLE
[Bug] Major - podkrepi.bg/campaigns beginning of the page differ from mockup

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#534]
**Describe the bug**
podkrepi.bg/campaigns beginning of the page differ from mockup.  Background picture is missing. The title is black instead of blue as it is on the other pages. The longer text should be center aligned

**To Reproduce**

1. Go to podkrepi.bg/campaigns

**Expected behavior**
The page is no different than the mockup, or at least uses the common style for the site

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155532386-7399331e-8b53-4154-b32c-64feb7138574.png)
![image](https://user-images.githubusercontent.com/99661273/155532734-2ae6afd1-39da-410b-97a0-0dc96035e2b6.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit).

**Comment by ani-kalpachka** [comment]
As discussed with @swolf86 and @TeDy-A-K and requested by the marketing team, the subtitles have to be present on this page and the current look has to remain the same. 
Тherefore, I am closing this issue.
We can create a separate one for the titles (h1, h2) font-sizes and fonts;

**Comment by TeDy-A-K** [comment]
https://github.com/podkrepi-bg/frontend/issues/587 seperate issue for the titles
