### ISSUE TITLE
[Bug] Minor - podkrepi.bg/about /"Как започна всичко"  the text above the pic should be aligned center

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#535]
**Describe the bug**
At  podkrepi.bg/about /"Как започна всичко"  the text above the pic should be aligned center

**To Reproduce**

1. Go to  podkrepi.bg/about /"Как започна всичко" 
2. Observe the text above the picture

**Expected behavior**
the text above the pic should be aligned center

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155533114-93f265ac-86e1-4752-8ff9-88df31a57a27.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Additional context**
Consulted with UX alexvtomov

**Comment by ani-kalpachka** [comment]
Closing this issue because the text on this section has been removed.

**Comment by TeDy-A-K** [comment]
Verified
