### ISSUE TITLE
[Bug] Minor - blog.podkrepi.bg button "Начало" is not working

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#540]
blog.podkrepi.bg - "Начало" button is not working

1. Go to blog. podkrepi.bg
2. Click on "Начало" button

**Expected behavior**
The user should be redirected to the Home page - https://podkrepi.bg/

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome 
- Version- Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by dimitur2204** [comment]
I think that it's fine since we have a button "Към сайта" 
![image](https://user-images.githubusercontent.com/61479393/168469231-3b395355-9d7b-4f84-96f1-f5f5821f40a8.png)
Next to "Начало" that leads to podkrepi.bg
