### ISSUE TITLE
[Bug] Major - blog.podkrepi.bg - no need of two buttons for returning the user to Home page ("Начало" and "Към сайта")

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#541]
blog.podkrepi.bg - no need of two buttons for returning the user to Home page ("Начало" and "Към сайта")

**To Reproduce**

1. Go to blog.podkrepi.bg
2. See on the upper left corner both buttons - "Начало" and "Към сайта"

**Expected behavior**
Тhe user to have an easy use the site, not to wonder which button to choose. 

**Desktop (please complete the following information):**

- OS:Windows
- Browser Chrome
- Version - Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by vikito755** [comment]
Which button do we want to keep "Към сайта" or "Начало"? Also where should it lead?

**Comment by ani-kalpachka** [comment]
Closing this issue since we already have the blog implemented internally in the site:
https://podkrepi.bg/blog
