### ISSUE TITLE
[Bug] Critical - podkrepi.bg/"Регистарция" "Back to Application" button redirects to edit profile

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#545]
**Describe the bug**
"Back to Application" button redirects to edit profile, not to the site home page

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Enter all fields correctly and click "Register"
4. After the registration is successfully finished
5. Click the browser "Back" button
6. You are redirected to page "You are already logged in"
7. Click on the "Back to Application" button

**Expected behavior**
User is redirected back to the site home page, not Edit Profile functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155706571-deb02bdf-e6bd-4a1b-a9c9-0fd7b929b5c3.png)
![image](https://user-images.githubusercontent.com/99661273/155706466-a6b7e650-9b2e-48a3-8df8-0918797d54d5.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by kachar** [comment]
@stilian-nikolaev Any progress on this issue?

**Comment by ani-kalpachka** [comment]
I assume this issue is no longer valid.

**Comment by igoychev** [comment]
yep, fixed long ago
