### ISSUE TITLE
[Bug] Minor - podkrepi.bg/"Регистарция" form is not fully translated in bulgarian language

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#547]
**Describe the bug**
Registration form is not fully translated in bulgarian language

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Observe the page

**Expected behavior**
All fields are translated

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155709527-45186e19-0656-4258-b454-78675b8c00cd.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by igoychev** [comment]
Solved with this PR : https://github.com/podkrepi-bg/infrastructure/pull/27
