### ISSUE TITLE
[Bug] - Major podkrepi.bg/"Регистарция" user input in fileds "passowrd" and "Confirm password" is deleted when validation for them is triggered

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#548]
**Describe the bug**
user input in fileds "passowrd" and "Confirm password" is deleted when validation for them is triggered

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Enter passowrd ( ex:  "1" )
4. Enter the same in the "Confirm password"
5. Click "Register" button

**Expected behavior**
The validation for the mandatory fields is triggered. The user input is unchanged

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155709797-54dde7c5-cde6-4b23-af1b-15d202602b52.png)
![image](https://user-images.githubusercontent.com/99661273/155709845-fe6cf64e-0300-4bf0-bc41-39bdc0704208.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by igoychev** [comment]
Closing this as it is default behavior of Keycloak. 
Also, it looks correct to clear the passwords fields if they are invalid as there is no way to know how to correct them if you see only stars(*).
