### ISSUE TITLE
[Bug] Critical - podkrepi.bg/"Регистарция" missing password complexity restrictions 

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#549]
**Describe the bug**
Missing password complexity restrictions  on the registration form

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Enter one digit passowrd  and confirm it
4. Enter data in all other fields correctly
5. Click "Register" button

**Expected behavior**
There are password complexity restrictions and validation is triggered

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by TeDy-A-K** [comment]
@kachar  on production the restrictions are in palce

**Comment by kachar** [comment]
@TeDy-A-K Updated staging password policy to match production

![image](https://user-images.githubusercontent.com/893608/157870927-bcd6a491-0f95-4e8b-9f04-441f2ab4d8b6.png)


Please confirm

**Comment by TeDy-A-K** [comment]
Verified
