### ISSUE TITLE
[Bug] Major - podkrepi.bg/"Регистарция" missing input validation on fields "First Name" and "Last Name"

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#550]
**Describe the bug**
missing input validation on fields "First Name" and "Last Name" at page  podkrepi.bg/"Регистарция" 

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Enter invalid symbols in "First name" and "Last name" fields

**Expected behavior**
Validation is triggered. Only "-" should be permited in the "Last name" field

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155712395-468b278c-f919-4249-85bc-1ba6d893817d.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by igoychev** [comment]
Wondering what Elon Musk will say if he wants to register his son ;) 
Closing with Won't fix - if someone wants put strange symbols in his name, he is hindering himself, not the functionality of the donation platform.
