### ISSUE TITLE
[Bug] Minor - podkrepi.bg/"Регистарция" form the bulgarian version of the form should be open by default

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#551]
**Describe the bug**
 podkrepi.bg/"Регистарция" form the bulgarian version of the form should be open by default

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Observe the page

**Expected behavior**
the BG version of the form should be open by default, not the EN one

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/155714283-c13e2417-c83a-4b67-b69a-75c40e29d72a.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by TeDy-A-K** [comment]
I think it is similar to the "Вход" functionality. For logging an existing user, which default is BG. The pic is from prodkrepi.bg , because in dev.odkrepi.bg in the moment there is another issue with loging pages ( both for new user and registration)
![image](https://user-images.githubusercontent.com/99661273/156017553-aead8ab5-7bfd-4725-b65e-dc8c212127ba.png)

**Comment by igoychev** [comment]
For the bulgarian by default, we need to have a translation file for the register page in the Custom Keycloak theme. See how to make changes in the Keycloak theme here: https://github.com/podkrepi-bg/infrastructure/tree/main/keycloak#custom-theme-for-podkrepibg
To set a local test server: https://github.com/podkrepi-bg/infrastructure/tree/main/keycloak#local-testing

**Comment by igoychev** [comment]
The bulgarian translations were added with this merge https://github.com/podkrepi-bg/infrastructure/pull/27

Now for which Language will shown as default the logic is the following:
 - At very first time if the user has never used the platform keycloak is configured to load Bulgarian
 - If the user manually chooses the Language from the selector, then the system will remember it after login and next time will show the previously selected Language. 
More details here: https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/realms/themes.adoc#user-locale-selection
