### ISSUE TITLE
[Bug] Major -  podkrepi.bg/"Регистарция" when the user switches bethwen BG and EN version the form data is deleted

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#552]
**Describe the bug**
when the user switches bethwen BG and EN version the previously entered form data is deleted

**To Reproduce**

1. Go to Home page
2. Click on "Регистрация"
3. Enter some data in the form
4. Change the version form BG to EN or vice versa

**Expected behavior**
The already entered data is preserved, not deleted

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by kachar** [comment]
I consider this a normal behavior as user leaves the page on language change the same way as they do when they click home button.

**Comment by igoychev** [comment]
closing as default behavior of Keycloak that we won't be able to change. Also quite unlikely to create any usability problems as language selection is usually done before the start of entering text.
