### ISSUE TITLE
[Bug] Major - Create campaign Form (EN) - billingual text both English and Bulgarian (Localization Testing)

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#554]
**Describe the bug**
**Bilingual text in Create Campaign Form (EN)** 

To Reproduce

1. Go to dev.podkrepi.bg
2. Change the language with EN
3. Navigate to the "Donation" menu
4. Scroll down to "Suggest campaign"
5. A Create campaign Form is opened

**Expected behavior**
To see all fields in English.

**Actual result:**
The user is seeing a mixed language Form - which is not user - friendly.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome
- Version -
![Create Campaign Form en](https://user-images.githubusercontent.com/77857494/155720560-6074b589-1556-41b8-b184-04195550dbc9.jpg)

**Comment by ani-kalpachka** [comment]
Hello, @Polina1985!
I cannot reproduce this issue: 

![image](https://user-images.githubusercontent.com/14351733/155810973-4cb8f9af-ab8d-47e0-af15-1f4243160bd0.png)

Could you please recheck?

**Comment by Polina1985** [comment]
https://podkrepi.bg/en/campaigns/create

**Comment by Georgiev86** [comment]
![Podkrepi bg - EN](https://user-images.githubusercontent.com/97630899/155845265-03fccb61-5e55-48fa-88d6-6b0d8553aa91.png)

**Comment by kachar** [comment]
@Polina1985 Also cannot reproduce on https://dev.podkrepi.bg/en/campaigns/create

Probably it's fixed already. Please re-open if issue persists

**Comment by kachar** [comment]
Okay got it, it happens with a direct link, instead of after a language change

**Comment by kachar** [comment]
Just deployed latest master to https://dev.podkrepi.bg/en/campaigns/create 

Please verify if this issue is fixed

**Comment by Polina1985** [comment]
It is fixed already.
Thanks.
