### ISSUE TITLE
[Feature] New page> Choose payment option 

### ISSUE THREAD

**Issue by AlbenaGeleva** [podkrepi-bg/frontend#557]
To complete the donation flow, one new landing page is needed:
from https://dev.podkrepi.bg/campaigns/for-the-children the Подкрепи ни (Donate) button sends to a Login/Register/Continue as anonymous page. The page loops back to the donation process where the donation amount is chosen via the button Подкрепи ни. From here, a new page should be opened asking for the payment method - online by credit card (Stripe) or via bank transfer.
See attached file with sample text and format for the new page.
[Podkrepi Campaigns - Page Choose Payment Option.docx](https://github.com/podkrepi-bg/frontend/files/8141972/Podkrepi.Campaigns.-.Page.Choose.Payment.Option.docx)

**Comment by ani-kalpachka** [comment]
Closing this task since it is completed.
