### ISSUE TITLE
[Tech] Split frontend/src/service/restRequests.ts in individual small files

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#573]
**Is your feature request related to a problem? Please describe.**

At the moment with every PR this file conflicts as many people add their code to the same file

**Describe the solution you'd like**
Let's split this file in small dedicated files in the same directory for example

```
frontend/src/service/restRequests/document.tsx
```

Which includes the following hooks:

```
useCreateDocument
useEditDocument
useDeleteDocument
useDeleteManyDocuments
```

**Comment by kachar** [comment]
@podkrepi-bg/softuni-bootcamp This task is for any of you if you want it

**Comment by dpmarkov** [comment]
> @podkrepi-bg/softuni-bootcamp This task is for any of you if you want it
I'll do it!
