### ISSUE TITLE
[Bug] UX issue with the UI - The mandatory fields are not marked as such with red asterisks

### ISSUE THREAD

**Issue by boyanaboneva** [podkrepi-bg/frontend#586]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Navigate to: https://dev.podkrepi.bg/campaigns/create
2. Have a look at the fields and find out, which of them are mandatory

**Expected behaviour**
All mandatory fields should have red asterisks, which indicates they are mandatory.

**Screenshots**

**Desktop (please complete the following information):**

- OS: latest MacOS, but it would be at any OS
- Browser: latest Opera, but it would be at any browser as it is user experience.
- Version: 83

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ani-kalpachka** [comment]
Closing this task since it is completed.
