### ISSUE TITLE
[Bug] Minor- podkrepi.bg/campaigns  titles (h1, h2) font-sizes and fonts

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#587]
**Describe the bug**

**To Reproduce**

1. Go to podkrepi.bg/campaigns

**Expected behavior**
titles (h1, h2) font-sizes and fonts comply with the other pages ( the subtitle should be blue)

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/157193894-18e37f55-bb1f-4672-ba31-1cd6576a3498.png)

**Desktop (please complete the following information):**

OS: Windows 10
Browser Edge
Version Version 98.0.1108.50 (Official build) (64-bit).

**Comment by ani-kalpachka** [comment]
@TeDy-A-K Could, @swolf86 could you please confirm if the fonts and font-sizes have to be the following everywhere in the site?
 - h1: Montserrat, 45px
 - h2: Montserrat, 35px

**Comment by nradkova** [comment]
This bug has already been fixed.

![Screenshot (69)](https://user-images.githubusercontent.com/78322634/163841456-a7b681a4-34a7-4ec8-8325-8ea61f3ba09a.png)
