### ISSUE TITLE
[Bug] Major - Deploy version is not changing after new deploy on dev.prokrepi.bg

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#590]
**Describe the bug**
Deploy version is not changing after new deploy on dev.prokrepi.bg

**To Reproduce**

1. Observe the version number before and after deploy

**Expected behavior**
After deploy the version is incremented

**Screenshots**
![image](https://user-images.githubusercontent.com/99661273/157196867-a052ad3e-56e1-4573-8a44-2c45888c2318.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by igoychev** [comment]
cleanup - this was fixed long ago
