### ISSUE TITLE
[Bug] Critical - When user is logged in his session does not expire at all

### ISSUE THREAD

**Issue by TeDy-A-K** [podkrepi-bg/frontend#592]
**Describe the bug**
When user is logged in his session does not expire at all

**To Reproduce**

1. Log in
2. Leave it for an hour

**Expected behavior**
The user session expire after appropriate time ( 15, 30 min foe example )

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge
- Version Version 98.0.1108.50 (Official build) (64-bit)

**Comment by igoychev** [comment]
cleaning up - this is working now, currently is set to 1h
