### ISSUE TITLE
[Bug] No adjustment possible in User Profile. Unable to edit Username, Password and Data in Profile .

### ISSUE THREAD

**Issue by Georgiev86** [podkrepi-bg/frontend#608]
**Describe the bug**
When the user tries to correct the name, password or date of birth. The platform does not allow.

**To Reproduce**

1. Go to 'https://dev.podkrepi.bg/profile'
2. Click on 'Лична Информация'
3. Edit Парола, Име и рожден ден

**Expected behavior**
Тhe user must be able to update their data

** Actual result:**
The platform does not allow corrections and refreshes the page.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Win 10]
- Browser [ chrome]

https://user-images.githubusercontent.com/97630899/158023285-7452fd3b-e6c1-4b77-bc4b-be50ef91bf47.mp4

**Comment by kachar** [comment]
The edit name and birthday functionality have been delivered with #687 

The rest of this issue will be tracked in https://github.com/podkrepi-bg/frontend/issues/698

Closing this one so it can be tested
