### ISSUE TITLE
[Feature] Implement uploading campaign files

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/frontend#616]
**Is your feature request related to a problem? Please describe.**
We need to support uploading files for a campaign. Currently, there is an upload dialog from uppy that is integrated in our frontend. However, we chose not to use Uppy as it is too heavy for our simple use-case. The back-end for uploading files is already implemented and deployed to development. You can see the changes [here](https://github.com/podkrepi-bg/api/pull/123)

**Describe the solution you'd like**
The component from Uppy should be removed and we should have a simpler solution that just sends the selected files to the API. We can do it simple at the beginning by just listing the file names that are going to be uploaded. However, in the future there will be a need to have a better visualization. I only managed to find:
- [component 1](https://react-dropzone-uploader.js.org/)
- [component 2](https://www.positronx.io/react-image-upload-with-preview-percentage-progress-bar-tutorial/)

**Additional context**
The current implementation of the back-end expects a multipart form-data to be submitted with the files. All files should be indexed with the `file` key. It is important to make sure the user's authentication token is passed to the back-end when uploading since the uploader is taken from the token itself.

**Comment by kachar** [comment]
@dplamenov Is there anything left to be done here or the campaign upload functionality can be considered completed?
