### ISSUE TITLE
[Bug] Major - App makes wrong requests

### ISSUE THREAD

**Issue by dpmarkov** [podkrepi-bg/frontend#624]
**Describe the bug**
Context: admin panel
Wrong GET requests are being sent to the api. This happens when `<DetailsModal />` component (_it doesn't matter for which entity_) is being rendered. It makes requests with either empty string or wrong id and fails to re-fetch data for the modal. This should be avoided.

This behavior causes the app to be not responsive.
For example: if you delete a record from the grid then sometimes the deleted row does not disappear instantly.

**To Reproduce**

1. Go to [admin](http://localhost:3040/admin)
2. Select any entity
3. Delete a record
4. Watch the console for errors

**Comment by kachar** [comment]
@dpmarkov Can you still reproduce this behavior?

If yes, then can you please share which entity/page do you use to reproduce it

**Comment by dpmarkov** [comment]
Yes I can.
Just to be clear that I'm on master branch and all it's up to date.

Let's take **Withdrawal** entity.

If I delete a record, the grid doen't refresh. Then if I click somewhere or wait a while then it does.
After that if I check the console I see GET requests being made for the same record that was just removed.

![deleted](https://user-images.githubusercontent.com/71282381/162598251-8f753bb3-6213-47eb-90c8-714cf7cc41c7.jpg)
![error](https://user-images.githubusercontent.com/71282381/162598253-fa7fe549-baf3-4683-ab29-00c2430012fd.jpg)

Unfortunately similar behavior we can see with **Coordinator**.

But this time the errored requests are different.
In the prefetching of the list the authorization header is missing.
After a few tries later React Query decides to add the token and it's all good (_ironically speaking_). 

![1](https://user-images.githubusercontent.com/71282381/162598627-df256c7f-9656-4e91-b919-d4298bb0706d.jpg)
![2](https://user-images.githubusercontent.com/71282381/162598628-fdfae4b1-9144-4465-95e6-5b0ff9fdc7b0.jpg)
![3](https://user-images.githubusercontent.com/71282381/162598629-a1781440-091b-4b50-ab3c-41abd9dd0fca.jpg)

Here's **BankAccounts**.

![bank-error](https://user-images.githubusercontent.com/71282381/162598781-c270cb31-a236-44e9-bc60-2ba0b58dab95.jpg)

**Documents** are no different.

![docs](https://user-images.githubusercontent.com/71282381/162598956-e30ae7c8-3908-4f37-ae64-4e6f53459cb0.jpg)

I haven't checked all entities but I think it'll be all the same.

**Comment by kachar** [comment]
@dpmarkov Would you take care of this issue, we've got green light to fix it since it's still reproducible

**Comment by dpmarkov** [comment]
Actually, I was working on the issue but got transfered to do another task. I'll get back to it and see what I can do.
