### ISSUE TITLE
[Feature] Improve wording of the delete profile modal

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#635]
The delete profile modal texts looks awkward and should be improved

![image](https://user-images.githubusercontent.com/893608/159254607-98c5f56f-c64f-4754-889d-18c2bd70e7d4.png)

https://github.com/podkrepi-bg/frontend/blob/882b2e698b8243e9d6ce7ca65feb643b58aca423/src/components/auth/profile/PersonalInfoTab.tsx#L165-L192

**Comment by omniage** [comment]
<Typography variant="h6" component="h2">
            Изтриване на акаунт
          </Typography>
          <Typography className={classes.graySpan}>Съжаляваме, че ни напускате!</Typography>
          <Typography className={classes.heading}>Преди да ни напуснете...</Typography>
          <hr></hr>
          <ul style={{ listStyle: 'disc', paddingLeft: '20px' }}>
            <li className={classes.h5}>
              Ако ви е омръзнало да получавате имейли, деактивирайте ги <Link href="#">оттук</Link>.
            </li>
            <li className={classes.h5}>
              Ако .........................., моля, пишете <Link href="#">тук</Link>.
            </li>
            <li className={classes.h5}>Изтриването на акаунт е необратимо.</li>
            <li className={classes.h5}>Ще бъде невъзможно да възстановите акаунта си.</li>
          </ul>
          <Button
            variant="contained"
            size="large"
            color="secondary"
            onClick={() => setIsDeleteAccountModalOpen(false)}>
            Запази моя акаунт
          </Button>
          <Button variant="contained" size="large" color="secondary" style={{ marginLeft: '10px' }}>
            Изтрий моя акаунт
          </Button>
