### ISSUE TITLE
[Bug] Major - Donation through the Platform as a Registered User has not reflected the Administrative panel, Menu "Дарения" and the FRONT-END of the Campaign

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#641]
**Describe the bug**
Donation in the Platform as a Registered user does not reflect on the Administration panel in menu "Дарения" and in Front-end of the site

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Click on Enter valid credentials of a Registered user
3. Select Menu "Дарителство"
4. Scroll down to 'Кампании"
5. Choose random Campaign
6. On the right side, choose the button "Подкрепи" and click on
7. Choose a sum and click - 500 BGN
8. A redirection to stripe is done
9. Enter test data: card information: 4242 4242 4242 4242
The other data should you invent by yourself
10. A message for successful payment should appear

**Expected behavior**
**FRONT - END**  - To see your Donation has been made (the sum donated) in the UI of the Campaign both as a sum and as a Donator Polina Mihaylova - 500 BGN
**FRONT-END** - counter of the Donator to work properly and to update after each donation

**BАCK- END** - The Donation to be seen in the Administrative panel - menu "Дарения" (as you are logged **as an Administrator**) with all necessary fields.
![Inkedотразена е дарената сума но не в Дарител 1 и в брой дарения_LI](https://user-images.githubusercontent.com/77857494/159476893-5d1a4014-fd1f-441b-a7d1-c81058809769.jpg)
![InkedДарения без последно дарение в Админ панела_LI](https://user-images.githubusercontent.com/77857494/159476912-7be52b84-fdc5-47c0-8961-18669aafc4c2.jpg)

**Actual result:**
- no reflection over the last donation - neither the name of the donator nor the sum
- no back - end link - to Donations - in the Administrative panel, menu "Дарения"

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows
- Browser chrome
- Version - Version 99.0.4844.74 (Official Build) (64-bit)

THE PICTURES ARE TAKEN AFTER A DONATION THROUGH THE PLATFORM HAS BEEN MADE (by a Registered user - Polina Mihaylova).

**Comment by kachar** [comment]
@dplamenov Let's add the created date to the frontend so it's clear when a given donation has been created

That's beside the API sorting of the donations
