### ISSUE TITLE
[Bug] Major - Admin panel/  Menu "Тегления" does not work properly 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#643]
**Describe the bug**

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Login as an admin
3. Select the side Menu "Тегления"
4. Click on it

**Expected behavior**
To open a new page with info.

Actual result; 500 Internal server error

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome
- Version 99.0.4844.74 (Official Build) (64-bit)

![500](https://user-images.githubusercontent.com/77857494/159481500-a0f8af6b-745a-423e-9390-d4a88710a1ab.jpg)

**Comment by kachar** [comment]
Can you please check again, should be ok by now

**Comment by Polina1985** [comment]
Hello, ilko.
I think it is OK as per functionality.
As far as it concerns accessibility, UI it is not good enough. Look at the attached pic.

I opened through my phone A22 5G, Android![Screenshot_20220409-130507_Chrome.jpg](https://user-images.githubusercontent.com/77857494/162567292-1ddaee39-b49f-4d68-8a6b-a4f849bbbcfa.jpg)

**Comment by igoychev** [comment]
cleaning up - this is working now
