### ISSUE TITLE
[Bug] Minor - The Bulgarian version of the Registration form is in English

### ISSUE THREAD

**Issue by AntoanetaMincheva** [podkrepi-bg/frontend#646]
**Describe the bug**
When you open the Registration form and choose Bulgarian, all the fields' names are in English, except "Парола"

**To Reproduce**

1. Go to site URL
2. Click on the burger menu
3. Choose "Регистрация"
4. Choose "Bulgarian" from the drop-down menu in the upper right corner

**Expected behavior**
A registration form in Bulgarian is opened

![Screenshot_2022-03-22-23-26-25-869_com android chrome](https://user-images.githubusercontent.com/101809720/159581660-2233be01-d6bf-4d46-8d7c-9532b433cf81.jpg)

**Smartphone:**

- Device: Xiaomi Redmi Note 10 S
- OS: Android
- Browser: Chrome
- Version v0.9.8

**Comment by AntoanetaMincheva** [comment]
![Screenshot_2022-03-18-23-15-27-880_com android chrome](https://user-images.githubusercontent.com/101809720/159582228-a33a7a5e-4a5b-4aeb-8658-cfdcbadb6f12.jpg)

**Comment by Polina1985** [comment]
@kachar

**Comment by igoychev** [comment]
fixed by @GeorgyGenchev  with this merge https://github.com/podkrepi-bg/infrastructure/pull/27

**Comment by kachar** [comment]
@igoychev Is that development deployed to staging? If so please add the label so QA team can test
