### ISSUE TITLE
[Bug] Minor - The name of the password field in the Registration form begins with a small letter

### ISSUE THREAD

**Issue by AntoanetaMincheva** [podkrepi-bg/frontend#647]
**Describe the bug**
All the fields' names in the Registration form in English begins with capital letters, except the password field

**To Reproduce**

1. Go to site URL
2. Click on burger menu
3. Choose 'Регистрация'
4. Choose English from the drop-down menu in the upper right corner
5. A registration form in English is opened and all the fields' names begins with capital letters, except the password field

**Expected behavior**
A registration form in English is opened with names of the fields in the same style

![Screenshot_2022-03-22-23-26-47-093_com android chrome](https://user-images.githubusercontent.com/101809720/159583752-bacd443b-22d0-44a8-b19e-e2e1613fc8c0.jpg)

**Smartphone (please complete the following information):**

- Device: Xiaomi Redmi Note 10 S
- OS: Android
- Browser: Chrome
- Version v0.9.8

**Comment by AntoanetaMincheva** [comment]
![Screenshot_2022-03-18-23-15-27-880_com android chrome](https://user-images.githubusercontent.com/101809720/159584381-7d11b1ca-03cb-400e-86a9-92cd0812d39a.jpg)

**Comment by igoychev** [comment]
The fix for password casing needs to happen in the Keycloak Theme theme-podkrepi/register. See how to setup a local Keycloak and edit the theme here: https://github.com/podkrepi-bg/infrastructure/tree/main/keycloak#local-testing
