### ISSUE TITLE
[Bug] Major - For each campaign there is a difference between reached amount shown on the campaign list and this one shown in the campaign pages

### ISSUE THREAD

**Issue by AntoanetaMincheva** [podkrepi-bg/frontend#649]
**Describe the bug**
For each campaign there is a difference between reached amount shown on the campaign list and this one shown in the campaign pages

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to site URL
2. Click on the burger menu
3. Click on "Дарителство"
4. Choose "Кампании" from the drop-down menu
5. Scroll down to the campaign list
6. Choose one of the campaigns and click on it to enter the campaign page
7. There is a difference between the shown reached amount in the list and on the campaign page

**Expected behavior**
The shown information about reached and targeted amounts are the same in the list and on the campaign page

**Screenshots**
![IMG_20220323_083841](https://user-images.githubusercontent.com/101809720/159641561-b0f8ca1c-c2d2-4599-b9d0-a8b46a022618.jpg)

![IMG_20220323_083900](https://user-images.githubusercontent.com/101809720/159641586-b6b3acde-c117-4a33-bdd9-aa48eb7a7135.jpg)

**Smartphone:**

- Device: Xiaomi Redmi Note 10 S
- OS: Android
- Browser: Chrome
- Version v0.9.8

Additional comment:
The information about donors shown on the bottom of campaign pages are the same for each campaign and it seems like they are not related to the campaign

**Comment by AntoanetaMincheva** [comment]
![Screenshot_2022-03-18-23-15-27-880_com android chrome](https://user-images.githubusercontent.com/101809720/159642596-773e5052-8611-47dc-9159-9c046ce1ba48.jpg)

**Comment by kachar** [comment]
@podkrepi-bg/softuni-bootcamp Please share which API endpoints provide both of the amounts so we can trace the error.

**Comment by Bunny303** [comment]
Issue will be fixed in https://github.com/podkrepi-bg/api/issues/198

**Comment by kachar** [comment]
@AntoanetaMincheva A fix has been deployed to staging, please validate it and reopen the ticket if issue still occurs.
