### ISSUE TITLE
New home page design

### ISSUE THREAD

**Issue by PepiPetrov** [podkrepi-bg/frontend#652]
Refractoring home page to look like figma design.
Link to design: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=8281%3A24205.

Screenshots:
   Before:
![2022-03-25](https://user-images.githubusercontent.com/74186271/160117782-1f724e89-3dee-4a9b-b203-c4bc099b53fe.png)
![2022-03-25 (2)](https://user-images.githubusercontent.com/74186271/160117773-250d9d83-a007-45a1-83bc-479c303d9705.png)
![2022-03-25 (3)](https://user-images.githubusercontent.com/74186271/160117775-604f237e-c828-47fa-a2b2-bb46b852c851.png)
![2022-03-25 (4)](https://user-images.githubusercontent.com/74186271/160117778-88c649f2-7ade-4599-9772-cce196499764.png)
![2022-03-25 (5)](https://user-images.githubusercontent.com/74186271/160117780-fd4cf300-77d6-4055-8cb0-76708991d38c.png)
![2022-03-25 (1)](https://user-images.githubusercontent.com/74186271/160117769-d87c47f6-41fc-47cc-85ae-dd12b438e254.png)

**Comment by kachar** [comment]
@PepiPetrov Please add link to the design and attach a screenshot
