### ISSUE TITLE
[Bug] Campaigns Grid dont load

### ISSUE THREAD

**Issue by dplamenov** [podkrepi-bg/frontend#671]
**Describe the bug**
![Screenshot at Apr 04 17-57-56](https://user-images.githubusercontent.com/30602242/161572174-4cafcbd5-6f21-407e-8913-dd1ca8f6846c.png)

**To Reproduce**

1. Go to `admin/campaigns`
2. See error

**Comment by igoychev** [comment]
Just checked in master - looks like working now
