### ISSUE TITLE
[Bug] Major - User Profile on Mobile device - visualization problems 

### ISSUE THREAD

**Issue by Polina1985** [podkrepi-bg/frontend#677]
Mobile Device Android/ Successful Login of an existing user/ Login screen - functional testing

**To Reproduce**

1. Go to dev.podkrepi.bg
2. Click on "Вход" button
3. Enter valid credentials for log in of an existing user - email and password
4. A new screen is opened "Дарителски профил"

**Expected behavior**
То visualize all necessary data - menus of the screen "Дарителски профил" ("Дарения", "Лична информация", "Сертификати", "Договор дарение")

Actual result:
1. The user cannot see all the menus on the screen "Дарителски профил" - only 2 menus - "Дарения" and "Лична информация"

**Screenshots**
![Inked277847465_294685169410416_2482969535803029100_n_LI](https://user-images.githubusercontent.com/77857494/161932240-01c0816e-b560-4caf-a8b9-ee7627e6e6dc.jpg)

**Smartphone (please complete the following information):**
 Device: Huawei y7 2019, EMUI version 8.2.0, Android version: 8.1.0
- OS: Android
- Browser Chrome
- Version - Chrome 99.0.4844.73

**Comment by Polina1985** [comment]
@kachar

**Comment by dimitur2204** [comment]
Are there any designs of how it should look on mobile?

**Comment by Polina1985** [comment]
I think figma but you should check further.
