### ISSUE TITLE
[Feature] Add profile menu in admin layout navigation bar

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#689]
**Is your feature request related to a problem? Please describe.**
When user is on https://dev.podkrepi.bg/ they see their profile menu in top right corner, but when user goes to https://dev.podkrepi.bg/admin they don't see the menu anymore and they can't logout or return to the public website

**Describe the solution you'd like**
Add a profile menu similar to the public website one with the following options:

- Homepage
- Profile
- Line separator
- Logout

Please use pre-defined `routes` and consider the mobile version of the menu

**Additional context**
![image](https://user-images.githubusercontent.com/893608/162577183-cf5dbe2d-a496-40a3-91c2-105d609a9234.png)

![image](https://user-images.githubusercontent.com/893608/162577375-40201e74-b4d3-4b7a-95b1-102011eefd63.png)

**Comment by PepiPetrov** [comment]
This problem appears only when non-authenticated user tries to get to the page.

**Comment by kachar** [comment]
@PepiPetrov It's a new feature, not a problem.

The admin layout does not have profile menu at all

**Comment by PepiPetrov** [comment]
I can see that there is a profile menu on the admin.
![2022-04-13](https://user-images.githubusercontent.com/74186271/163122179-0d1ce295-d4a9-4b0e-b91e-e41fae144187.png)

**Comment by kachar** [comment]
@PepiPetrov Let's investigate why this menu is shown in some cases and hidden in others.

It should be visible at all times imo

**Comment by PepiPetrov** [comment]
This problem was fixed with putting securedProps on admin page, as there was no authentication on admin page.

**Comment by kachar** [comment]
Alright then! Let's close this issue :) :rocket:
