### ISSUE TITLE
[Bug] Admin interface is accessible even without authenticated user

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#693]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.podkrepi.bg/admin/info-requests or https://dev.podkrepi.bg/admin/withdrawals
2. See the admin UI 

**Expected behavior**
User is sent to login page and the back to the initially requested page

**Screenshots**
![image](https://user-images.githubusercontent.com/893608/162590817-6fb372f3-30d3-47e6-936e-64a9c6050049.png)

**Comment by borislavstoychev** [comment]
@kachar what do you think about this approach? Is it good or not? Unauthorized page is for example only. The point is to restrict access to the data grid or to the entire admin page?
```JavaScript
import { useTranslation } from 'next-i18next'
import AdminContainer from 'components/admin/navigation/AdminContainer'
import AdminLayout from 'components/admin/navigation/AdminLayout'

import Grid from './grid/Grid'
import GridAppbar from './grid/GridAppbar'
import { useSession } from 'common/util/useSession'
import { Typography } from '@mui/material'

export default function BenefactorPage() {
  const { t } = useTranslation('benefactor')
  const { keycloak } = useSession()
  if (keycloak?.realm == 'webapp-dev') {
    console.log(keycloak.realm)
    return (
      <AdminLayout>
        <AdminContainer title={t('benefactor')}>
          <GridAppbar />
          <Grid />
        </AdminContainer>
      </AdminLayout>
    )
  } else {
    console.log(keycloak?.realm)
    return <Typography variant="h1">Not authorized</Typography>
  }
}
```

**Comment by igoychev** [comment]
@borislavstoychev please check how the Profile page is secured, essentially the redirect to login happens with this code:

```JavaScript
  if (!keycloak.token) {
    return {
      redirect: {
        destination: `${routes.login}?pathname=${ctx.req.url}`,
        permanent: false,
      },
    }
  }
```

**Comment by kachar** [comment]
@borislavstoychev The point is to restrict access to the whole page

Be sure to use the method `securedProps` in the page component.

See 

https://github.com/podkrepi-bg/frontend/blob/36707a5a40755e1a1e44541e74a8597e2f3b3ed8/src/pages/profile.tsx#L1-L6

**Comment by borislavstoychev** [comment]
When i use ```securedProps``` how do i pass related json to translate the page? Directly here https://github.com/podkrepi-bg/frontend/blob/36707a5a40755e1a1e44541e74a8597e2f3b3ed8/src/middleware/auth/keycloak.ts#L50

```JavaScript
import BenefactorAddPage from 'components/benefactor/BenefactorAddPage'
import { securedProps } from 'middleware/auth/keycloak'

export const getServerSideProps = securedProps

export default BenefactorAddPage}
  ```
  result:
  
![image](https://user-images.githubusercontent.com/67734870/162728524-d16adcc8-de1f-41d8-b128-825f65c74ab5.png)

**Comment by dplamenov** [comment]
Maybe you can make `securedProps` return function. And pass array to the `securedProps` function. For example: `securedProps('benefactor')`. The downside to this is that we will have to change the way we call securedProps everywhere.

@kachar @igoychev @borislavstoychev

**Comment by borislavstoychev** [comment]
@dplamenov 
```JavaScript
export function securedProp(translate: string) {
  const securedProps: GetServerSideProps<ServerUser> = async (ctx) => {
    const cookies = parseKeycloakCookies(ctx)
    const keycloak = getKeycloakInstance(keycloakConfig, SSRCookies(cookies))

    if (!keycloak.token) {
      return {
        redirect: {
          destination: `${routes.login}?pathname=${ctx.req.url}`,
          permanent: false,
        },
      }
    }

    return {
      props: {
        ...(await serverSideTranslations(ctx.locale ?? 'bg', [
          'common',
          'auth',
          'validation',
          translate,
        ])),
        keyCookies: cookies,
        userToken: keycloak.token,
      },
    }
  }
  return securedProps
}
```

**Comment by kachar** [comment]
@dplamenov @borislavstoychev I would advise we split the translation and the token validation in two dedicated functions and then reuse them wherever we need.

At the moment both functionalities are compiled together which makes it difficult to extend the translation namespaces.


I've added one commit to split them https://github.com/podkrepi-bg/frontend/commit/f4892603416af3db7c7667af7b60f6b301b1eea7

Please continue with the implementations based on that one
