### ISSUE TITLE
[Feature] Make sure the edit password link leads to Keycloak profile page

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#698]
**Is your feature request related to a problem? Please describe.**
Related to #608 

At the moment edit button on the password does nothing

![image](https://user-images.githubusercontent.com/893608/162607832-82756791-6111-409e-a134-d74ab6ab27d8.png)

**Describe the solution you'd like**
Please make sure this button leads the user to Keycloak profile page so they can edit their password

The final link is:

https://keycloak.podkrepi.bg/auth/realms/webapp-dev/account/password

Where `webapp-dev` is the realm `keycloakConfig.realm`

To create that link please use the default `keycloak-js` methods if it can lead to the password page directly.

```tsx
keycloak?.createAccountUrl({
  redirectUri: `${baseUrl}${routes.profile}`,
})
```
If you can't make it work then feel free to use the hardcoded links (according to the config)

```tsx
const link = `${keycloakConfig.url}/realms/${keycloakConfig.realm}/${keycloakConfig.clientId}/password`
```

**Comment by dplamenov** [comment]
@kachar When user click `edit password` button should be redirected to `${keycloakConfig.url}/realms/${keycloakConfig.realm}/${keycloakConfig.clientId}/password`, right?

![Screenshot at Apr 10 11-50-21](https://user-images.githubusercontent.com/30602242/162610428-e25663ea-5eac-4cfc-8a3e-4146a136d244.png)
