### ISSUE TITLE
[Feature] Admin panel - Export Donations to excel

### ISSUE THREAD

**Issue by angelina-7** [podkrepi-bg/frontend#700]
Export donation records from Donations Grid in Admin UI

Ideally, the solution should be reusable for the other grids in the UI too.

**Comment by AndreyGoranov** [comment]
@igoychev @angelina-7 If no-one is working on this issue I would like to get assigned.

**Comment by igoychev** [comment]
@AndreyGoranov great for willing to take this one! I've updated the description. 

Let's start with the Donations Grid and then we will continue with other grids in separate tickets.
