### ISSUE TITLE
[Feature] Add option for create beneficiary in Create campaign

### ISSUE THREAD

**Issue by Bunny303** [podkrepi-bg/frontend#715]
Add option for create beneficiary in Create campaign when creator is regular user (not admin).
- form for creating baneficiary shoul be added in create capaign
- beneficiary data should be included in campaign request
- add checkbox "Аз съм бенефициент на кампанията" that will add beneficiary same person as campaign coordinator

**Comment by ani-kalpachka** [comment]
Beneficiary in 'Create Campaign' form is implemented.:
![image](https://user-images.githubusercontent.com/14351733/197359707-c770af92-c105-42b1-adee-01f20e48e651.png)
