### ISSUE TITLE
[Feature] Using selects for fields on recurring donation form

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#725]
![image](https://user-images.githubusercontent.com/64007447/163371514-39b8c8e0-a287-4111-8b48-fa92c37391e4.png)
@dimitur2204 I do agree that we need a better approach for selecting a person.

Let's use the current `<PersonSelect />` for this task and fork the topic in another issue so we can do it properly on all locations at once.

It can be done within the `PersonSelect` component without involving the recurring donations context. It can be realized as a Button that opens a Modal for finding the person you need by typing their name, etc

_Originally posted by @kachar in https://github.com/podkrepi-bg/frontend/issues/708#issuecomment-1105491940_

**Comment by dimitur2204** [comment]
What do you think about a Material UI Autocomplete or a normal Select or should I improvise with a Modal with a search bar to search the user that I think would look good?

**This is the Autocomplete**
![mui-autocomplete](https://user-images.githubusercontent.com/61479393/164980089-811371aa-dc1d-4c6d-8cdd-5e2c0cac529d.gif)

**Comment by kachar** [comment]
@dimitur2204 In fact we may need both for different scenarios. A separate dialog will help us add additional controls if we want to be sure that this person is the one we're looking for. It may display latest campaigns of this user or similar extra info.

One scenario would be to have this autocomplete in a modal dialog.

Do you think the autocomplete would be sufficient by itself?

**Comment by dimitur2204** [comment]
> @dimitur2204 In fact we may need both for different scenarios. A separate dialog will help us add additional controls if we want to be sure that this person is the one we're looking for. It may display latest campaigns of this user or similar extra info like ID, email or others.
> 
> One scenario would be to have this autocomplete in a modal dialog.
> 
> Do you think the autocomplete would be sufficient by itself?

Okay I got it. I will then implement something like a `PersonSelectModal` which will have a Select at the top showing the first and last name and then when you select a person it would show more info about him. And then you would click confirm to actually select the person.

Should we have a similar functionality for vaults?

**Comment by kachar** [comment]
That sounds great

If you mean if we're going to use the `PersonSelectModal` component in vault edit form, then yes.

**Comment by kachar** [comment]
Fixed with https://github.com/podkrepi-bg/frontend/pull/728
