### ISSUE TITLE
[Bug] Campaign details page - donors count

### ISSUE THREAD

**Issue by nradkova** [podkrepi-bg/frontend#727]
**Describe the bug**
The field `дарители` does not show the donors count for a campaign.

**To Reproduce**
![Screenshot (77)_LI](https://user-images.githubusercontent.com/78322634/165283370-9f8f5acb-3090-49a0-986e-041b109b3389.jpg)

**Expected behavior**
Expected to show 3, not 0, as the unique donors' count is 3.

**Additional suggestions**
1. If `дарители` is set for unique donors count, maybe it will be better for the donors' list to present the accumulated amount for each donor's donations, or
2. `Дарител 1` to be renamed to `Дарение 1` in order to present a single donation transaction.

**Comment by Bunny303** [comment]
Will add PR in the api that will return donors count in campaign data.
