### ISSUE TITLE
[Feature] Report form for irregularities

### ISSUE THREAD

**Issue by nradkova** [podkrepi-bg/frontend#737]
**Task**
- [ ] to create a form for whistleblowing.

[https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=3904%3A13406](https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=3904%3A13406) - FRAME 8

**Comment by kachar** [comment]
We might reuse the contact form and add a dropdown for the reason of contact.

https://dev.podkrepi.bg/contact

![image](https://user-images.githubusercontent.com/893608/165938542-7813c6a0-e8d3-4fa8-bdaa-7a95fdcc6105.png)

**Comment by nradkova** [comment]
We have considered adding a button on a campaign`s details page. This will redirect to 'campaigns/[slug]/report', where it will be the step form from Figma. For e.g.:
![Screenshot (79)](https://user-images.githubusercontent.com/78322634/165944012-1cf9d83b-bb48-40a0-8b8e-7ae76ac8c49c.png)
Is it fine or I shall change it?

**Comment by kachar** [comment]
@nradkova You can find the backend implementation at https://github.com/podkrepi-bg/api/pull/226

**Comment by nradkova** [comment]
Thank you.
