### ISSUE TITLE
[Feature] Functionality for uploading a payment receipt and updating bank transactions

### ISSUE THREAD

**Issue by GeorgyGenchev** [podkrepi-bg/frontend#739]
In the admin panel in the payments part a button should be added where you can upload a bank receipt of payments. 
The server api should correctly read the file which is in XML format and add theese payments to our database.

**Comment by kachar** [comment]
Let's initially upload the XML as a campaign file and do processing when we have the specific XML format. At the moment this format is not specified and not well-known.

**Comment by GeorgyGenchev** [comment]
It was clarified to me that, the idea is that this XML may contain number of payments which may be for different donations, and should not be connect to a single campaign.

**Comment by kachar** [comment]
Please link or add the XML format when it's available so we can be on the same page

**Comment by GeorgyGenchev** [comment]
Currently this functionality cannot be implemented correctly, since the data/bank movements/ present in the XML file does not have sufficient data for a donation to be made.

**Comment by GeorgyGenchev** [comment]
Since there is a need for this functionality to be implemented, the issue will be reopened and built from scratch, because the cu rrent branch is really behind in comparison to the master. Some of the data of the bank movements needs to be hardcoded so the donation can be made.
