### ISSUE TITLE
[Feature]Allow/restrict donations on completed campaigns

### ISSUE THREAD

**Issue by Bunny303** [podkrepi-bg/frontend#740]
**Is your feature request related to a problem? Please describe.**
At the moment donations could be done if campaign is completed (target amount is reached). This could be a good option for some types of campaigns, but for others not. 

**Describe the solution you'd like**
When campaign is created a checkbox should be added and it will shows that donations could be made even if target amount is reached. Boolean flag should be added in Campaign type and send on create/update.

**Comment by igoychev** [comment]
The field from backend is called allowDonationOnComplete

**Comment by igoychev** [comment]
This was implemented for Admin/Create Campaign Form, needs to be added in Edit Form too
