### ISSUE TITLE
[Feature] Google signup should send data to the backend

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#770]
**Is your feature request related to a problem? Please describe.**
At the moment we use NextAuth with Google as social provider

However when new user signs up our API never knows about their data

We need to find a way to send the data to the API in a secure manner so our API and Keycloak can create the appropriate setup for the persons.

- https://next-auth.js.org/providers/google
- https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/google.ts
- https://next-auth.js.org/configuration/events#createuser `createUser` and `linkAccount` events

Additional note:

 - The JWT from google differs from the one we use internally - we should find a way to accommodate both even if that means to change the format of the JWT token

**Comment by dimitur2204** [comment]
Are there any concepts of how that should work right now. I see there are providers that can be added to the Keycloak, but is it possible then for that to work through our frontend.

If we do it through NextAuth then how are we supposed to create and link the user to our database. Some ID google provides or an email?

**Comment by kachar** [comment]
The idea is to move the social auth layer from Keycloak server to the NextAuth endpoints of the frontend.

So far we've got it working but our DB is not aware of the accounts provided by Google, so we need to send the social info to our API so it creates a proper person record and maybe register them in the headless Keycloak integration as well.
We might need to add additional fields to the person model to keep some of the social provider's details.

**Comment by igoychev** [comment]
this is closed by @dimitur2204 with commit https://github.com/podkrepi-bg/frontend/commit/99db2232efd3a76b99cf832d58000c0b4744d5c6
