### ISSUE TITLE
[Bug] [Medium] "Open data" page leads to error 404 

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#781]
**Describe the bug**
"Open data" page leads to error 404 

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Разработка'
3. Click on "Отворени данни"

**Expected behavior**
Redirecting to Open Data page

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari] 
Version [15.4]

**Comment by ani-kalpachka** [comment]
Could you please provide the path which this hyperlink has to lead to?

**Comment by petarrr1** [comment]
not specified in the requirements....

**Comment by igoychev** [comment]
We need to add the following text:
### БГ текст
"За да осигури пълна прозрачност на дейноста си, освен отворен код, Подкрепи.бг предоставя също и отворени данни. 
Целта е всеки при интерес да може да достъпи анонимизирани данни показващи движенията на даренията и сумите по сметките свързани с кампаниите. За да достъпите тези данни можете да използвате UI като потребител или директно през публичните методи на API. Описанието на API поддържаме чрез Swagger  на този адрес: https://podkrepi.bg/swagger 

За етичното използване на отворените данни сме избрали да използваме лиценз Creative Commons CC BY-NC 4.0 https://creativecommons.org/licenses/by-nc/4.0/ , според който:
Имате право да:
 - Споделяте - да копирате и повторно да разпространявате материала на всякакъв носител или във всякакъв формат
 - Адаптирате - да преработвате, преобразувате и доразвивате материала 
(Ако спазвате условията на лиценза, лицензодателят не може да отмени тези свободи.)
При следните условия:
 - Признание - Вие сте длъжни да посочите като автор на данните Подкрепи.бг, да дадете електронна препратка към лиценза, и да укажете дали сте внесли промени. Можете да направите това по всеки разумен начин, но не по начин, който предполага, че лицензодателят одобрява Вас или използването от Ваша страна на материала. 
 - Некомерсиално ползване - Вие нямате право да използвате данните за [търговски цели](https://creativecommons.org/licenses/by-nc/4.0/#commercial_purposes) в смисъла на събирането на пари за данните във вид на файл или за достъп до тях.

Без допълнителни ограничения - Вие нямате право да прилагате правни условия или [технологични мерки](https://creativecommons.org/licenses/by-nc-sa/4.0/#technological_measures) които създават правни ограничения за други лица да извършват разрешеното от лиценза.

### EN text
"To ensure full transparency of operations, in addition to the open source code, Podkrepi.bg provides also open data. The motivation is for everyone who is interested to be able to access anonymized data for the transactions of donations and amounts between the accounts related to the campaigns. To access the data you can use the UI as regular user or directly through the public methods of the API. The API description is supported using Swagger on the following url: https://podkrepi.bg/swagger 

For the ethical use of our open data we chose to use Creative Commons CC BY-NC 4.0 https://creativecommons.org/licenses/by-nc/4.0/ according to which:
You are free to:
 - Share — copy and redistribute the material in any medium or format
 - Adapt — remix, transform, and build upon the material
(The licensor cannot revoke these freedoms as long as you follow the license terms.)
Under the following terms:
 - Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by-nc/4.0/#) and mention Podkrepi.bg as data owner, provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-nc/4.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
 - NonCommercial — You may not use the material for [commercial purposes](https://creativecommons.org/licenses/by-nc/4.0/#)

    No additional restrictions — You may not apply legal terms or [technological measures](https://creativecommons.org/licenses/by-nc/4.0/#) that legally restrict others from doing anything the license permits.

**Comment by omniage** [comment]
За да осигури пълна прозрачност на дейността си, освен отворен код, Подкрепи.бг предоставя и отворени данни.
Целта ни е всеки заинтересован да има възможност за достъп до анонимизирани данни, показващи движенията на даренията и сумите по сметките, свързани с кампаниите. За достъп до тези данни можете да използвате UI като потребител или директно през публичните методи на API. Описанието на API поддържаме чрез Swagger на следния адрес: https://podkrepi.bg/swagger.

За етичното използване на отворените данни сме избрали да използваме лиценз Creative Commons CC BY-NC 4.0 https://creativecommons.org/licenses/by-nc/4.0/, според който имате право да:

Споделяте – да копирате и повторно да разпространявате материала на всякакъв носител или във всякакъв формат;
Адаптирате – да преработвате, преобразувате и доразвивате материала;

Забележка: Ако спазвате условията на лиценза, лицензодателят не може да отмени тези свободи.

При следните условия:

Признание – Вие сте длъжни да посочите като автор на данните Подкрепи.бг, да дадете електронна препратка към лиценза и да укажете дали сте внесли промени. Можете да направите това по всеки разумен начин, но не по начин, който предполага, че лицензодателят одобрява Вас или използването от Ваша страна на материала.
Некомерсиално ползване – Вие нямате право да използвате данните за [търговски цели](https://creativecommons.org/licenses/by-nc/4.0/#commercial_purposes) в смисъла на събирането на пари за данните във вид на файл или за достъп до тях.
Без допълнителни ограничения – Вие нямате право да прилагате правни условия или [технологични мерки](https://creativecommons.org/licenses/by-nc-sa/4.0/#technological_measures), които създават правни ограничения за други лица да извършват разрешеното от лиценза.

**Comment by igoychev** [comment]
The issue is still valid - the Open Data Link needs to appear when the new page is added
