### ISSUE TITLE
[Bug] [Minor]  FAQ Hyperlink "тази бланка" not working

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#786]
**Describe the bug**
"Подкрепи.бг прави ли проверки на кампаниите на място?" hyperlink "тази бланка" is not working

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Дарителство'
3. Click on  'Често задавани въпроси'
4. Click on "Кампании"5. 
5. Scroll down to "Подкрепи.бг прави ли проверки на кампаниите на място?"6. 
6. See the error

https://dev.podkrepi.bg/faq#1

**Expected behavior**
Clicking on "Тази бланка" will redirect to a blank

**Screenshots**
![Screenshot 2022-05-23 at 16 01 31](https://user-images.githubusercontent.com/105493182/169826251-a2aca7ee-72d0-489f-921c-b6bf9bfaf7ba.png)

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari] 
Version [15.4]

**Comment by ani-kalpachka** [comment]
Closing the issue because we currently do not have this text in the FAQ page.
