### ISSUE TITLE
[Bug] [Critical] Cannot register new user 

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#788]
**Describe the bug**
An error occurred while trying to register a new user

**To Reproduce**

1. Go to 'Регистрация' https://dev.podkrepi.bg/register
2. Enter valid credentials 
3. Click on "Регистрация" button

**Expected behavior**
A new user is registered and its redirected to My Profile page

**Actual behavior**
An error "Грешен потребител / парола." occured

**Screenshots**
![Screenshot 2022-05-25 at 16 00 06](https://user-images.githubusercontent.com/105493182/170267304-acc3a8f5-e21a-4bb6-9c92-e02f4717ec5e.png)

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari] 
Version [15.4]

**Comment by Bunny303** [comment]
Attached screenshot is for login page, not register.

**Comment by igoychev** [comment]
Tested today and working.
