### ISSUE TITLE
[Bug] [Critical] Login form not working

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#789]
**Describe the bug**
Cant login using valid credentials

**To Reproduce**

1. Go to 'Login' https://dev.podkrepi.bg/login
2. Enter valid credentials 
3. Click "Вход"

**Expected behavior**
Redirecting to "My Profile" page

**Actual behavior**
An error "Грешен потребител / парола." occured

Desktop: 
OS: macOS Catalina 10.15.7 
Browser: safari] 
Version [15.4]

**Comment by igoychev** [comment]
Working now. The issue was fixed a while ago, but the ticket was not updated
