### ISSUE TITLE
[Bug] [Major] the English version of the site has not been fully translated

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#792]
**Describe the bug**
There are still untranslated parts of the site

**To Reproduce**

1. Go to 'Homepage'
2. Change the language to english 
3. See the error
Check the screenshot down below

**Expected behavior**
The whole page has to be translated to english 

**Screenshots**
![Screenshot 2022-05-26 at 15 01 49](https://user-images.githubusercontent.com/105493182/170484612-6fd199a9-8b93-4fa1-a94e-b5df0fffb779.png)

![Screenshot 2022-05-26 at 15 10 16](https://user-images.githubusercontent.com/105493182/170484898-be23f497-bbde-47f2-8abf-0045a91c6cf1.png)

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

**Comment by StanislavSt** [comment]
Closing in favour of https://github.com/podkrepi-bg/frontend/issues/979
