### ISSUE TITLE
[Bug] [Minor] Dropdown menus are lagging 

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#798]
**Describe the bug**
The dropdown menus are lagging and doesn't come out smoothly

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Дарителство' dropdown menu
3. See error

**Expected behavior**
The dropdown menus to come out smoothly and on one time 

**Actual behavior**
The dropdown menus are not coming out smoothly and its flickering when appears

Desktop
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

**Comment by ani-kalpachka** [comment]
I am not able to reproduce this issue. Could it be fixed?
