### ISSUE TITLE
[Design] Apply latest design for CampaignDetailsPage

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#824]
**Description**
We have an updated design from the design team for the CampaignDetails Page available here: https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=11718%3A35769

**Desired solution**
We need to apply the new design and also fill the missing fields that are not displayed in the current one too. For example the names of beneficiary are missing, the campaign state, the file list, dates are not formatted etc

The current design is available here, with a near real campaign:
https://dev.podkrepi.bg/campaigns/rabotilnica-ela

**Comment by ani-kalpachka** [comment]
New changes added: https://github.com/podkrepi-bg/frontend/pull/835

What is left to be done is:
- Get the correct values from the endpoint for the operator's data, campaign's profile and status.
- Fix responsive styles.
- Apply the latest design to Inline Donation.
- Return campaign's slider.
- Add messages/comments.
