### ISSUE TITLE
[Bug] File upload not working with filename in cyrillic

### ISSUE THREAD

**Issue by nradkova** [podkrepi-bg/frontend#834]
Uploading files to campaigns/irregularities with filename in cyrillic - `тест.txt` ends with an error from s3 service - `Invalid character in header content ["x-amz-meta-originalName"]`

**Comment by igoychev** [comment]
The problem was fixed by encoding the file name in this commit on the backend:
 https://github.com/podkrepi-bg/api/commit/ac2b0da5316433900f901ca7fc073c909e502cc6
