### ISSUE TITLE
[Feature] Set position sticky to the basket

### ISSUE THREAD

**Issue by ilievZlatko** [podkrepi-bg/frontend#860]
Set position "sticky" to the basket component so it follows the scroll when user scroll down.

<img width="900" alt="Screenshot 2022-07-07 at 17 29 42" src="https://user-images.githubusercontent.com/18635490/177799084-8a0a471f-fe3c-4136-bd89-dee5181f41d0.png">

**Comment by igoychev** [comment]
fixed with https://github.com/podkrepi-bg/frontend/pull/861 from @ilievZlatko
