### ISSUE TITLE
[Bug] User Session gets broken when any error happens on backend

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#878]
**Describe the bug**
When the backend responds with error, the user session on frontend is lost as if the user tried to access a page without security token. This results in error 401 unauthorized in the browser console and then the user is redirected to User Profile page where the session is silently restored.

**To Reproduce**

1. Open any frontend page that requires data from backend
2. On the backend modify the code to throw an intentional error
3. Reload the frontend page, so that it makes request to backend
4. See error 401 in the browser console and then redirect to Profile page happens

**Expected behavior**
Backend error should be nicely displayed in error message on frontend without loosing the session

**Comment by ilievZlatko** [comment]
This seems to be an issue with the size of the cookie created by keycloak, or something we additionally add to the cookie.
When debugging I got this error:

<img width="982" alt="Screenshot 2022-07-19 at 13 06 25" src="https://user-images.githubusercontent.com/18635490/179725683-2630b123-e160-4bfd-a9a9-0f053c20c97b.png">

**This should be a back-end task!**

**Comment by quantum-grit** [comment]
fixed by https://github.com/podkrepi-bg/frontend/pull/1007
