### ISSUE TITLE
Donation List Paging

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#886]
**Describe the solution you'd like**
[ ]  - Consolidate the donation list queries - need to load only using donations/list, currently the Admin Donation grid loads donations from campaign/donations too
[ ]  - Implement paging also on backend so that to not load all donations at once and slow down the site

**Comment by Juicebgs** [comment]
There is a semi-duplicate issue #935  . @borislavstoychev can you have a look at it?
