### ISSUE TITLE
[Bug] Google authentication not working in production environment 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#895]
User path: Registration - Login with Google 

The result is : Error 400:   redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.

Tested on Chrome (mobile and desktop), Edge,

**Comment by igoychev** [comment]
Fixed now.
