### ISSUE TITLE
[Bug] improvements of home page abou the team 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#899]
To add additional people on the area about podkrepi team
Description (docs) and photos (jpg) https://drive.google.com/drive/folders/1Ml3qOlQgGdPAl0goPpol6DS_ji2vjqs9?usp=sharing

1. Go to home page 
3. Scroll down to 'about the team 
![IMG_20220718_172943](https://user-images.githubusercontent.com/75036745/179602240-9b65d999-3c14-4e42-8c92-8f91f22c2618.jpg)

4. See area for improvement 

**Expected behavior**
Add new people- their photos and positions, can add a link to the blog

**Comment by igoychev** [comment]
due to a problem with the swiper component, this is fixed by removing it - the button "Meet the team" leads to the blog with showing more members anyway
