### ISSUE TITLE
[Feature] Automatic generation of bank expense for Stripe commissions 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#901]
Since Stripe business model is fee based for each transaction – in our case one time fee  (0.5 BGN) + a fixed percentage (1.4%) of every donation made with card we need to address this with an automatic generation of an expense for the campaign after each successful payment. 

The amount of the expense is calculated with the following formula: 0.5 + 0.014*[donation] rounded up to the 2-nd decimal. For example if the donation is 10 BGN an expense related to the campaign to the amount of 0.5 + 0.014*10 = 0.64 BGN should be created and subtracted from the Stripe account balance. 

Please note, that for the phase 1 the one time fee + percentage will be hard coded, when time and resources allow these taxes should be configured from the admin panel.  

Should you have any questions - I am your disposal.

**Comment by stann1** [comment]
see comments on issue #902
