### ISSUE TITLE
[Bug] Campaigns share button not working correctly

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#903]
Our share button is not working correctly for Linkedin and sub-optimal for Facebook. 

When we press the "Share" button in a campaign and choose Linkedin or Facebook there should be an already prepared banner that should be attached to the publication. Currenly for linkedin we are attaching a generic podkrepi.bg banner and not one with photo and description from the campaing we are trying to share and make more popular. 

The social media banner can be added as additional type of file which can be uploaded from the campaign administrator.

**Comment by igoychev** [comment]
this is fixed by setting the campaignListPhoto to og:Image for social media to pick it
