### ISSUE TITLE
[Feature] Campaign donations pagination

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#904]
Currenly in our campaign page there are two scrolls - one of the campaign description, photos, etc and another for scrolling through the made donations. If you want to look through the latter, you must first scroll down to end of the first scroll. My suggestion is to make pagination for donations (for example 5 at a page) in order to solve this ux issue.

**Comment by Juicebgs** [comment]
There is a semi-duplicate issue #935. @borislavstoychev можеш ли да го погледнеш?

**Comment by igoychev** [comment]
fixed with : https://github.com/podkrepi-bg/frontend/pull/945
