### ISSUE TITLE
[Bug] Back button after bank transfer completion leads to error

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#905]
**Describe the bug**
A donor  chooses a campaign, clicks on Support, chooses to use bank transfer, then receives the code and clicks next. Then clicks back, because he didn't copy his code. 

I suppose the back button breaks the session, because the error message is 
"За съжаление, възникна проблем!"

**Comment by borislavstoychev** [comment]
@Juicebgs I can't reproduce the error. Can you check if I'm doing the right steps?


[Screencast from 14.08.2022 19:43:54.webm](https://user-images.githubusercontent.com/67734870/184546922-2008d592-5767-43f2-beaf-1bffa41be34b.webm)

**Comment by igoychev** [comment]
The problem is in the interpretation of the query parameter for success -> when not passed, it is assumed as false and the error is shown.
Check for the logic related to this line in Steps.tsx
const success = router.query.success === 'true' ? true : false.

**Comment by ani-kalpachka** [comment]
I cannot reproduce the issue. It seems to be fixed?
@igoychev could you recheck please?

**Comment by ani-kalpachka** [comment]
Closing this issue as fixed.
Tested on Chrome and Firefox.
