### ISSUE TITLE
[Feature] Donation via bank transfer page - elements to be removed

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#907]
The bank name and BIC code is derived from IBAN so no need for Bank name to be copied 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/74968982/179672432-4a9e1365-0854-4859-9d0d-33a0c3639124.png">

Another useless element - 
<img width="44" alt="image" src="https://user-images.githubusercontent.com/74968982/179672489-09601605-eb9e-4fba-b740-19373d64dbaf.png">
Since it will not open a pop-up and explain into more detail the purpose of the code, it should not be here.

**Comment by igoychev** [comment]
closed by @Margi13  with https://github.com/podkrepi-bg/frontend/pull/926
