### ISSUE TITLE
[Bug] Personal profile - Certificates tab 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#912]
There are numerous problems with the certificates tab - "Download" button not working, the amount is shown in stotinki and not BGN, date filters are not working.

Since we have a donations tab where these issues are fixed and user can download certificate for each donation, let's hide the certificats tab.

**Comment by borislavstoychev** [comment]
@Juicebgs I tried fixing the certificate table instead of hiding it. Please check linked PR!
