### ISSUE TITLE
[Bug] Personal profile not working after session error 

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#914]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/74968982/179678220-4f23e4d7-601a-4a79-be79-e4f35bb16f23.png">

If there is a session error, the user is unable to look at his personal information (name, donations etc.) although it looks like he/she is logged in. The ideal solution would be to not let a session error unlog the user. 

Second best option is to check when a donor clicks on his/her profile if the user is logged and the session is intact.

**Comment by Juicebgs** [comment]
The Issue #878 is connected to this one.

**Comment by quantum-grit** [comment]
Fixed with PR: https://github.com/podkrepi-bg/frontend/pull/1007
