### ISSUE TITLE
[Feature] add beta pop up on home page

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#928]
As we are launching and asking people to go and test the platform we need to tell them that this is still work in progress with a message: 
"Това е бета версията на платформата на Подкрепи.бг преди предстоящия наесен официален старт. Ще сме благодарни, ако ни помогнеш като тестваш платформата и ни върнеш обратна връзка на feedback@podkrepi.bg с нещата, които според теб могат да се подобрят."

Let the popup appear after 30 sec
And have an option to not be show anymore 
Click outside of the popup should close it 
"Затвори" closes the pop up 

Image 
![Group_1255](https://user-images.githubusercontent.com/75036745/180207194-8018b0ef-a379-426c-bdde-6114307a8eb3.png)
Figma
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=13308%3A41211

**Comment by Juicebgs** [comment]
One request - please change the wording as to address our visitors  "Вие" and not "ти".

**Comment by swolf86** [comment]
"не показвай" tickbox actually show you the message on every page refresh. It will be better if it doesn't
