### ISSUE TITLE
[Info site] 404 | 500 Pages needs to be created

### ISSUE THREAD

**Issue by rkgeorgiev** [podkrepi-bg/frontend#93]
404 | 500 Pages needs to be created

- [x] https://github.com/podkrepi-bg/frontend/pull/300
- [ ] 500 page

**Comment by kachar** [comment]
@rkgeorgiev At the moment we've got the following default 404 page

![image](https://user-images.githubusercontent.com/893608/109973798-808b8a80-7d01-11eb-9744-338016c4b345.png)

It's gonna be awesome if we can improve it :rocket:

**Comment by rkgeorgiev** [comment]
> It's gonna be awesome if we can improve it 🚀

I asked the design guys, if they can have a shot at it. That is if they have the time.

**Comment by swolf86** [comment]
Идеята е да имаме анимацийката на ръчичката/пилето,  за 404 

Текста от долу ще :
Съжаляваме, долетял си на несъществуваща страница :)
/Бутон/ Начална страница /Бутон/ Контакти
Гит хъб не позволява да се добави файловете тук 
Ето я задачата с файловете в Ора https://app.ora.pm/p/280006?c=5047067

**Comment by kachar** [comment]
Добавям видео на анимацията

https://user-images.githubusercontent.com/893608/111631361-f90f4280-87fb-11eb-8c6d-908b07dcb789.mp4

**Comment by kachar** [comment]
@polibb Just letting you know that the `404.ts` and `500.ts` error page files have been introduced on master with #152 (#91)

This might conflict if you've started on that as well.
