### ISSUE TITLE
[Bug] leave 5 sums and remove the other 6

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#930]
On donation when presented with the price options to click at the moment we have 11 options. It is good to limit that option not to confuse the user and load load the screeb with unnecessary fields let present 5, 10, 20, 50, 100lv + other 
We have organisers sharing their experience and most of the donations 80% are up to 20 lv

**Comment by igoychev** [comment]
Done, now left with 6 prices: 5, 10, 20, 30, 50, 100 - note , we need them even number, so that the form to align well
