### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by VelikaGeorgieva** [podkrepi-bg/frontend#942]
Hello.
Can you please change the logo for organizator in this page: (https://podkrepi.bg/campaigns/krizisen-centur-za-postradali-ot-nasilie-gr-pernik-shans-za-nov-zhivot) , to the new one , which is attached here: 
![logo pulse bg2](https://user-images.githubusercontent.com/110093767/181208803-6c781db2-9960-4393-8715-421bbd3773bc.png)
 We need also to not place logo at circle.
Thank you in advance.

**Comment by igoychev** [comment]
Just checked - the logo is updated!
Could you check if it is ok now?

**Comment by VelikaGeorgieva** [comment]
@igoychev  it is not ok. It is the same like before. I cannot see some change.

**Comment by marianacat** [comment]
Готово е вече.
