### ISSUE TITLE
[Bug] Long organiser name goes below the organiser logo.

### ISSUE THREAD

**Issue by AnaNikolova** [podkrepi-bg/frontend#960]
**Describe the bug**

Longer organiser names go below the logo at the campaign page (see below).

![Photo 1](https://user-images.githubusercontent.com/110336012/182025834-c2ed43da-f64c-40a6-9c9a-e10be5e6d86a.png)

Shorter organiser names are next to the logo (see below). 

![Photo 2](https://user-images.githubusercontent.com/110336012/182025838-bda1e421-5d83-41fc-8f35-5253c79351c6.png)

The same is on mobile. 

**To reproduce:** 
Would be good to find a way to look the same. Either to distribute the organiser name on more lines when is longer one or to put it below the logo for all.

**Comment by ani-kalpachka** [comment]
The same problem applies for coordinator.
PR created: https://github.com/podkrepi-bg/frontend/pull/970
