### ISSUE TITLE
Header (Global Nav) 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#961]
Header height to be 88px 
Header items to change as shown
![image](https://user-images.githubusercontent.com/75036745/182036763-8d807ea6-50ed-4959-a4b0-3a94affc3cc9.png)
Dropdown menu as shows
![image](https://user-images.githubusercontent.com/75036745/182036801-33cf60a4-24b4-4380-a61d-37cc30861f86.png)
Text if needed on Figma (https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=0%3A7243)

**Comment by igoychev** [comment]
@swolf86 some feedback and questions:
 - the two images have the User Icon and EN/BG swapped - which is the correct one?
 - also if "Дарете" is a button, why is "Подкрепете ни" not a button?
 - with this new design we end up with three Donation elements - "Дарете", "Подкрепете ни", and "Дарителство" which seems even more confusing than helping...

**Comment by swolf86** [comment]
1. User icon should be on right to start with 
2. Подкрепете is secondary button with hover state can be shown 
3. Дарете is shortcut / call to action of a specific elements or Дарителството - urgent campaigns. Подкрепете ни has Ни, which is for the platform itself . Happy to do card sorting (UX activity) to see how what is confusing for donors and how to improve. In the meantime suggestion for better wording is welcomed

**Comment by kachar** [comment]
@swolf86 Right now the header height is flexible and dynamic according to the user scroll position. Do you want us to downgrade it to be fixed height? I'd vote against that if my vote counts.

**Comment by kachar** [comment]
Also, there's no search icon right now, seems your designs are outdated regarding the real website at this moment.

**Comment by swolf86** [comment]
Header height take space from hero image and main call to action, sentences and buttons are not visible at above the fold on all resolutions. We don't mind being flexible just initial stage header height should be smaller. 

As we building more and more pages, faq, blogs, content - Search is more and more needed functionality which I hope we can achieve at some point. Got your point we need to present correctly

**Comment by swolf86** [comment]
Let's put this update on hold and continue discussion in the channels?

**Comment by ani-kalpachka** [comment]
The discussed changes are applied in this PR: https://github.com/podkrepi-bg/frontend/pull/1001
The initial height is reduced, however the dynamic scroll height is saved.
Please review and advice if the changes fit all these requirements.
