### ISSUE TITLE
[Bug] YouTube videos doesn't play or play for 30sec and stops automatically 

### ISSUE THREAD

**Issue by swolf86** [podkrepi-bg/frontend#973]
On both campaign pages when you click to play the video it doesn't start always playing straight away. When you click again it plays for 30 sec and stops with no other interactions 

Video recording https://photos.app.goo.gl/TahC3BEqngmetBht6

Problem appeared at least on 3 users

**Comment by igoychev** [comment]
fixed by removing the autorefresh with this PR: https://github.com/podkrepi-bg/frontend/pull/1032
