### ISSUE TITLE
[Bug] Donations count in campaigns != number of donations in campaign

### ISSUE THREAD

**Issue by Juicebgs** [podkrepi-bg/frontend#984]
**Describe the bug**
I noticed a discrepancy between number of donations shown in the pagination and the total donations number 

<img width="287" alt="image" src="https://user-images.githubusercontent.com/74968982/182880504-3b85a7f6-abaa-4b99-9979-afe1671c35d9.png">

Let's find out the root of the problem

**Comment by imilchev** [comment]
I think the number is correct. The number on the top is not showing the donations but the unique donators that have contributed to that campaign. The number on the bottom is the is the actual donations. Mariyana donated twice, hence the difference between unique donators and donations.

Double-check this and if you think that makes sense, close the ticket

**Comment by Juicebgs** [comment]
@imilchev  that was quick ;) 
Closing ... Although it is questionable whether all anonymous donations shouldn't be counted as 1 donor.
